### ISSUE TITLE
Support VS2017 V15.2

### ISSUE THREAD

**Issue by YZahringer** [Xavalon/XamlStyler#103]
There is a bug with 15.2 version, the XAML remains in black color when the plugin is active (on Xamarin.Forms XAML).

**Comment by boguslawblonski** [comment]
After todays Vs2017 xamrin  update XAML  coloring was out all text was grey , had to change theme to Light and again to Dark came out on more than one station

**Comment by NicoVermeir** [comment]
@YZahringer can you confirm that that solves your issue? I can't reproduce it on my machine

**Comment by YZahringer** [comment]
Yes, theme switch solve issue
