### ISSUE TITLE
Attribute Tolerance & Max Attributes Per Line

### ISSUE THREAD

**Issue by jur007** [Xavalon/XamlStyler#107]
https://github.com/Xavalon/XamlStyler/wiki/Attribute-Formatting

I dont get the difference. Why are there both values?

If the number of attributes exeeds the tolerance "Max Attributes Per Line" comes into play.
But why do I need different values then?

**Comment by grochocki** [comment]
Attribute Tolerance allows you to specify how many attributes must be present before it is split into multiple lines, while Max Attributes Per Line allows you to specify how many attributes can exist per line.

> [Max Attributes Per Line] defines the maximum number of attributes an element can have on each line after the start tag if the number of attributes exceeds the Attribute Tolerance.

If Attribute Tolerance is 4, but Max Attributes Per Line is 2, you would see this:
```
<TextBlock Margin="4" FontSize="12" Text="Test" />

<TextBlock
    Margin="4" FontSize="12"
    FontWeight="Bold" VerticalAlignment="Center"
    Text="Test"  />
```

**Comment by jur007** [comment]
So with Tolerance 4 and Max Attr at 2, if I type in 3 Attributes, it wont get moved.

**Comment by grochocki** [comment]
Correct. 1-4 attributes will stay on one line.

**Comment by jur007** [comment]
thx now it works. If I dont reload the json cfg I get strange sideeffects. Now I see, thx!
