### ISSUE TITLE
Settings.XamlStyler when solution folder is not a parent folder and/or in parallel of the project file

### ISSUE THREAD

**Issue by fforjan** [Xavalon/XamlStyler#108]
In our solution,
we have something like : 
- GUI
    - Project1
        Views \ Styles \ basic.xaml
        Project.csproj
       Settings.XamlStyler
    - Project 2
- Server
- Product
    product.sln
    Settings.XamlStyler

While reading the code, https://github.com/Xavalon/XamlStyler/blob/master/XamlStyler2.Package/StylerPackage.cs
It seems our Settings.XamlStyler will never be picked by the package algorithm while formatting the basic.xaml as -
- project and solution path are not common ancestor (GetConfigPathInsideSolution algorithm)
- Settings.XamlStyler is at the same level of the project  (GetConfigPathOutsideSolution algorithm)
 
Is my understanding correct ?

**Comment by fforjan** [comment]
Could we have a simple change to check for <solution name>.XamlStyler ?

**Comment by grochocki** [comment]
I would have to do some testing to double-check this did not break, but the [documentation](https://github.com/Xavalon/XamlStyler/wiki/External-Configurations) should be accurate:

> Alternatively, put your external configuration inside a "Settings.XamlStyler" file in any directory up through your solution directory and this configuration will take precedence. **XAML Styler will respect the first configuration file it finds in the folder up-hierarchy**, so it is possible to use separate configurations for different projects or subdirectories.

I believe #73 discusses this a bit more, and #75 is the fix for both the plugin and the console application.

**Comment by fforjan** [comment]
I'm using version 2.4 which should have the fix, but as said, looking at the code I don't think this is working in my case.

**Comment by grochocki** [comment]
Ok, will look into it.

**Comment by jyardin** [comment]
This is what the PR I submitted a few months ago is supposed to fix : 
https://github.com/Xavalon/XamlStyler/pull/102

**Comment by grochocki** [comment]
Resolved by #102
