### ISSUE TITLE
External configuration file doesn't work on VS2017

### ISSUE THREAD

**Issue by chrisxvin** [Xavalon/XamlStyler#114]
The same file works on VS2015, but not in VS2017.
I'm using VS2015 Pro and VS2017 Ent.

**Comment by grochocki** [comment]
Is the only difference VS2015 vs. VS2017? Can you share the troublesome configuration?

**Comment by Spidermain50** [comment]
I am experiencing the same issue with VS 2017. The external configuration file is not working. It is working for VS 2015

**Comment by NicoVermeir** [comment]
I can't seem to reproduce this. 
Can you verify if this is still an issue and share the config file with us?

If it's still an issue, could you also try with the default configuration from the wiki? Maybe it's one setting in your config that doesn't work.

**Comment by grochocki** [comment]
I am also not able to repro this. Please feel free to reactivate with more information if you continue to run into this problem.
