### ISSUE TITLE
No detecting with CodeMaid

### ISSUE THREAD

**Issue by saiyadjin** [Xavalon/XamlStyler#115]
Using CodeMaid 10.4, under its setting you can select 
automatic use of XAML styler. but since version 2.4 of xaml styler it doesn't work anymore and you can't run the beautify on whole document.

They provided the code that runs XAML styling in older versions, could you just type down what should be replaced this with so it can work again?

`_commandHelper.ExecuteCommand(textDocument, "EditorContextMenus.XAMLEditor.BeautifyXaml", "EditorContextMenus.XAMLEditor.FormatXAML");`

**Comment by grochocki** [comment]
The command changed due to changes to the code editor menu command ids in Visual Studio 2017. The fix lives in the CodeMaid codebase and is referenced by [this issue](https://github.com/codecadwallader/codemaid/issues/401). Please continue conversation there.
