### ISSUE TITLE
Add "Align with opening bracket" flag to "Put Ending Brackets On New Line" option

### ISSUE THREAD

**Issue by FlorianObermayer** [Xavalon/XamlStyler#117]
The `Put ending Brackets On New Line` option currently formats xaml as such:
```xaml
    <Label
        Grid.Row="2"
        Padding="0"
        />
```
 where as I'd prefer the closing bracket to be aligned with the opening bracket like so:
```xaml
    <Label
        Grid.Row="2"
        Padding="0"
    />
```
This is more conform with e.g. K&R code styles and shoud be worth an extra flag in the settings.

**Comment by grochocki** [comment]
K&R does not really apply to the closing bracket in XAML, and since this styling does not appear to conform to styling in any XAML documentation or large body of code, this is not something we are looking to add to XamlStyler at this time.

**Comment by SuperCorks** [comment]
I'm upvoting this. It's something I'd like to have too
