### ISSUE TITLE
Option for column limit

### ISSUE THREAD

**Issue by grochocki** [Xavalon/XamlStyler#12]
From @kgallaha: I'd like a Hard Column Limit added to the Attribute Formatting section. It would usually be set to 80 - 120 which represents the limits typically set when formatting C#.

This limit would force attributes to be broken onto separate lines (assuming they were originally within an attribute tolerance >1), followed by enforcement of the Max Attributes Per Line rule. This would prevent attributes from trailing off the visible area of editors (thus requiring horizontal scrolling) while still allowing for an attribute tolerance greater than 1 (in the event there are several short attributes which could fit within the column limit).

Since the Characters Per Line limit doesn't include indentation and requires Max Attributes Per Line >1 it serves a different (somewhat niche) purpose. It doesn't prevent code from trailing off the screen and requires you to set the Max Attributes Per Line at 2 or more.

My main desire for XAML elements is to have them reside on a single line until they leave the visible area (break a column limit) in which case I want all of the attributes on separate lines.

In the event one attribute breaks the column limit then I wouldn't worry about trying to introduce any line breaks inside of it - I imagine this could get messy very quickly. This is the simple solution and would be the least confusing to users as a single setting. 

If you'd like to include a checkbox to wrap long attributes as well then I imagine someone might appreciate it. I don't know how much extra work would go into that (considering all the edge cases) and would be plenty happy with just to first option. It would be further complicated if someone wanted splitting on commas and/or spaces.

**Comment by grochocki** [comment]
See #122 for consideration of respecting VS Tag Wrapping settings as a potential default.

**Comment by grochocki** [comment]
While column break rules work for most languages, we do no believe they make a lot of sense for markup languages like XAML and believe there are already a number of options to help break out attributes on newlines in a way that works well.

**Comment by mikernet** [comment]
I really think this should be reconsidered for addition. Just like code should wrap things like method parameters if it extends beyond a certain column, attributes should start to wrap at the same column width. The only thing that makes sense for me is wrapping at a total character width including indentation, not excluding it. If it fits inside my VS window width then it doesn't need to wrap, otherwise it does.

**Comment by dvdgnz** [comment]
Upvote for this. I agree first line attributes should be split even if below the tolerance if they exceed a certain length. While a hard-column limit might not be desiderable, first line attributes without indentation and tag could still obey the maximum characters rule.
