### ISSUE TITLE
Comply with Tag Wrapping settings

### ISSUE THREAD

**Issue by JCKodel** [Xavalon/XamlStyler#122]
![image](https://user-images.githubusercontent.com/379339/30410354-efc8f5bc-98e0-11e7-9b38-a0102f05dd45.png)

It would be possible to ignore the ```Max attributes per line``` (or set to a high value) and obey the above configuration (```Wrap tags that exceed specified length```)?

In other words: make attributes fill the line until reach column 150 (or whatever is and IF is configured in Text Editor > XAML > Formatting > Tag Wrapping).

I'm lost between the default VS formatting options (lack the XamlStyler options) and XamlStyler (lack this feature).

**Comment by grochocki** [comment]
Similar to #12. Going to close this as a duplicate feature request, but add additional details to #12 about being mindful of VS settings (likely as a default).
