### ISSUE TITLE
Req: Toggle one line xaml

### ISSUE THREAD

**Issue by regrem** [Xavalon/XamlStyler#123]
This extension is great. But sometimes i would like to toggle so all xaml is formated on one single line.
Not one line per xaml file but one line per xaml item.
Example:
from this:
```
<Label
            Grid.Row="12"
            Grid.Column="0"
            Content="{T:Translate BF Name,
                                  Format=' {0}:'}"
            Style="{StaticResource K2M_Label_Base}" />
```
to this:
```
<Label Grid.Row="12" Grid.Column="0" Content="{T:Translate BF Name, Format=' {0}:'}" Style="StaticResource K2M_Label_Base}" />
```
I want to do this because it is alot easier to mass edit things like row/columns and such.

After i have done the editing i want to format it back to the very nice formating that XamlStyler already does.

**Comment by grochocki** [comment]
Thank you for the feature request, but we feel that this is too specialized of a use case to accept. Both styles you are talking about are possible with the right configuration, but switching between multiple styles for the purpose of editing is not a feature we are looking to add at this time.
