### ISSUE TITLE
Visual Studio for Mac

### ISSUE THREAD

**Issue by keyduq** [Xavalon/XamlStyler#135]
Any plan to support Visual Studio for Mac?

**Comment by NicoVermeir** [comment]
we're not actively working on it, it's somewhere on the backlog.
we'd happily accept a PR though :)

**Comment by NicoVermeir** [comment]
let's make this happen! (no timeframe though :))

**Comment by alickmail** [comment]
This is a good news!!!!

**Comment by charce36** [comment]
branch for work in progress?

**Comment by NicoVermeir** [comment]
progress report: there's a branch! :)
current status: the extension works, but no format on save for now, still looking into how to get this done (if anyone knows, feel free to reach out or create a PR)

**Comment by NicoVermeir** [comment]
it's based off of that version, I've reached out to the original author a long time ago but never got a reply. I would still very much like for him to get on board and make it the official XAML Styler for mac

**Comment by petero-dk** [comment]
Cool, we are using his latest VisualStudio for Mac add-in and the Official one here for Windows, I am not sure how they handle the project configuration files and the settings are not quite the same, so we are looking forward to an official version :-)

**Comment by skadookkunnan** [comment]
Could you please upgrade it for Visual Studio fo Mac 2019 version. The Mono libraries needs to be upgraded to get it working :(

**Comment by Saratsin** [comment]
I think this one can be closed

**Comment by NicoVermeir** [comment]
definitely :)
