### ISSUE TITLE
Multiline comment padding

### ISSUE THREAD

**Issue by gpetrou** [Xavalon/XamlStyler#136]
The CommentPadding option works well with regards to one line comments such as:
`<!-- Single line -->`
When using multiple lines though, I see that there are 4 spaces.
Is this the expected behavior?

      

Shouldn't the CommentPadding option affect this?

**Comment by grochocki** [comment]
This setting was intended for spacing for single-line comments. Multiline comments respect the indent size setting (defaults to Visual Studio settings, but can be overwritten with [configuration file](https://github.com/Xavalon/XamlStyler/wiki/External-Configurations#indent-size))
