### ISSUE TITLE
Grouping by owner type

### ISSUE THREAD

**Issue by Deni35** [Xavalon/XamlStyler#145]
It would be conveniently if attributes were grouped by its owner type.
I.e. Visibility or FontSize at the beginning. More specific attributes at the end.
Also attributes ending on Id or Style would be good to placing at the beginning.

**Comment by grochocki** [comment]
This is fully customizable with the [Attribute Order Rule Groups](https://github.com/Xavalon/XamlStyler/wiki/Attribute-Reordering#attribute-ordering-rule-groups) feature. Does this meet you needs?

**Comment by grochocki** [comment]
XAML Styler does not analyze class hierarchy, so it would not be able to order attributes based on that (e.g., DependencyObject attributes, followed by attributes for FrameworkElement, Control, etc.), if that is what you are after.

**Comment by grochocki** [comment]
Closing due to reasonable customization options available with Attribute Order Rule Groups.
