### ISSUE TITLE
Inline elements being modified on format

### ISSUE THREAD

**Issue by Heldenkrieger01** [Xavalon/XamlStyler#152]
_Proposal: Implement a setting which allows to exclude certain tags and all its children from getting styled._

This could also be considered a bug, since it alters my end result shown to the user, which in my opinion should not happen.

**Reason why:** Elements like TextBlock are sensitive to line breaks in code, as follows:

Here is the code **before** being styled, together with the result: **_(desired output)_**
![before_xamlstyler](https://user-images.githubusercontent.com/6423282/39114487-49b7ff12-46df-11e8-96d9-fd9ca9b87238.png)

Here is the code **after** being styled, together with the result: **_(actual output)_**
![after_xamlstyler](https://user-images.githubusercontent.com/6423282/39114609-a0a64fd6-46df-11e8-8389-c46a6159c71a.png)

I am using the latest version of XamlStyler.

**Comment by grochocki** [comment]
If it is just inline elements that are causing you headache, that is a bug, as XAML Styler should not be making any changes that cause whitespace changes in TextBlock.

Otherwise, I think the rest of the request is covered by #9 and #44.

**Comment by Heldenkrieger01** [comment]
It's only the inline elements which cause trouble in this case @grochocki

**Comment by grochocki** [comment]
Closing as dupe of #203, which has an easier repro. Let me know if you disagree, and we can reopen this one.
