### ISSUE TITLE
Advance search locations for configuration/settings file

### ISSUE THREAD

**Issue by SokoFromNZ** [Xavalon/XamlStyler#155]
**Current situation:**
When saving any xaml-file in VS XamlStyler searches for the Settings.XamlStyler file from the location of the xaml-file up to (and including) the directory where the solution file (*.sln) is located.

**Issue:**
For teams with more than one application - and therefore more than one solution - it is not possible to have one file system based XamlStyler settings for all solutions.

**Existing solutions:**
1.) Copy the same Settings.XamlStyler file into all solution directories
2.) Set the Settings.XamlStyler file in the Visual Studio XamlStyler settings page

**Issues of existing solutions:**
ad 1.) You have to keep redundant information in multiple files, have to make sure you make changes in all of them and must remember to copy the file each time you are creating a new solution
ad 2.) It is not possible to keep different versions of the settings for different versions of the applications. I.e. you want to change the settings just for your solutions in v4.04 of your programs and keep the old settings for v4.03 of all your solutions.

**Suggested solution:**
Let XamlStyler optional search for the Settings.XamlStyler file not only up until the solution directory but up until the drive root. Of course and as usual: Until it finds the first Settings.XamlStyler file.

For this suggested solution I've already placed the pull request https://github.com/Xavalon/XamlStyler/pull/154.

**Comment by SokoFromNZ** [comment]
Hi,

The file is not outside the TFS/repo structure. One example folder in our TFS structure is: /TFS/WIN/v4/Dev/v4.03.XX/...
In this folder we have different solutions (> 10) in different folders(depths) with all the apps that belong to v4.03.XX.
The Settings.XamlStyler file is put in the v4.03.XX folder and will then work for every solution in this folders sub-structure.

I understand your 2nd point. But with our structure above you see how its not working.

Your 3rd point is not a problem. I implemented the option in the settings just there might be no performance issues with searching all the way to the drives root when its not neccessary...

**Comment by XamlNerd** [comment]
I would really appreciate this modification in the search algorithm. When will the associated pull request be completed?

**Comment by grochocki** [comment]
Fixed by #154
