### ISSUE TITLE
Any plan to support Visual Studio for Mac?

### ISSUE THREAD

**Issue by moogiis** [Xavalon/XamlStyler#158]
I need your help 😄

**Comment by NicoVermeir** [comment]
we're working on it:
https://github.com/Xavalon/XamlStyler/issues/135

it's going slowly because of time restraints. 
the branch is there: https://github.com/Xavalon/XamlStyler/tree/135-VisualStudio4Mac
the code works, it doesn't format on save yet and not all options are tested

**Comment by moogiis** [comment]
Thank you for your reply 😄

**Comment by NicoVermeir** [comment]
as I've said, this hasn't been released yet :)
it's very much a work in progress

**Comment by grochocki** [comment]
Closing this duplicate feature request. Keep the conversation going in #135
