### ISSUE TITLE
Option for closing tag indentation

### ISSUE THREAD

**Issue by denisz1** [Xavalon/XamlStyler#16]
Python style sort of thing

from:

    <foo>
      <bar>
      <baz>
    </foo>

to:

    <foo>
      <bar>
      <baz>
      </foo>         <--- this is indented

**Comment by NicoVermeir** [comment]
We've reviewed this but are not really sure if this is something that people want. After asking around, I found no one that would like this style of xml formatting so I don't know if it's worth the effort of building this in but we'd like to open up a discussion about this, if other people are interested as well

**Comment by punker76** [comment]
I have never seen this on any Xaml code. And I think this is not a good style. Any benefits?

```xaml
<foo>
  <bar />
  <baz />
  <anotherfoo>
    <baz />
    </anotherfoo>         <--- this is indented
  </foo>         <--- this is indented
```

**Comment by JohanLarsson** [comment]
This is probably not going to be commonly used, don't think I have seen it anywhere. Should be configurable via setting but not sure it is worth the effort/added complexity.

**Comment by denisz1** [comment]
It is called Banner style and is common in various languages. In Python it's standard.

Maybe it's not worth the effort now, but it's not a "bad idea". It keeps code readable, which is why it is used. We use it all the time, code is much cleaner and easier to read and maintain. XML is called "tag soup" for a reason, this minimises the soup.

Maybe in some future version.

**Comment by grochocki** [comment]
Fair point about possibly being more common in other languages, but it seems to be non-standard XAML styling. Because of this, I am going to close this issue as _wontfix_. Of course, if there is an increase in demand for this type of formatting in the future, we can always revisit the issue.
