### ISSUE TITLE
Use FormatOnSave setting in Settings.XamlStyler

### ISSUE THREAD

**Issue by tmatz** [Xavalon/XamlStyler#161]
Please use "FormatOnSave" setting in "Settings.XamlStyler" file.

I want to format XAML files only in the specific projects.

- Root/
    - Solution.sln
    - Settings.XamlStyler **setting 1**: FormatOnSave = false
    - Project1/
          - Project1.csproj
          - Project1.xaml
    - Project2/
          - Project2.csproj
          - Project2.xaml
          - Settings.XamlStyler **setting 2**: FormatOnSave = true

Project1.xaml is **not** formatted on save (according to **setting 1**).

Project2.xaml is formatted on save (according to **setting 2**).

**Comment by valsby** [comment]
According to the Wiki page configuration file, it seems possible to set the FormatOnSave configuration - but it seems to be ignored. Do I do something wrong, or is it ignored? Can you only set this setting through VS? I am using VS 17.

**Comment by grochocki** [comment]
> According to the Wiki page configuration file, it seems possible to set the FormatOnSave configuration

Hmm, you are right. Let me dig into this to see whether it was intended to be include in the config and at some point it regressed, or was unintentionally added and isn't respected at all.

**Comment by tmatz** [comment]
Implemented here https://github.com/tmatz/XamlStyler/commit/1d4bdbc5c6a41a9723de33e9513bbc0ee69fd312 .

**Comment by grochocki** [comment]
@tmatz Feel free to submit a PR with your change. Looks good (I am not the biggest fan of early returns, but we are not consistent anyways...)!

**Comment by tmatz** [comment]
@grochocki Thank you! I submitted PR now. I added fix description about default value of FormatOnSave.
