### ISSUE TITLE
Add setting to customize supported file extensions like XAML, AXML

### ISSUE THREAD

**Issue by takacsalbert** [Xavalon/XamlStyler#162]
Hi,

I am developing Xamarin Android apps and formatting is a pain for AXML files just like for XAMLs.
I love Xaml Styler and I believe this should be integral part of Visual Studio.

So my recommendation is to add a setting for supported file extensions. You could add your own to a list of values. I would really appreciate such a feature.

Thanks in advance,
Albert

**Comment by NicoVermeir** [comment]
The problem here is not so much file extensions, but the editor that Visual Studio uses.
We need to have the GUID for the used editor and adjust the package to load whenever that editor gets loaded, I'm not sure if this is something we can do dynamically

**Comment by goldcode** [comment]
I noticed that i could have use for the plugin while editing wix setup projects. e.g. wxs files. On renaming to xaml, the formatting of the wxs file worked fine! I wonder if the styler can be used for all xml like documents. I didnt seem to find any suitable extension on Marketplace yet.

**Comment by grochocki** [comment]
After further review, we have decided to not move forward with adding support for other markup languages. While some of these languages are _similar_, it would be difficult to optimize for all of them. Instead, we would like to focus on investing in more advanced XAML-specific styling and refactoring features. Thanks for your contribution!
