### ISSUE TITLE
.editorconfig support

### ISSUE THREAD

**Issue by sonnemaf** [Xavalon/XamlStyler#164]
It would be nice if you supported the .editorconfig file for storing the settings. Not a must have but just nice.

**Comment by RCP161** [comment]
Are you maybe looking for a "[Settings.XamlStyler](https://github.com/Xavalon/XamlStyler/wiki/External-Configurations)"? I wouldn't prefer mixing this two files, because they have different jobs. I put it the settings next to the .editorconfig , .gitignore , ... in a SolutionsItems Folder.

**Comment by grochocki** [comment]
@sonnemaf any reason Settings.XamlStyler does not work for you?

**Comment by NicoVermeir** [comment]
discussed with @sonnemaf we can close this for now
