### ISSUE TITLE
Add a 'Generate Settings.XamlStyler file from settings' button in the Options

### ISSUE THREAD

**Issue by sonnemaf** [Xavalon/XamlStyler#165]
It would be nice if there was an 'Generate Settings.XamlStyler file from settings' button in the Options dialog. Similar to the 'Generate .editorconfig file from settings' button in VS2019.

**Comment by grochocki** [comment]
Great idea! Closing as duplicate of #60, which captures the same spirit of this. Added a note that implementation might be better in VS options as opposed to standalone.
