### ISSUE TITLE
Can't install on VS for Mac v7.6.11(build 9)

### ISSUE THREAD

**Issue by softsan** [Xavalon/XamlStyler#166]
I not able to find it in Extension in my visual studio for Mac.
So i downloaded it from here [here](https://xampubdl.blob.core.windows.net/addins/Addins/Beta/Mac/6.0/Xavalon.XamlStyler-1.0.3.mpack)

and then install it via "Install from file" option in Extention manager in VS for Mac. but it show me following error:
<img width="430" alt="screenshot 2018-11-30 at 8 48 04 pm" src="https://user-images.githubusercontent.com/7391319/49297831-d13c2980-f4e1-11e8-879f-65cd401c4abe.png">

Any thougts? Thanks

**Comment by dishantmshah** [comment]
@NicoVermeir I guess now there's an official release for VS Mac, still getting the same error in VS 2019 for Mac. 

VS Version: 8.0.1
Mac Version: 10.14.4

**Comment by Saratsin** [comment]
@dishantmshah that's strange behavior, have you downloaded it from VS for Mac Extensions repository (directly from VS for Mac, not from browser)?

**Comment by dishantmshah** [comment]
@Saratsin I tried both the way( Via setting up repository and also downloading the extension). Same issue with bot the approach.

**Comment by dishantmshah** [comment]
<img width="422" alt="Screenshot 2019-06-03 at 12 19 16 PM" src="https://user-images.githubusercontent.com/39511878/58788065-bf5e4f00-8608-11e9-8d9a-70de54c8be15.png">

Attaching a screenshot of the error that I am getting.

**Comment by Saratsin** [comment]
@dishantmshah what is your version of VS for Mac, 8.0.9 or some earlier?

**Comment by Saratsin** [comment]
Saw in previous comment. Try to update your VS for Mac. This should fix the issue

**Comment by dishantmshah** [comment]
After upgrading VS it worked. Thanks.
