### ISSUE TITLE
Make it work with VS 2019

### ISSUE THREAD

**Issue by jamers99** [Xavalon/XamlStyler#167]
Just downloaded the preview of VS 2019 and most extensions work and the only important one that I really need is Xaml Styler!

**Comment by jamers99** [comment]
Any status on the progress?

**Comment by xperiandri** [comment]
https://blogs.msdn.microsoft.com/visualstudio/2018/09/26/how-to-upgrade-extensions-to-support-visual-studio-2019/

**Comment by xperiandri** [comment]
Do you know who in MS can issue a signature key?

**Comment by jamers99** [comment]
I couldn't find in the documentation where it says you need a key of any sort...

**Comment by xperiandri** [comment]
@jamers99, key is required for Blend

**Comment by jamers99** [comment]
Is there documentation on it?  I don't know how to get a key, but I would assume that if a key is required there would be good documentation somewhere on how to get a key.

**Comment by xperiandri** [comment]
I'm not sure that documentation is available about that.

**Comment by jamers99** [comment]
Where do you find you need a key?

**Comment by xperiandri** [comment]
You can check an issue about Blend

**Comment by jamers99** [comment]
Do you have a link?

**Comment by NicoVermeir** [comment]
The key we got for Blend 2015 should still work for 2017 and 2019 I think.
I'm going to build a new vsix and upload it to the gallery today, if it doesn't work in Blend we can reach out to MS

**Comment by NicoVermeir** [comment]
3.2 is being verified by the marketplace, should be up soon

**Comment by gojanpaolo** [comment]
Hi. Is there any plans on when this will be released to the marketplace? Thanks! :)

**Comment by jamers99** [comment]
It is already! I've been using it.

- James Esh

________________________________

**Comment by gojanpaolo** [comment]
ugh. I was searching `xamlstyler` instead of `xaml styler`. thanks for confirming. :)
