### ISSUE TITLE
Unable to update to 3.2

### ISSUE THREAD

**Issue by pkoelbl** [Xavalon/XamlStyler#169]
Get this error when trying to update. i am on VS 2017 15.9.5 btw

1/9/2019 4:21:55 PM - The extension will be upgraded from version 3.1.
1/9/2019 4:22:01 PM - Extension cannot be installed to the following products due to missing prerequisites:
1/9/2019 4:22:01 PM - 	Microsoft Visual Studio Professional 2017
1/9/2019 4:22:01 PM - 		-------------------------------------------------------
1/9/2019 4:22:01 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
1/9/2019 4:22:01 PM - 		Name         : Visual Studio core editor
1/9/2019 4:22:01 PM - 		Version      : [15.8.27729.1,17.0)
1/9/2019 4:22:01 PM - 		Error        : The prerequisite version specified does not match the version installed
1/9/2019 4:22:01 PM - 
1/9/2019 4:22:02 PM - System.InvalidOperationException: No modifications could be applied.
   at VSIXInstaller.MultipleChangePage..ctor(ExtensionData data)
   at VSIXInstaller.LoadingPage.<>c__DisplayClass15_1.<OnLoaded>b__2()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by QuentinSuckling** [comment]
Yep, I'm getting the same error as well.

**Comment by lennartb-** [comment]
I'm getting the same error with 3.2.3, exact same log entries as the initial post. It's interesting that the version of the core editor reported in the error (15.8.27729.1,17.0) is lower than my actual VS version (15.9.5, which is the latest as of today)

**Comment by NicoVermeir** [comment]
@lennartb- can you try uninstalling xaml styler first?

**Comment by lennartb-** [comment]
Uninstalls fine, but same error when trying to install. I also tried emptying the ComponentModelCache, but that did nothing either.

**Comment by pkoelbl** [comment]
Yes i am still getting the same error

**Comment by NicoVermeir** [comment]
can you try with this vsix:
[https://1drv.ms/u/s!AnM0l16xWzRaxdB2Wr5d3TBEqJGuEw](https://1drv.ms/u/s!AnM0l16xWzRaxdB2Wr5d3TBEqJGuEw)
I'll upload it to the marketplace once it's confirmed working

**Comment by lennartb-** [comment]
@NicoVermeir Works for me

**Comment by NicoVermeir** [comment]
awesome, 3.2.4 is now on the marketplace

**Comment by DoCode** [comment]
Update failed on VS16.  

@NicoVermeir please fix the prerequisites to support VS16:
```
16.01.2019 12:53:42 - 	References         : 
16.01.2019 12:53:42 - 	Prerequisites      : 
16.01.2019 12:53:42 - 		-------------------------------------------------------
16.01.2019 12:53:42 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
16.01.2019 12:53:42 - 		Name         : Visual Studio core editor
16.01.2019 12:53:42 - 		Version      : [15.0,16.0)
```

Move Version to `[15.0,17.0)`!

**Comment by NicoVermeir** [comment]
@DoCode ow wauw… the prerequisite setting screen sure likes to automatically change values o.O
new version is up!

**Comment by pkoelbl** [comment]
Works now, thanks for the quick turn around
