### ISSUE TITLE
Unable to update to 3.2.5

### ISSUE THREAD

**Issue by re-ba** [Xavalon/XamlStyler#171]
Have 3.1 installed. Cannot update to newest Version. Uninstall of 3.1 fails and install Fails.
Error message is 
22.01.2019 11:58:45 - vsPkg.Version is '3.1'.  extension.Header.Version is '3.1'
22.01.2019 11:58:47 - Unable to find component in product catalog with this ID: Component.0c572937-0d4a-48cc-aa3f-875ffa9805ba,version=3.1
22.01.2019 11:58:47 - Installationsfehler: System.InvalidOperationException: Im Katalog muss ein Wert für "Component" angegeben werden.

Attached is catalog.json (Extension txt) and complete log file
[catalog.txt](https://github.com/Xavalon/XamlStyler/files/2782594/catalog.txt)
[VSIXInstaller_578abb00-c7c6-4a8a-86a6-22a0d5b714c5.log](https://github.com/Xavalon/XamlStyler/files/2782595/VSIXInstaller_578abb00-c7c6-4a8a-86a6-22a0d5b714c5.log)

**Comment by grochocki** [comment]
@re-ba Are you still having issues? I am not able to repro this problem.

**Comment by re-ba** [comment]
Today I tried again. Uninstall And update still do not work.
Attached are the log files.
Please help.

[VSIXInstaller_8a7996b6-9ef1-4b0d-84f3-84841f9fd53a.log](https://github.com/Xavalon/XamlStyler/files/2974939/VSIXInstaller_8a7996b6-9ef1-4b0d-84f3-84841f9fd53a.log)

[VSIXInstaller_d5834173-91bb-4518-bd10-1be7eb3c7f38.log](https://github.com/Xavalon/XamlStyler/files/2974940/VSIXInstaller_d5834173-91bb-4518-bd10-1be7eb3c7f38.log)

**Comment by NicoVermeir** [comment]
it looks like this was a known issue in Visual Studio a while back.
can you see if this fixes it: https://github.com/github/VisualStudio/issues/1295#issuecomment-348027716
(that post is about the github extension, obviously replace github with xaml styler in the steps :))

**Comment by re-ba** [comment]
Thank you very much. Deleting the directory of version 3.1 made Version 3.2.5 coming up without any more action. Problem is solved now.

**Comment by NicoVermeir** [comment]
awesome! thanks for reporting back :)
