### ISSUE TITLE
Add option to XamlStyler.Console to perform a formatting check without changing output

### ISSUE THREAD

**Issue by HofmeisterAn** [Xavalon/XamlStyler#176]
It would be great if we are able to check, if XamlStyler was applied to the `xaml` files. I would like to add a stage to my CI build which breaks, if anyone forgot to apply the style rules.

Is there anything like that? Otherwise, I’ll have a look at it.

**Comment by grochocki** [comment]
Have you explored some of the [script integration](https://github.com/Xavalon/XamlStyler/wiki/Script-Integration) options? A team that I worked on utilized a [Git Hook](https://github.com/Xavalon/XamlStyler/wiki/Git-Hook) to enforce format on commit. It could easily be adapted to run as a build task in a CI build.

**Comment by HofmeisterAn** [comment]
Yes, I have seen the script integration options and I'm already using them with Cake. However, I don't want to use Git hooks. I'm not sure if VSTS support those kind of server side Git hooks and I don't want to rely on client side hooks.

I would like to make sure that the code is formatted correct before it gets merged into the main branch without any bypass (I know these feature from other projects like [diffplug/spotless](https://github.com/diffplug/spotless)). A simple `check` option for XamlStyler.Console would be enough. For example, we can easily compare `originalContent` with `formattedOutput` and break the build or use a specific exit code.

**Comment by grochocki** [comment]
This seems like a reasonable feature request for the console app.
> For example, we can easily compare originalContent with formattedOutput and break the build or use a specific exit code.
