### ISSUE TITLE
Create a Gitter room for the project.

### ISSUE THREAD

**Issue by JohanLarsson** [Xavalon/XamlStyler#18]
Sample: https://gitter.im/ButchersBoy/MaterialDesignInXamlToolkit

Nice way to get to know each other and all kinds of discussions.

I think an owner must create the room.

**Comment by PolarbearDK** [comment]
We are using Slack: https://xavalon.slack.com/

**Comment by JohanLarsson** [comment]
How does invites work? Gitter is nice since there is no invite required. Also nice integration with github.

**Comment by PolarbearDK** [comment]
I think it is fine that Slack is invite only, as we can discuss things that we would'nt  do in an open forum.
Other than that, I have no opinion as to which site to use.

**Comment by grochocki** [comment]
Perhaps we can also have a public Gitter to have an open forum for discussion?

**Comment by JohanLarsson** [comment]
Open discussion for an open source project makes sense to me. Also I have never seen a project room get spammed.

**Comment by NicoVermeir** [comment]
room created
https://gitter.im/Xavalon/XamlStyler
