### ISSUE TITLE
Does not work in VS2019 16.1.2

### ISSUE THREAD

**Issue by rezamohamed** [Xavalon/XamlStyler#186]
With the most recent upgrade to VS2019 Community 16.1.2 the XAML Styler has stopped working completely.

**Comment by NicoVermeir** [comment]
seems to work fine for me. can you give some more information? are you getting error messages? what project type are you using?

**Comment by JohnnyWestlake** [comment]
I will say that although it does format for me, it's completely ignoring my Settings.XamlStyler file that's further down the folder structure (with search to Root set to true in settings), whereas it did work before the update.

**Comment by rezamohamed** [comment]
@NicoVermeir the xaml styler does nothing. I have tried the hot key, I have set style on save etc. But the extensions itself just does nothing. It used to work fine on a couple of builds prior of VS19, but with this build it has just stopped working. I have uninstalled the extension, and reinstalled as well. No difference.

![image](https://user-images.githubusercontent.com/18199852/59569309-2b02dc00-904d-11e9-9046-bdc8fbcaf7b5.png)

**Comment by grochocki** [comment]
@rezamohamed I addressed a couple verified compatibility issues in #206. I am not 100% sure this will address this issue, but 16.1.2 would definitely be a version I would expect to experience some of the issues that PR addresses. Any chance you can give the build out of master a try on your install and see if that resolves your problem?

**Comment by grochocki** [comment]
Should be addressed in [3.1912.9](https://github.com/Xavalon/XamlStyler/releases/tag/Release-3.1912.9), available now!
