### ISSUE TITLE
Latest source is not public

### ISSUE THREAD

**Issue by tmatz** [Xavalon/XamlStyler#188]
The currently published package is version 3.2.5, but only sources up to version 3.2.4 have been public.

**Comment by NicoVermeir** [comment]
the sources should be the latest, the manifest probably isn't, but apart from the version number nothing changed there. I'll see about getting it checked in later

**Comment by tmatz** [comment]
@NicoVermeir Thank you for your reply.
I understand that the source is up to date.
I am very glad if you can maintain the release tag.

**Comment by grochocki** [comment]
This will be better with #222. See [3.1912.9](https://github.com/Xavalon/XamlStyler/releases/tag/Release-3.1912.9) for latest release.
