### ISSUE TITLE
Format XAML error "&lt;" "&gt;" (version 2.1)

### ISSUE THREAD

**Issue by Hoocker** [Xavalon/XamlStyler#19]
**Formating XAML code causes errors**

**Original XAML code:**

`<MultiDataTrigger.Conditions>
          <Condition Binding="{Binding Failed, Converter={StaticResource NumericEqualityToBoolConverter}, ConverterParameter='&lt;'}" Value="True" />
          <Condition Binding="{Binding Items.Count, Converter={StaticResource NumericEqualityToBoolConverter}, ConverterParameter='&gt;'}" Value="True" />
        </MultiDataTrigger.Conditions>
`

**Formated XAML code (ConverterParameter):**

`                <MultiDataTrigger.Conditions>
                    <Condition Binding="{Binding Failed, Converter={StaticResource NumericEqualityToBoolConverter}, ConverterParameter='<'}" Value="True" />
                    <Condition Binding="{Binding Items.Count, Converter={StaticResource NumericEqualityToBoolConverter}, ConverterParameter='>'}" Value="True" />
                </MultiDataTrigger.Conditions>
`

**Comment by PolarbearDK** [comment]
I will look at it tonight.

**Comment by grochocki** [comment]
The fix for this issue has been merged into master.
