### ISSUE TITLE
Where is the VS for Mac Installation??

### ISSUE THREAD

**Issue by aormsby** [Xavalon/XamlStyler#193]
Maybe I'm missing something, but I can't seem to find any way to install your lovely extension into Visual Studio for Mac (2019). I saw a link in the [Xamarin Developer Youtube video](https://www.youtube.com/watch?v=0eLc9KK3tzM&feature=em-uploademail) that was posted a little bit ago, but it seems to go straight to the Github project where there are only .vsix downloads for PC. Is this right?

A screenshot from the video description
![Screen Shot 2019-06-29 at 12 50 27](https://user-images.githubusercontent.com/1312251/60380252-8cbf3f00-9a6c-11e9-9504-618bb55a8eed.png)

The actual link - [click me!](https://github.com/Xavalon/XamlStyler) - just goes to the project. I guess I was hoping to find a Mac release version based on the link description above.

What's the status on this?

**Comment by grochocki** [comment]
Check out the [downloads](https://github.com/Xavalon/XamlStyler/blob/master/README.md#downloads) section in the README for download links for each version of Visual Studio.

**Comment by aormsby** [comment]
Wow, I thought I looked there. I guess I just blew right past it somehow. Thank you for pointing out the obvious link. Cheers. :)

**Comment by Saratsin** [comment]
You can also download it inside the Visual Studio for Mac. Open Visual Studio => Extensions. There will be tab for downloading other extensions (not only XamlStyler)
