### ISSUE TITLE
Tab for identation

### ISSUE THREAD

**Issue by DaRochaRomain** [Xavalon/XamlStyler#195]
When using xstyler.exe, it seems that the defaut identation is 2 spaces : 
![image](https://user-images.githubusercontent.com/6987690/60809774-bf171d80-a18b-11e9-9c50-465c57396e0d.png)

I tried to set IndentSize property inside the DefaultSettings.json but nothing change (maybe I did something wrong). Anyway, how can I set the styler to use tab as identation to achieve something like this : 
![image](https://user-images.githubusercontent.com/6987690/60809881-04d3e600-a18c-11e9-9f7f-a922e72da1fe.png)

**Proposed Solution** (see discussion below for details)
> I think it is reasonable to expose the ability to override ```IndentWithTabs``` in the same way, but we can't simply remove ```[JsonIgnore]``` without breaking use without external configurations. I would suggest following the same pattern we did for ```IndentSize``` by removing ```[JsonIgnore]``` from ```IndentWithTabs``` and adding:
> - **UseVisualStudioIndentWithTabs**: Allows us to track when to rely on default Visual Studio tabs/space settings (or not). This is set based on whether you specify [IndentWithTabs](https://github.com/Xavalon/XamlStyler/wiki/External-Configurations#indent-size) in your external configuration.

**Comment by grochocki** [comment]
Hmm, that is the correct way to set indentation (xstyler.exe cannot detect Visual Studio indentation options). Can you share your configuration?

**Comment by DaRochaRomain** [comment]
I've just edited the one in the Options folder.

```
"AttributesTolerance": 2,
    "KeepFirstAttributeOnSameLine": false,
    "MaxAttributeCharactersPerLine": 0,
    "MaxAttributesPerLine": 1,
    "NewlineExemptionElements": "RadialGradientBrush, GradientStop, LinearGradientBrush, ScaleTransfom, SkewTransform, RotateTransform, TranslateTransform, Trigger, Condition, Setter",
    "SeparateByGroups": false,
    "AttributeIndentation": 0,
    "AttributeIndentationStyle": 1,
    "RemoveDesignTimeReferences":  false,
    "EnableAttributeReordering": true,
    "AttributeOrderingRuleGroups": [
        "x:Class",
        "xmlns, xmlns:x",
        "xmlns:*",
        "x:Key, Key, x:Name, Name, x:Uid, Uid, Title",
        "Grid.Row, Grid.RowSpan, Grid.Column, Grid.ColumnSpan, Canvas.Left, Canvas.Top, Canvas.Right, Canvas.Bottom",
        "Width, Height, MinWidth, MinHeight, MaxWidth, MaxHeight",
        "Margin, Padding, HorizontalAlignment, VerticalAlignment, HorizontalContentAlignment, VerticalContentAlignment, Panel.ZIndex",
        "*:*, *",
        "PageSource, PageIndex, Offset, Color, TargetName, Property, Value, StartPoint, EndPoint",
        "mc:Ignorable, d:IsDataSource, d:LayoutOverrides, d:IsStaticText",
        "Storyboard.*, From, To, Duration"
    ],
    "FirstLineAttributes": "",
    "OrderAttributesByName": true,
    "PutEndingBracketOnNewLine": false,
    "RemoveEndingTagOfEmptyElement": true,
    "SpaceBeforeClosingSlash": true,
    "RootElementLineBreakRule": 0,
    "ReorderVSM": 2,
    "ReorderGridChildren": false,
    "ReorderCanvasChildren": false,
    "ReorderSetters": 0,
    "FormatMarkupExtension": true,
    "NoNewLineMarkupExtensions": "x:Bind, Binding",
    "ThicknessSeparator": 2,
    "ThicknessAttributes": "Margin, Padding, BorderThickness, ThumbnailClipMargin",
    "FormatOnSave": true,
    "CommentPadding": 2,
	"IndentSize": 2
```

**Comment by jltjohanlindqvist** [comment]
I'm having a similar issue using the xstyle.exe from the console, where XamlStyler is indenting using spaces instead of tabs even though I've configured it to use tabs.

Here's my configuration file:
```json
{
    "AttributesTolerance": 3,
    "KeepFirstAttributeOnSameLine": false,
    "MaxAttributeCharactersPerLine": 0,
    "MaxAttributesPerLine": 1,
    "NewlineExemptionElements": "RadialGradientBrush, GradientStop, LinearGradientBrush, ScaleTransfom, SkewTransform, RotateTransform, TranslateTransform, Trigger, Condition, Setter",
    "SeparateByGroups": false,
    "AttributeIndentation": 0,
    "AttributeIndentationStyle": 1,
    "RemoveDesignTimeReferences":  false,
    "EnableAttributeReordering": true,
    "AttributeOrderingRuleGroups": [
        "x:Class",
        "x:Key, x:Name, x:Uid"
        "xmlns, xmlns:x",
        "xmlns:*",
        "Key, Name, Uid, Title",
        "ui:Grid.Columns, ui:Grid.Row",
        "mc:Ignorable, d:DataContext, d:IsDataSource, d:LayoutOverrides, d:IsStaticText",
        "Storyboard.*, From, To, Duration",
        "When, Then"
    ],
    "FirstLineAttributes": "",
    "OrderAttributesByName": true,
    "PutEndingBracketOnNewLine": false,
    "RemoveEndingTagOfEmptyElement": true,
    "SpaceBeforeClosingSlash": false,
    "RootElementLineBreakRule": 0,
    "ReorderVSM": 2,
    "ReorderGridChildren": false,
    "ReorderCanvasChildren": false,
    "ReorderSetters": 0,
    "FormatMarkupExtension": true,
    "NoNewLineMarkupExtensions": "x:Bind, Binding",
    "ThicknessSeparator": 1,
    "ThicknessAttributes": "Margin, Padding, BorderThickness, ThumbnailClipMargin",
    "FormatOnSave": true,
    "CommentPadding": 1,
    "IndentWithTabs": true,
    "IndentSize": 1,
}

```

It says configuration found when I run it with log level set to debug, but only lists the following settings: 
```
Configuration Found: <redacted path>\Settings.XamlStyler
["x:Class","x:Key, x:Name, x:Uid","xmlns, xmlns:x","xmlns:*","Key, Name, Uid, Title","ui:Grid.Columns, ui:Grid.Row","mc:Ignorable, d:DataContext, d:IsDataSource, d:LayoutOverrides, d:IsStaticText","Storyboard.*, From, To, Duration","When, Then"]
```

**Comment by jltjohanlindqvist** [comment]
https://github.com/Xavalon/XamlStyler/blob/72ba28a007dd2612e1d3c8dbe3f1a4a8969734ce/XamlStyler.Core/Options/StylerOptions.cs#L59

If I remove the `[JsonIgnore]` attribute and build it myself and use that executable instead then the settings-file I have works.

What's the reason behind the `[JsonIgnore]` on `IndentWithTabs`? Since that seems to be the culprit.

**Comment by DaRochaRomain** [comment]
Good find. I'll try to make a build for myself.

**Comment by grochocki** [comment]
> What's the reason behind the [JsonIgnore] on IndentWithTabs? Since that seems to be the culprit.

There are some parts of IStylerOptions that are not intended to be set via external configurations.

- **UseVisualStudioIndentSize**: Allows us to track when to rely on default Visual Studio indent size (or not). This is set based on whether you specify [IndentSize](https://github.com/Xavalon/XamlStyler/wiki/External-Configurations#indent-size) in your external configuration.
- **SearchToDriveRoot**: Facilitates loading external configurations
- **ResetToDefault**: Resets defaults when _not_ using external configurations
- **ConfigPath**: Facilitates loading external configurations

_Before_ we added support for external configurations, ```IndentSize``` behaved as ```IndentWithTabs``` does today. [This](https://github.com/Xavalon/XamlStyler/commit/a08f173ac603d4d0c57df411dd00a16cd4bd5f6a#diff-f114db559155e5aed6f311c7f200ffd6) commit enabled the ability to override the VS setting.

I think it is reasonable to expose the ability to override ```IndentWithTabs``` in the same way, but we can't simply remove ```[JsonIgnore]``` without breaking use without external configurations. I would suggest following the same pattern we did for ```IndentSize``` by removing ```[JsonIgnore]``` from ```IndentWithTabs``` and adding:

- **UseVisualStudioIndentWithTabs**: Allows us to track when to rely on default Visual Studio tabs/space settings (or not). This is set based on whether you specify [IndentWithTabs](https://github.com/Xavalon/XamlStyler/wiki/External-Configurations#indent-size) in your external configuration.

**Comment by Tyrrrz** [comment]
It seems quite unintuitive that the default indent size in XamlStyler.Console is 2 spaces while the default in Visual Studio plugin is 4 (I assume that's because it's taken from VS settings which are also default).

Here's me formatting with extension, as you can see all settings are default.
![2020-01-06 22_12_06-Options](https://user-images.githubusercontent.com/1935960/71845964-20379380-30d2-11ea-913d-d2c7c6c35ac9.png)
![2020-01-06 22_12_23-LightBulb - Microsoft Visual Studio](https://user-images.githubusercontent.com/1935960/71845966-20d02a00-30d2-11ea-8e32-d76b32ee5020.png)

And here's me formatting via XamlStyler.Console. Note that the indentation is wrong.
![2020-01-06 22_12_39-LightBulb - Microsoft Visual Studio](https://user-images.githubusercontent.com/1935960/71845984-2ded1900-30d2-11ea-84ce-02daebe739d2.png)

**Comment by grochocki** [comment]
> It seems quite unintuitive that the default indent size in XamlStyler.Console is 2 spaces while the default in Visual Studio plugin is 4

I agree. I would be in favor of updating the default value for [IndentSize](https://github.com/Xavalon/XamlStyler/wiki/External-Configurations#indent-size) from 2 to 4 for CLI. For the plugin, we should continue to use the Visual Studio options as the default (i.e., no change). I'll open up a new issue to track this.
