### ISSUE TITLE
XAML Styler Configuration options do not persist on MacOS

### ISSUE THREAD

**Issue by developering** [Xavalon/XamlStyler#196]
I am working with VS for Mac v8.1.3 (build 19), and am unable to save any Configuration changes within Preferences.

Anytime I go into preferences and check `Search to drives root` or add an `External configuration file` from the menu below, the value is cleared when I revisit preferences:
![Screen Shot 2019-07-09 at 9 46 59 AM](https://user-images.githubusercontent.com/4691573/60898372-a3188800-a22e-11e9-8bd0-855c3742d507.png)

The root issue is that I am trying to figure out some way to share XAML Styler configuration between Windows & MacOS. Currently, I don't have a way of doing this beyond manually updating each of the required settings in each environment (the defaults seem to be different on each platform).

**Comment by Saratsin** [comment]
This is definitely a bug. These seeing options are not working currently on Mac. I can suggest you to drop your Settings.XamlStyler file to the project root folder (or either solution root folder). It will handle then these for files styling (available since v1.1.3 for Mac)

**Comment by developering** [comment]
Thanks @Saratsin. I mentioned in #194 that I was having issues with v1.1.3 for Mac. I just added details to that PR, but let me know if I can provide more info.

**Comment by grochocki** [comment]
Fixed via #246
