### ISSUE TITLE
CLI options `check` `dry-run`

### ISSUE THREAD

**Issue by virzak** [Xavalon/XamlStyler#198]
Looking for an option to test that all files are formatted, but the pre-commit hook is being utilized by [husky](https://github.com/typicode/husky).

Would like to have a check / dry run option the same way dotnet format is [doing](https://github.com/dotnet/format#how-to-use) it.

```sh
dotnet format --check --dry-run
```

Is an option like that available?

**Comment by grochocki** [comment]
Do you see this as a dupe of #176?

**Comment by virzak** [comment]
I do. Glad to see this has been requested already.

**Comment by grochocki** [comment]
Cool, going to close this as a duplicate then.
