### ISSUE TITLE
Attribute Ordering Rule Groups aren't being applied

### ISSUE THREAD

**Issue by PensionProSoftware** [Xavalon/XamlStyler#2]
I may be missing something here, but it doesn't appear that the groups for attribute reordering are being applied. One of the defaults is to group things like Grid.Row and Grid.Column, but this isn't happening when I run XAML Styler on a xaml document. I've attached a screenshot of how my options are currently set up in case I've done something stupid and disabled the attribute groups somehow.

![xaml styler options](https://cloud.githubusercontent.com/assets/4097059/15083704/b65bbcbc-139c-11e6-9c1b-e3362d66f954.PNG)

**Comment by NicoVermeir** [comment]
would this by any chance be the same issue that was fixed in XAML Magic here: https://github.com/grochocki/XamlMagic/issues/7 ?

**Comment by PensionProSoftware** [comment]
I don't think so. My specific problem is that it's breaking up all my Grid attributes, and those are listed before "*:*,*", that is unless the wildcard in group 2 (xmlns:*) is causing is. I should note that I'm on version 2.1.

**Comment by NicoVermeir** [comment]
could you provide us with a xaml snippet and what result you would expect?

**Comment by PensionProSoftware** [comment]
I hope some screenshots are ok.

**Before**
![grid before](https://cloud.githubusercontent.com/assets/4097059/15127352/45004df2-1604-11e6-928d-a5035b57c53e.PNG)
**After**
![grid after](https://cloud.githubusercontent.com/assets/4097059/15127350/44fdd1d0-1604-11e6-84d3-ada9a4a55f27.PNG)
**After Expected**
![grid after expected](https://cloud.githubusercontent.com/assets/4097059/15127351/44fecb30-1604-11e6-8bcc-81d1878ac94f.PNG)

I may have missed a few things, but I hope that gives you the idea of what I expected.

**Comment by NicoVermeir** [comment]
oh I see now. The issue here is that your settings are conflicting. You've set Put rule groups on seperate lines to true, but also the max attributes per line to 1. When you set that to 2, it works as you would expect.

We realise some of the settings are confusing and we're going to clean them up and/or change the descriptions to make it more clear.

if you can confirm that changed Max attributes per line to 2 fixes your issue, we can close this as "by design"

**Comment by PensionProSoftware** [comment]
That did it. Thanks so much for the help and sorry for wasting your time.

Just so you know, this is a great tool and it sucks it took me so long to find it. We use ReSharper and XAML formatting is sorely lacking in there, so this tool fills that gap and fills it well.
