### ISSUE TITLE
The extension makes VS2019 v16.2 to lock up when using Find/Replace in XAML pages

### ISSUE THREAD

**Issue by albrtogomez** [Xavalon/XamlStyler#200]
This is happening after updating to 16.2.0. When searching text in XAML files, the search window flickers at high speed completely locking visual studio. After that you can only kill the process and start VS again. Disabling the extension is my only solution at the moment.

**Comment by grochocki** [comment]
I am _not_ able to reproduce this issue on 16.2.5. @albrtogomez, have you tried updating to the latest version of VS2019?

**Comment by grochocki** [comment]
Should be addressed in [3.1912.9](https://github.com/Xavalon/XamlStyler/releases/tag/Release-3.1912.9), available now!
