### ISSUE TITLE
After update to VS 2019 V 16.2.3 only default settings work.

### ISSUE THREAD

**Issue by robinmtb** [Xavalon/XamlStyler#202]
I'm running VS 2019 v16.2.3 and Xaml Styler v3.2.5 on Win10 v10.0.16299.

Xaml Styler was working fine until I update to v16.2.3. Now no matter what I change in the settings, in VS->Tools->Options->Xaml Styler, it only uses the default settings.
I get the same behavior if I try using an external settings file.

To clarify, the setting values persist in the settings view, but they do not have any effect on the outcome.

**Comment by robinmtb** [comment]
Updated to 16.2.4 and the issue still persist. Please let me know if there is any other data I can provide that might be helpful!

**Comment by grochocki** [comment]
Thanks, I am having a hard time reproducing the issue.

> I get the same behavior if I try using an external settings file.

Do you mean that settings get reset if you specify a non-default external config?

**Comment by robinmtb** [comment]
Hi, sorry if I was unclear.

We are using a non-default external config which was working fine until I updated VS.

After the update XamlStyler is editing files as if the default values were set. I have tried removing the link to the external file and just changing the settings directly in the options in VS. XamlStyler seems to disregard those changes as well and keeps on editing as if the default settings are set.

The issue is not contained to only my computer, more and more people in the company are moving to the new version and encountering this issue.

Attaching our external settings file.

[Settings.XamlStyler.txt](https://github.com/Xavalon/XamlStyler/files/3599419/Settings.XamlStyler.txt)

**Comment by robinmtb** [comment]
Aha! Sorry to have used up your time! Seems like we have had a faulty external settings file for years. 

If you look in the attached file above you can see that we lack a comma at the end of line 14 inside the "AttributeOrderingRuleGroups": [].

For some reason this has been working earlier and I guess some change in the latest version made it so that it didn't work any more.

Thanks for the help any how and thank you for an amazing piece of software! Certainly helps us greatly every day! You guys rock! :D

**Comment by grochocki** [comment]
Ah, great to hear you were able to solve the issue! There are a couple other similar reports, and I am curious if this is the cause. If so, we may want to explore popping a more friendly error message to help folks fix syntax in configuration files.
