### ISSUE TITLE
Unwanted whitespaces with InlineUIContainer element

### ISSUE THREAD

**Issue by lightwalker01** [Xavalon/XamlStyler#203]
Wrapping `InlineUIContainer` inside `TextBlock` generates unwanted whitespaces similarly to `Run`  elements ([see wiki](https://github.com/Xavalon/XamlStyler/wiki/Getting-Started#whitespace)).

Example:
```xaml
<TextBlock VerticalAlignment="Center" HorizontalAlignment="Center">
    <Run Text="Before" />
     <InlineUIContainer>
         <TextBlock Text="After" />
      </InlineUIContainer>
</TextBlock>
```
Turns out like:
`Before After`

And:
```xaml
<TextBlock VerticalAlignment="Center" HorizontalAlignment="Center">
    <Run Text="Before" /><InlineUIContainer>
         <TextBlock Text="After" />
      </InlineUIContainer>
</TextBlock>
```

Turns out like:
`BeforeAfter`

---
XamlStyler 3.2.5
VS 2017

**Comment by grochocki** [comment]
Similar to #130. Note the workaround there might work here too:

> You can work around this by adding xml:space="preserve" to the tag

**Comment by lightwalker01** [comment]
> Similar to #130. Note the workaround there might work here too:
> 
> > You can work around this by adding xml:space="preserve" to the tag

Ok, thank you.
