### ISSUE TITLE
Xamarin.Forms Support

### ISSUE THREAD

**Issue by lsaudon** [Xavalon/XamlStyler#209]
I would like to add Xamarin attributes in DefaultSettings.

- WidthRequest, HeightRequest
- HorizontalOptions, VerticalOptions
- and others

The top would be to build a list of recurring attributes.

**Comment by roubachof** [comment]
Just use a config file: https://www.sharpnado.com/xamarin-forms-xamlstyler-config/

**Comment by lsaudon** [comment]
I think it would be nice to add it as an option in XamlStyler or add your file as an example in the documentation.
