### ISSUE TITLE
Possible Plugin for Rider JetBrains?

### ISSUE THREAD

**Issue by moreirawebmaster** [Xavalon/XamlStyler#213]
It's possible create plugin for  Rider?

Thanks.

**Comment by NicoVermeir** [comment]
we're currently looking into this with the good people from JetBrains, we'll keep you posted

**Comment by maartenba** [comment]
As a quick-fix, you could create XamlStyler as an External Tool in Rider.

1) Download the latest XamlStyler console [from the releases](https://github.com/Xavalon/XamlStyler/releases)
2) Extract and note the path to `xstyler.exe`
3) In Rider, find the settings and add an external tool under **Tools \| External Tools**

Program: `<path to xstyler.exe>`
Arguments: `-f $FileName$` (note if you have a config file you can add the arguments to use that config file here as well)
Working directory: `$FileDir$`
Disable `Open console tool for output` (if you don't want to see the output of the console application when invoked)

![image](https://user-images.githubusercontent.com/485230/66979859-bf17a980-f0fa-11e9-93e0-394e47b00874.png)

Once configured, you can invoke XamlStyler from **Find Action** (Ctrl+Shift+A or double-shift):

![image](https://user-images.githubusercontent.com/485230/66979928-fb4b0a00-f0fa-11e9-8ff8-9a30c034adb8.png)

Bonus tip: you can assign a keyboard shortcut if you ant (under the settings' keymaps section)

**Comment by matkoch** [comment]
@NicoVermeir if you want have a chat about Rider integration, please reach me on [twitter](https://twitter.com/matkoch87). I can get you invited into our internal chat, and also give you some hints for the start. But I guess voice/video call would be good to start with.

**Comment by Tyrrrz** [comment]
@moreirawebmaster check out [this post](https://tyrrrz.me/blog/formatting-xaml-on-build).

**Comment by amirvenus** [comment]
I am currently using this article and it does work:

https://tyrrrz.me/blog/formatting-xaml-on-build

However, it would be better to auto style my XAML on each file save rather than having to build the whole thing again.

**Comment by kyurkchyan** [comment]
I would really love to see this implemented as cross platform Rider plugin. As of now half of the team uses Visual Studio, the other Rider. And every time someone touches Xaml files we get tone of unwanted changes as the ones who have it on Visual Studio will re-format the file according to the styling rules :)

**Comment by maartenba** [comment]
## Good news, everyone!**

I did a spike on making XAML Styler work in Rider. 

It can be downloaded [from the releases here](https://github.com/maartenba/XamlStyler.dotUltimate/releases) (pick the ZIP file for Rider), and installed manually [using these instructions](https://www.jetbrains.com/help/rider/Managing_Plugins.html#install_plugin_from_disk). It's intentionally not on the plugins marketplace yet, for reasons outlined further in this comment.

The plugin currently has:
* An options page under **Tools \| XAML Styler**
* Supports (and enabled by default) "Format on Save"
* Comes with an `Alt+Enter` intention to format the current file, or all files in project/solution
* Loads `XamlStyler.Settings`, went with a similar resolving mechanism as the VS extension, but may need some tweaks as I have no idea what the proper convention is 😃 

![xamlstyler-in-rider](https://user-images.githubusercontent.com/485230/80182613-96232480-8607-11ea-8983-74234a011cc7.gif)

_Disclaimer: there may be and probably will be issues, so make sure to use version control so you can revert any changes the plugin makes to your project. You could turn off "Format on Save" and invoke XAML Styler manually where needed._

## For XAML Styler maintainers

I would like to contribute the plugin to the XAML Styler project, but am not sure about the next steps.

### Shall I create a PR?

If you're interested in having the plugin in your repo, I'll happily make a pull request. If not, that's fine too.

The plugin is not on the plugins marketplace right now, as the ownership will depend on who publishes it. Given the heavy work on reformatting is XAML Styler, and the plugin is only hooking things up, I feel you should be the owners from the start.

### Repository structure

The repository at [maartenba/XamlStyler.dotUltimate](https://github.com/maartenba/XamlStyler.dotUltimate) has the Rider plugin, as well as a R# extension (which has roughly the same features, apart from "Format on Save".

I checked #254, which looks cool, and I could dump all files in a folder according to that structure.

**All and any feedback welcome!** We'll see from here.

### Side effects

You now have an SVG version of the logo as well. 🥳  #277

**Comment by NicoVermeir** [comment]
Thanks a lot for your hard work @maartenba !
I'll discuss the next steps with @grochocki and we'll keep you in the loop!

thanks again!

**Comment by grochocki** [comment]
@maartenba - thanks a bunch for all of your hard work here! After a bit of discussion, we would like to move forward with adding support for Rider 😁

> Shall I create a PR?

We would love to merge this into the XAML Styler project, but it would be great to coordinate this with the project refactoring detailed in #254. I am going to work to get the core parts of #254 completed early this weekend. After that is in, it would be great if you could help align your changes to that new project structure before opening up a PR.

> The plugin is not on the plugins marketplace right now, as the ownership will depend on who publishes it. Given the heavy work on reformatting is XAML Styler, and the plugin is only hooking things up, I feel you should be the owners from the start.

Thanks! We certainly appreciate your contribution here, but we also agree that publishing under 'Xavalon', like we do in the Visual Studio Gallery, is probably the best path forward here. This approach will help users already familiar with the extension find it in the JetBrains plugins marketplace, and it will also make it easier for us to announce/publish updates to the extension across all supported IDEs.

We are really excited to get this in -- thanks again!

**Comment by maartenba** [comment]
Cool, I'll wait with a PR until that happens. Regarding marketplace, what we could also do is have me publish this first version and add you as an owner (ownership can be shared). Any option works for me :)

**Comment by grochocki** [comment]
I create a publisher account we can post it under, though I would say we should hold off until we merge in the PR before publishing so we can have a clear place for users to go to file issues and so we can quickly follow up with any bug fixes for the initial release.

We want to move on this quickly, so just a _bit_ longer :)

**Comment by grochocki** [comment]
@maartenba The [projectStructure](https://github.com/Xavalon/XamlStyler/tree/projectStructure) branch should be good to work against. Meanwhile, @NicoVermeir is going to update XamlStyler.Mac.sln to align to new project hierarchy.

I think it would be good to prep your change against that branch, but I am leaning towards merging that branch in first, with a fast follow of your PR against master. It feels cleaner. Thoughts? To expedite review, perhaps you can open a PR against that working branch so we can parallelize the rest?

**Comment by maartenba** [comment]
Sounds good, I'll get on it.

**Comment by grochocki** [comment]
With #281 in, we will incorporate the Rider extension into our release pipeline and get an official release out soon :)

**Comment by roubachof** [comment]
any news from the vnext integrating this ?

**Comment by grochocki** [comment]
We are excited to add support for [JetBrains Rider](https://plugins.jetbrains.com/plugin/14932-xaml-styler) with [v3.2008.4](https://github.com/Xavalon/XamlStyler/releases/tag/Release-3.2008.4)!

**Comment by maartenba** [comment]
Woohoo! Thanks everyone involved! You are awesome!
