### ISSUE TITLE
Unify output of XML Declaration Node and Processing Instruction

### ISSUE THREAD

**Issue by renao** [Xavalon/XamlStyler#225]
If the pull request https://github.com/Xavalon/XamlStyler/pull/215 is accepted, the output of the XML Declaration Node and possible Processing Instructions look inconsistent.

By definition those nodes are not the same, but I would like to have nodes ending with `?>` being handled consistent 😉 

I will add a PR right after this issue is created to update the behaviour - knowing full well, that this change will affect many files for all the users out there.

**Comment by grochocki** [comment]
I appreciate consistency too, but while they look similar XML declarations are explicitly _not_ processing instruction. As such, I don't think we want to update those to remove the spaces and unnecessarily cause changes in XML files as a result.

> An XML processing instruction is enclosed within <? and ?>, and contains a target and optionally some content, which is the node value, that cannot contain the sequence ?>.
>
> ```<?PITarget PIContent?>```
>
> The XML Declaration at the beginning of an XML document (shown below) is not a processing instruction, however its similar syntax has often resulted in it being referred to as a processing instruction.
>
> ```<?xml version="1.0" encoding="UTF-8" ?>```

<sub>[Source](https://en.wikipedia.org/wiki/Processing_Instruction)</sub>

**Comment by renao** [comment]
Sure, technically it is different, but as you also pointed out, it is "visually equal".

So I am thinking from the "programmers experience" point of view, that this could be annoying if you are experiencing a different behaviour here and there.

Otherwise wouldn't it be an idea to add the whitespace again to the Processing Instruction again?

Just another suggestion ;-)

**Comment by grochocki** [comment]
After thinking on this a bit more, it it is a tough call, but we think that we generally need to stick to the spec/prescribed formatting wherever possible. In this case, that means the XML declaration having a space and processing instructions _not_ having a space.
