### ISSUE TITLE
Xamarin From XAML

### ISSUE THREAD

**Issue by smaucy** [Xavalon/XamlStyler#24]
can't format Xamarin Forms XAML File. XAML Styler is not available. #

**Comment by NicoVermeir** [comment]
the right-click option is not there, but it should still work when saving the file

**Comment by smaucy** [comment]
This is correct :-). It's a workaround. But usually i use a shortcut. Thanks for fast reply.

**Comment by h82258652** [comment]
And any plan for Xamarin Android axml file?

**Comment by NicoVermeir** [comment]
@h82258652 not at the moment. Android axml is a different beast from XAML. but who knows, maybe someday :)

**Comment by tlhintoq** [comment]
@smaucy - The keyboard shortcut still works even thought the context menu isn't there.  Cntrl+K,Cntrl+2
