### ISSUE TITLE
Latest version stopped working on VS2017

### ISSUE THREAD

**Issue by gdang** [Xavalon/XamlStyler#242]
Just updated the plugin to 3.1912.9 and it stopped working on VS2017 (15.9.18).

Ctrl+S doesn't automatically format anymore and going to the plugin settings in **Tools -> Options -> XAML Styler** displays the following message:

_An error occurred loading this property page_

**Comment by grochocki** [comment]
We were a bit too ambitious in updating Newtonsoft.Json in #217. We had been on 8.0.3, but this version is not compatible with .NET Standard/Core. However, 12.0.3 is not compatible with Visual Studio 15.0 VSIX packages. Visual Studio [15.3](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes-v15.3) added better support for .NET Core development, including bumping up support of Newtonsoft.Json to [9.0.1](https://github.com/JamesNK/Newtonsoft.Json/releases/tag/9.0.1), which added support for .NET Core.

More information here: [Using Newtonsoft.Json in a Visual Studio extension](https://devblogs.microsoft.com/visualstudio/using-newtonsoft-json-in-a-visual-studio-extension/)

**Comment by grochocki** [comment]
Adding to index: natemcmaster/dotnet-tools#178
