### ISSUE TITLE
Error formating Style

### ISSUE THREAD

**Issue by Marcel27** [Xavalon/XamlStyler#25]
I have a style in a dictionary with this Setter : 
Setter Property="telerik:StyleManager.Theme" Value="Windows8"

It makes XamlStyler crash

![xamlstylererror](https://cloud.githubusercontent.com/assets/19780028/15825896/cb18731c-2c05-11e6-8d16-280dec65960b.png)

**Comment by grochocki** [comment]
Marcel, have you updated to version 2.1? I am not able to repro the issue. Would you be willing to share more of the problem code?

**Comment by Marcel27** [comment]
Hi,
yes, I have updated to version 2.1
I tried to isolate the problem and reproduce the issue
        <Grid.Resources>            <Style x:Key="test"                   TargetType="{x:Type ComboBox}">                <Setter Property="telerik:StyleManager.Theme"                Value="Windows8" />            </Style>        </Grid.Resources>
Maybe it's due to my settings ?


Date: Wed, 8 Jun 2016 00:33:46 -0700

**Comment by antoinebj** [comment]
I can confirm that this error also occurs for me with version 2.1.
It appears that this kind of line breaks the XamlStyler parsing:
<Setter Property="someNamespaceAlias:SomeClass.SomeAttachedProperty" Value="..." />

**Comment by SylwesterZarebski** [comment]
Unfortunately confirmed. It beats me with Caliburn Micro style setters.

**Comment by CleanCodeDeveloper** [comment]
I can confirm this issue too.
Code to reproduce:
`            <Style TargetType="ScrollViewer">
                <Setter Property="telerik:StyleManager.Theme" Value="Windows8" />
                <Setter Property="Background" Value="Transparent" />
                <Setter Property="BorderBrush" Value="Transparent" />
            </Style>`

![untitled](https://cloud.githubusercontent.com/assets/16760760/17734001/ff7f67c6-6479-11e6-96ad-45684b1cc9bc.png)

**Comment by NicoVermeir** [comment]
I've just tried to reproduce this, but everything seems to work okay for me. is there a repro project that you can zip up and share? I need something to debug to get to the bottom of this

thanks

**Comment by Marcel27** [comment]
I reproduce the issue by creating a new wpf project and put this code : 

<Window x:Class="WpfApplication10.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:local="clr-namespace:WpfApplication10"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        Title="MainWindow"
        Width="525"
        Height="350"
        mc:Ignorable="d">
    <Grid>
        <Grid.Resources>
            <Style TargetType="{x:Type ComboBox}">
                <Setter Property="namespace:property"
                        Value="somevalue" />
            </Style>
        </Grid.Resources>
    </Grid>
</Window>

If you don't reproduce with this code, the only diffrence would be our settings.
You will find my settings into xamlstylesettings.png
[WpfApplication10.zip](https://github.com/Xavalon/XamlStyler/files/430386/WpfApplication10.zip)

Thanks

**Comment by NicoVermeir** [comment]
changing the settings to reflect yours triggered the issue, fix is done and will be included in the next version

**Comment by CleanCodeDeveloper** [comment]
Thank you for resolving this issue :+1:

**Comment by SylwesterZarebski** [comment]
When can we expect new release?
