### ISSUE TITLE
IDE Extensions projects unification

### ISSUE THREAD

**Issue by Saratsin** [Xavalon/XamlStyler#254]
**Problem: several IDE for current/future support**
For this moment we have 2 supported IDE: `Visual Studio for Windows` & `Visual Studio for Mac`
Probably in future we will support `Rider` as well: #213 . Maybe even some other IDE
But we don't have clear structure for this level of abstraction.
Core project is fine, but WIndows and Mac extensions have a lot of duplications 
or different implementations for features which can be implemented identically.

**Common project for Extension with more specific projects for specific IDE**
Here's how I see the structure for solution (or at least projects segregation, we could have separate sln files for build purposes):

| Project | Description |
| --- | --- |
| **Xavalon.XamlStyler** | Core project. Currently it's project `Xavalon.XamlStyler.Core`, I propose to get rid of `Core` namespace, to simplify accessibility to the core projects (we will have no need to add `using Xavalon.XamlStyler.Core` in each file)
| **Xavalon.XamlStyler.Console** | Console implementation |
| **Xavalon.XamlStyler.Extension** | Core project for all IDE Extensions. Will have some concrete implementations if possible and interfaces/abstractions for some platform specific functions |
| **Xavalon.XamlStyler.Extension.VS** | Core project for Visual Studio extensions. As far as I know from the roadmap of `Visual Studio for Mac` future, they want to make more and more common API for both Studio-s. Not sure if currently this project will appear, will see during the implementation, if it's needed now. |
| **Xavalon.XamlStyler.Extension.VS.Windows** | Visual Studio for Windows extension implementation. Current project: `Xavalon.XamlStyler.Package` |
| **Xavalon.XamlStyler.Extension.VS.Mac** | Visual Studio for Mac extension implementation. Current project: `Xavalon.XamlStyler.Mac` |
| **Xavalon.XamlStyler.Extension.Rider** | Rider extension implementation. Currently not exist, just how it would look like in this idea of projects separation |

**Post Scriptum**
This is currently only the idea. I want to hear opinion of the community about this approach is it looks good or I should change/improve something. After I will try to implement this feature in life. Also it would help us to Unify releases for Windows/Mac extensions for Visual Studio #231

**Comment by NicoVermeir** [comment]
I like it! 
but I do wonder how often we will use the abstractions for new versions. Take Rider for example, their extension model is not .net based, it's all Kotlin.  VsCode is all TypeScript.

so while I like the idea, and I see advantages in existing versions, I doubt we'll get much use of it for new branches

**Comment by Saratsin** [comment]
Good point. I thought that for Rider it's also possible to write extension on C#. Also as I understood they call it as Plugin, rather than Extension.
Then I propose next structure:
| Project | Description |
| --- | --- |
| **Xavalon.XamlStyler** | Core project. Currently it's project `Xavalon.XamlStyler.Core`, I propose to get rid of `Core` namespace, to simplify accessibility to the core projects (we will have no need to add `using Xavalon.XamlStyler.Core` in each file)
| **Xavalon.XamlStyler.Console** | Console implementation |
| **Xavalon.XamlStyler.Extension** | Core project for Visual Studio IDE Extensions. Will have some concrete implementations if possible and interfaces/abstractions for some platform specific functions |
| **Xavalon.XamlStyler.Extension.Windows** | Visual Studio for Windows extension implementation. Current project: `Xavalon.XamlStyler.Package` |
| **Xavalon.XamlStyler.Extension.Mac** | Visual Studio for Mac extension implementation. Current project: `Xavalon.XamlStyler.Mac` |
