### ISSUE TITLE
Configuration file not loaded in VS 16.4.4

### ISSUE THREAD

**Issue by vgromfeld** [Xavalon/XamlStyler#255]
**Describe the bug**
We are using a `Settings.XamlStyler` file to configure our styling rules. It was working fine in VS 2017. Now that we have migrated to VS 2019 (16.4.4), XAML styler is always applying its default rules not the one we have defined.

**To Reproduce**
1. Open a solution
2. Edit a XAML document
3. Save the document

**Expected behavior**
The document is formatted with our rules.

**External Configuration**
[Settings.txt](https://github.com/Xavalon/XamlStyler/files/4185510/Settings.txt)

**Version Info (please complete the following information):**
 - OS: Windows 10 (1903)
 - Visual Studio: VS2019 (16.4.4)
 - XAML Styler: Extension 3.2001.0

**Additional context**
We have the following file structure
- repository folder
  - sln
  - src folder
    - Settings.XamlStyler file
      - subfolder 1
        - files
      - subfolder 2
        - files

**Comment by grochocki** [comment]
Are subfolder1 and subfolder2 different projects in your solution?

Also, can you try a few things to help debug:
* If you replace your current configuration with the [default configuration](https://github.com/Xavalon/XamlStyler/wiki/External-Configurations#default-configuration) (and tweaks something), is it picked up then?
* If you move Settings.XamlStyler into one of the subfolders, is it picked up then?

**Comment by vgromfeld** [comment]
I've found the issue, we had one coma missing in one line of the `AttributeOrderingRuleGroups` array 🤦‍♂️.

We had:
```json
"AttributeOrderingRuleGroups": [
        "x:Class",
       [...]
        "RelativePanel, RelativePanel.*"  // no coma here after the line 
        "Width, Height, MinWidth, MinHeight, MaxWidth, MaxHeight",
        [...]
    ],
```
For some unknown reasons, this is working fine in VS 2017 but not in VS 2019. 
It could be a change in the JSON parser....

**Comment by grochocki** [comment]
This is likely due to changes in which version of Json.NET is included in different versions of VS ([details](https://devblogs.microsoft.com/visualstudio/using-newtonsoft-json-in-a-visual-studio-extension/)). Going to close this issue out.
