### ISSUE TITLE
Add Indication which configuration is used.

### ISSUE THREAD

**Issue by CarnageMarkus** [Xavalon/XamlStyler#256]
Hello, I can't seem to properly setup configuration file inside repo.
I downloaded the example configuration file and changed few attributes to test. I have config file located at the project folder. 
When I close and reopen solution, config file is inside project. But in `Tools->Options->XamlStyler`, configuration is default, without my or any changes.

I am not sure how to know the configuration has been loaded/why it's not loaded.
Could you add to the options some indication ? Something like text saying, "plugin default configuration in use" or when configuration file detected "Custom configuration file in use at _PATH_"

I am really confused how and where to place this "Settings.XamlStyler" file. Maybe it's loaded but settings do not reflect that ?

**Comment by NicoVermeir** [comment]
the settings in a configuration file are not reflected in the options window.
if you place the configuration file according to the description here: https://github.com/Xavalon/XamlStyler/wiki/External-Configurations
it should work.

**Comment by CarnageMarkus** [comment]
I did a few tests and its working. Very confusing though.
