### ISSUE TITLE
Is "Max attribute characters per line INCLUDING INDENTATION CHARACTERS" possible?

### ISSUE THREAD

**Issue by GreatFireWall** [Xavalon/XamlStyler#257]
![image](https://user-images.githubusercontent.com/4510984/75105785-e48d6480-5652-11ea-84dc-471daa7479f2.png)

**Comment by grochocki** [comment]
This is not currently possible, but #12 describes adding support for column limit, which I think is what you are interested in here. If you agree, I'd like to close this issue as a duplicate.

**Comment by GreatFireWall** [comment]
OK, thanks.
