### ISSUE TITLE
'xaml-comp' directive auto-corrected to 'Mapping'

### ISSUE THREAD

**Issue by roubachof** [Xavalon/XamlStyler#266]
**Describe the bug**
On Xamarin.Forms xaml, a very useful directive `xaml-comp` is transformed to `Mapping` word when auto-format is applied.

**To Reproduce**
1. Open [Colors.xaml.txt](https://github.com/Xavalon/XamlStyler/files/4408368/Colors.xaml.txt) in VS 2019
2. Format with XamlStyler

**Expected behavior**
It shouldn't correct this directive

**Screenshots**
Before auto format:

![image](https://user-images.githubusercontent.com/596903/78015334-8fc3c480-7349-11ea-8677-0e4f9c26b56c.png)

After auto format:

![image](https://user-images.githubusercontent.com/596903/78015398-a66a1b80-7349-11ea-9caa-b549303c2396.png)

**External Configuration**
[Settings.XamlStyler.txt](https://github.com/Xavalon/XamlStyler/files/4408351/Settings.XamlStyler.txt)

**Version Info (please complete the following information):**
 - Windows 10
 - Visual Studio: 2019 16.5
 - XAML Styler: VS Extension

**Comment by grochocki** [comment]
Thanks for the detailed bug report! This looks like a dupe of #181, which was fixed and shipped as part of the 3.2001.* update (I am not able to reproduce the problem).

Can you double-check to see if you have the latest version of the extension installed?

**Comment by roubachof** [comment]
Gosh I don't know how I missed #181, I searched for xaml-comp and Mapping in issues though... I had the version just before 3.2001 so it should be fine :)

**Comment by roubachof** [comment]
works :)
