### ISSUE TITLE
Support inserting newline between groups

### ISSUE THREAD

**Issue by tossingc** [Xavalon/XamlStyler#268]
Add configuration to insert newline between groups.

For improved readability, I like to separate element attributes into sections that are separated by newlines. I find that it makes it much easier to visually parse the element with that extra space between conceptual groupings of attributes.

**Comment by grochocki** [comment]
After reviewing this based on our [feature request guidelines](https://github.com/Xavalon/XamlStyler/blob/master/CONTRIBUTING.md#guidelines-for-feature-requests), we feel like this particular request reflects a personal style preference that might not be a good fit for the larger developer community, so we are declining this feature suggestion. Thanks for your contribution!
