### ISSUE TITLE
Support putting all properties of markup extensions/inline elements on separate lines

### ISSUE THREAD

**Issue by tossingc** [Xavalon/XamlStyler#269]
For source file line annotation purposes, I like to put the properties of markup extensions/inline elements on their own lines. This enables me to see when the element attribute was added separately from when the markup extension/inline element properties last changed.

I find that the trailing curly brace on its own line also helps in visually parsing where the attribute starts and ends.

Enable formatting of inline elements like this:

```
<DatePicker
    x:Name="DateOfBirthDatePicker"
    IsVisible="False"
    Date="{Binding
        DateOfBirth,
        Converter={StaticResource LocalDateToDateTimeConverter}
    }"
    />
```

NOTE: this would only apply where there was more than one property within the markup extension/inline element, leaving the below FirstName Binding on one line:

```
<Entry
    x:Name="FirstNameEntry"
    Text="{Binding FirstName}"
    Keyboard="Text"
    Placeholder="First Name"
    behaviors:NextControlBehavior.NextControl="{x:Reference DateOfBirthDatePicker}"
    />
```

**Comment by grochocki** [comment]
Check out the [Keep markup extensions of these types on one line](https://github.com/Xavalon/XamlStyler/wiki/Markup-Extension-Handling#keep-markup-extensions-of-these-types-on-one-line) setting. If you remove "Binding" from the list, it will put the properties on separate lines.
