### ISSUE TITLE
Update Required for "Script Integration/PowerShell" in Wiki

### ISSUE THREAD

**Issue by taoyouh** [Xavalon/XamlStyler#273]
**Describe the bug**
The [Script Integration/PowerShell](https://github.com/Xavalon/XamlStyler/wiki/PowerShell) and [Script Integration/Command Prompt](https://github.com/Xavalon/XamlStyler/wiki/Command-Prompt)  section in the Wiki does not work on the dotnet tool version 3.2003.9.

**To Reproduce**
1. Install the nuget package with instructions on nuget.org:
```
dotnet tool install --global XamlStyler.Console --version 3.2003.9
```
2. Try to follow the command on [Script Integration/PowerShell](https://github.com/Xavalon/XamlStyler/wiki/PowerShell) and [Script Integration/Command Prompt](https://github.com/Xavalon/XamlStyler/wiki/Command-Prompt). The file does not exist in `%USERPROFILE%\.nuget\packages\XamlStyler.Console\{version}\tools\xstyler.exe`. There is only an `.nuget\packages\xamlstyler.console\3.2003.9\tools\netcoreapp3.1\any\xstyler.dll` and an  `.dotnet\tools\xstyler.exe`

### Suggestion
Combine the two sections and update the content into the following:

**As a global tool**
1. Install the XamlStyler.Console as dotnet global tool:
```
dotnet tool install --global XamlStyler.Console --version 3.2003.9
```
2. Use the command `xstyler` directly in any shell.

**As a local tool**
1. Install XamlStyler.Cosole as dotnet local tool:
```
dotnet new tool-manifest
dotnet tool install XamlStyler.Console
```
2. In any shell, use the following commands:
```
dotnet tool restore
dotnet xstyler
```

**Comment by grochocki** [comment]
Thanks! Updated [Script Integration](https://github.com/Xavalon/XamlStyler/wiki/Script-Integration) with these details.
