### ISSUE TITLE
XamlStyler.Console changes file without... changes

### ISSUE THREAD

**Issue by stefandevo** [Xavalon/XamlStyler#289]
**Describe the bug**
When I run the XamlStyler.Console dotnet tool on a folder, it processes all files, makes no change, because everything is OK, but changes the file in such a way that git adds modified file but without changes.

**To Reproduce**
Run the tool on a folder that is already formatted correctly.

**Expected behavior**
No file changes, and no git modified files.

**Comment by grochocki** [comment]
Thanks for the bug report! Have you tried running this with the passive flag (-p)? Could you share the exact command you are running?

**Comment by stefandevo** [comment]
When I use the -p flag, then no files are written, but that's off course because of the fact that passive means you just check without modifications.
I use `xstyler -d ./Forms/ -r` in the root of my source tree (where my `Settings.XamlStyler` is).
If there aren't any modifications to be made, still all files get a modified flag in git (without no changes).

**Comment by grochocki** [comment]
Ah, gotcha -- yea, we should not be writing anything on format if there are no changes.

**Comment by Tyrrrz** [comment]
@stefandevo @grochocki could it be that xstyler changes line endings in a file? For example, the original file could be using LF but after running xstyler it changes to CRLF, which git considers as a change.

**Comment by LWChris** [comment]
I noticed some things

* this also happens in VS 2019 when you hit Ctrl+Shift+S to save the whole solution
* but only after **activating** the first XAML file (having a XAML file open already when loading the solution but not activating it isn't enough)
* saving will "modify" all unchanged, unopened XAML files
* saving will "unmodify" the active XAML file
* saving will not change an opened XAML file, no matter if currently "modified" or not according to the UI
* they byte content of the "modified" and "unmodified" files match
* the SHA256 hashes from Get-FileHash match
* using "git status" says "no modifications"

**Comment by barnski** [comment]
I find the behaviour on Ctrl+Shift+S problematic. XAML Styler formats then all the files in the solution, not those that need saving. Is there a way to work around that?
