### ISSUE TITLE
Why keep uninstalling Uwp sdk an reinstalling on every update?

### ISSUE THREAD

**Issue by EmilAlipiev** [Xavalon/XamlStyler#301]
I dont get why every time i install an update for xaml styler, it uninstalls and resintalls the uwp sdks. Does it make sense?

![image](https://user-images.githubusercontent.com/10422347/92296888-cecdf580-ef39-11ea-8a82-0cf116b1d6a8.png)

**Comment by grochocki** [comment]
What version of Windows and VS2019 are you on?

**Comment by EmilAlipiev** [comment]
this one was for VS 2019 pre 16.8 version but i had the same thing for VS 2019 16.7.2 as well
