### ISSUE TITLE
Allow to configure specific xml-attributes to not be encoded (Avalonia)

### ISSUE THREAD

**Issue by maxkatz6** [Xavalon/XamlStyler#302]
**Is your feature request related to a problem? Please describe.**
Right now it isn't possible to tell XamlStyler to not enforce XML encode for attribute values.
For instance, it breaks CSS-like selector syntax in Avalonia XAML.

**Describe the solution you'd like**
Allow to configure specific xml-attributes to not be encoded.
It could be new styler option IgnoreEncodeForAttributes
```json
{
   "IgnoreEncodeForAttributes": "Selector"
}
```

**Additional context**
Related issue https://github.com/Xavalon/XamlStyler/issues/300

**Comment by grochocki** [comment]
Instead of adding this as a separate setting, let's fold this into .axaml support as discussed [here](https://github.com/Xavalon/XamlStyler/issues/300#issuecomment-753622491).
