### ISSUE TITLE
Attribute ordering rule groups does not save

### ISSUE THREAD

**Issue by rotacioskapa** [Xavalon/XamlStyler#31]
By editing the default attribute ordering rule groups,
settings do not remain after visual studio is restarted.
Reproduce:
Switch rule 4 with rule 5.
Restart VS.
Now its reset to default

**Comment by NicoVermeir** [comment]
I can't seem to reproduce this. 

Let's see if we can figure this out:
- are you on the latest version? (2.2)
- are you using a configuration file?
- if yes, is that file writeable?

**Comment by NicoVermeir** [comment]
Closed because of no reply, if this is still an issue please open a new one with the requested info
