### ISSUE TITLE
Optionally sort event handlers after normal properties

### ISSUE THREAD

**Issue by jmairboeck** [Xavalon/XamlStyler#310]
**Is your feature request related to a problem? Please describe.**
It would be nice to have an option to have event handlers always after normal properties.

For example, CommandBindings are currently sorted like this:

```xml
<CommandBinding
    CanExecute="..."
    Command="..."
    Executed="..." />
```

which looks weird. I would like to have event handlers always come after normal properties. Of course, I could add a rule for this specific case, but a general option would be nice.

**Comment by grochocki** [comment]
Thanks for the suggestion! There are so many built-in events that I don't think this is something we could handle automatically, and there is an unlimited number of possible custom events that we would not be able to detect. Unless you can think of a novel way to dynamically detect events, I think your best option would be to add an ordering rule group and specify the events you use most a a new group.

**Comment by jmairboeck** [comment]
You would need to resolve the CLR type that corresponds to the XAML tag and use reflection on it to determine whether an attribute is a property or an event. But if you only work on the XAML itself and have no "code behind" model, this will be difficult or impossible (at least for local types).
