### ISSUE TITLE
Support for Jetbrains Rider 2020.3

### ISSUE THREAD

**Issue by jbachelor** [Xavalon/XamlStyler#313]
**Describe the bug**
I absolutely LOVE XAML Styler. It would be phenomenal if it could support the newest release, 2020.3. Thanks so much for this awesome tool!

**To Reproduce**
1. Update to latest version of Jetbrains Rider (currently 2020.3).
2. When you relaunch Rider and open up Preferences > Plugins > XAML Styler to see incompatibility message.

**Screenshots**
![image](https://user-images.githubusercontent.com/19045/102250497-a73fdf00-3ed1-11eb-861e-66a1511bc377.png)

**Version Info:**
 - OS: MacOS (10.15.5)
 - Rider version: 2020.3
 - XAML Styler: Jetbrains Rider plugin, 3.2008.4.0

**Comment by grochocki** [comment]
Implemented in #312
