### ISSUE TITLE
Support for JetBrains Rider IDE Build 203.*

### ISSUE THREAD

**Issue by jonathan-jd4software** [Xavalon/XamlStyler#314]
It would be great if XamlStyler supported the latest release of JetBrains Rider.
![Screenshot 2020-12-18 at 09 13 33](https://user-images.githubusercontent.com/7313813/102596781-954c7f00-4111-11eb-9bbc-96833cad1634.png)

**Comment by grochocki** [comment]
Added as part of #313. Will get an update out soon.
