### ISSUE TITLE
Add support of XamlStyler plugin for 2020.3 Rider version 

### ISSUE THREAD

**Issue by dranhovskyi** [Xavalon/XamlStyler#319]
**Describe the bug**
Provide support for the 2020.3 version of Rider

**To Reproduce**
Can't install the plugin from Rider market place or from the downloaded file

**Expected behavior**
Can install the plugin from Rider marketplace or from a downloaded file

**Screenshots**
![RiderXamlStyler](https://user-images.githubusercontent.com/25592237/106163314-afa65d80-6191-11eb-8420-17d92b410c9a.PNG)

**Version Info (please complete the following information):**
 - OS: Windows 10 (1903)
 - Rider: 2020.3
 - XAML Styler: XAML Styler 3.2008.4.0

**Comment by dfarrNTST** [comment]
Is there an expected time-frame for this update?  Would love to use this.

**Comment by MichaeIDietrich** [comment]
Yea, getting that fixed would be pretty nice. Rider 2021.1 might also be ready in a bunch of weeks. 
But last commit was on december, so this repo seems not to be maintained currently. 😐

**Comment by grochocki** [comment]
> Is there an expected time-frame for this update? Would love to use this.

Really sorry about the delay -- when we updated our build and release pipelines for Rider, we coupled it with Visual Studio and did not account for minor revision bumps to support Rider version changes. There are some lingering reports of upgrade issues on Visual Studio, so was delaying until we could investigate those. I will work around this by manually pushing an update later today.

> Rider 2021.1 might also be ready in a bunch of weeks.

I'll modify our release pipeline to allow for an immediate update for the Rider plugin once this change comes in such that the release isn't affected by the other extensions.

**Comment by grochocki** [comment]
Submitted [v2.3012.0](https://github.com/Xavalon/XamlStyler/releases/tag/Release-3.2012.0). Should be live after it is processes (within two business days, according to JetBrains). I also created this issue to track build pipeline improvements: #331.

**Comment by dranhovskyi** [comment]
@grochocki Thanks!
