### ISSUE TITLE
Inappropriately converting "&amp;" to "&"

### ISSUE THREAD

**Issue by TheMcCann** [Xavalon/XamlStyler#32]
XAML styler v2.1 is converting "&amp;" to "&".  There's no setting that seems to indicate XAML styler should be doing this, and it's causing problems because it produces invalid XAML.  Here's the full example that fails for me:

`Content="{Binding ViewModel.Procedure.InLiveEnvironment, Converter={cui:BooleanToObjectConverter TrueValue='OK', FalseValue='Save &amp; Close'}}"`

gets converted to

`Content="{Binding ViewModel.Procedure.InLiveEnvironment, Converter={cui:BooleanToObjectConverter TrueValue='OK', FalseValue='Save & Close'}}"`

**Comment by NicoVermeir** [comment]
Can you upgrade to 2.2 and try this again? I'm not able to reproduce the issue on the latest version

thanks

**Comment by TheMcCann** [comment]
It looks like it's fixed in 2.2.  Thanks!
