### ISSUE TITLE
Unable to download XAML Styler for Visual Studio for Mac

### ISSUE THREAD

**Issue by Bustillox** [Xavalon/XamlStyler#323]
**Describe the bug**
I'm not being able to download it from [this](http://addins.monodevelop.com/Project/Index/382) URL which is the one in the main repo page. The error I get is:

And nothing downloads.

**To Reproduce**
Go into the URL : [XamlStyler: Visual Studio for Mac](http://addins.monodevelop.com/Project/Index/382)

**Expected behavior**
I expect the XamlStyler for VSMAC to be downloadable

**Screenshots**
![image](https://user-images.githubusercontent.com/18311298/107590548-9a83f280-6bc5-11eb-92e0-b4c6d813bd85.png)

**Version Info (please complete the following information):**
 - OS: [MacOS BigSur 11.2.1]
 - Visual Studio: [VS For Mac 8.8.8]
 - XAML Styler: [V 2.0.1] 

**Additional context**
I've tried downloading it from three different computers and it won't download.

**Comment by ajtruckle** [comment]
I confirm the same error. I would like to install **XAML Styler** for Mac too if possible.

**Comment by ajtruckle** [comment]
Note that the original link was http. If you change it to https, so:

[https://addins.monodevelop.com/Project/Index/382](https://addins.monodevelop.com/Project/Index/382)

You will then see this instead of the error:

![Screenshot 2021-02-12 at 22 24 32](https://user-images.githubusercontent.com/7985331/107828615-20986880-6d81-11eb-9027-366d8e30b671.png)

Hope this helps!

**Comment by ajtruckle** [comment]
See:

https://docs.microsoft.com/en-us/visualstudio/mac/migrate-extensions?view=vsmac-2019

**Comment by Bustillox** [comment]
You're right. It seems that the only way to install the XamlStyler is to copy the folder with the .dlls into the addons folder of Visual  Studio... I hope this gets fixed soon !

**Comment by ajtruckle** [comment]
Where is the **addons** folder located?

**Comment by Bustillox** [comment]
/Users/{your.user}/Library/ApplicationSupport/VisualStudio/8.0/LocalInstall/Addins

Go ahead and drop this file in there and it will be working as expected.

In order to fully work you will need to close Visual Studio, and like in my case, restart your mac. Hope this helps!

[Xavalon.XamlStyler.2.0.1 2.zip](https://github.com/Xavalon/XamlStyler/files/5974735/Xavalon.XamlStyler.2.0.1.2.zip)

**Comment by ajtruckle** [comment]
Thanks. That worked!
