### ISSUE TITLE
Return to line with focus after reformatting XAML

### ISSUE THREAD

**Issue by ajtruckle** [Xavalon/XamlStyler#324]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I reformat my XAML and it jumps back to the top of the file in the editor.

**Describe the solution you'd like**
Try to remember what line (albeit approximately) had focus and return there after formatting the document.

**Additional context**
This would save me having to find where I was in the file again after reformatting.

Excellent extension by the way!!! 😊

**Comment by Saratsin** [comment]
Isn't it the same as #311 or it's related to another extension? What IDE do you use: VS for Mac, VS for Windows, Rider?

**Comment by ajtruckle** [comment]
VS for Mac.

Sometimes when building there is an error because of the xml being locked. I now always save the file before build.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by grochocki** [comment]
Since this is on VS for Mac, it appears to be a duplicate of #311. Closing this issue to continue the conversation there.
