### ISSUE TITLE
Build issues because of the automatic save and format feature. Can it be switched off?

### ISSUE THREAD

**Issue by ajtruckle** [Xavalon/XamlStyler#327]
<img width="645" alt="Screenshot 2021-02-17 at 22 34 52" src="https://user-images.githubusercontent.com/7985331/108276943-7baad080-7170-11eb-84e1-998143c3a84a.png">

This error stops the build process.

**Comment by grochocki** [comment]
Are you leveraging an [external settings configuration](https://github.com/Xavalon/XamlStyler/wiki/External-Configurations) in your project? If so, you can disable format on save with:

```json
{
    "FormatOnSave": false
}
```

**Comment by ajtruckle** [comment]
Thanks. I just made a file and added it to the top level of the master project. When I save it it says there is no schema. I am saving it in VS for Mac. Is that warning OK?

**Comment by grochocki** [comment]
I have not seen that before, but a schema is not necessary for XAML Styler to pick it up. It should be safe to ignore the warning.

**Comment by ajtruckle** [comment]
I still get the error. I wonder if the folder I used is not good enough? I put it in the master root folder for all three projects.

Is it not possible for this to be managed for a tick list via a GUI window?

Thanks for advice.

**Comment by ajtruckle** [comment]
<img width="404" alt="Screenshot 2021-02-19 at 20 54 24" src="https://user-images.githubusercontent.com/7985331/108560624-f00e7c80-72f4-11eb-9e47-18f0a03eb1b1.png">

This is where I put the file. Was that wrong? It is not being honoured.

**Comment by grochocki** [comment]
Any chance it it in a subdirectory in your main project folder? If so, it is possible it is getting picked up when formatting.

> XAML Styler will respect the first configuration file it finds in the folder up-hierarchy, so it is possible to use separate configurations for different projects or subdirectories.

**Comment by ajtruckle** [comment]
AsI have indicated, that folder it the highest … Yet I am still having the issue … Saving is restyling the file.

**Comment by grochocki** [comment]
Closing this as won't fix since [Visual Studio for Mac is scheduled for retirement by August 31, 2024](https://learn.microsoft.com/en-us/visualstudio/mac/what-happened-to-vs-for-mac?view=vsmac-2022).
