### ISSUE TITLE
Keep Control Name/x:Name on the same line as the call. so it remains visible when the control is condensed in visual studio

### ISSUE THREAD

**Issue by ghd796** [Xavalon/XamlStyler#330]
**Is your feature request related to a problem? Please describe.**
While not directly a problem it helps reduce confusion when looking at the code when the outlining is shrunken
*This is related to Visual Studio outlining
**Problem**
Currently a textbox code looks like this:

```
<TextBox
  x:Name="TbNewAmount"
  Text="This is my button" />
```

and when you close the outline:

```
<TextBox [...]/>
```

**Solution**
If you keep the NBame/x:Name on the first line like this

```
<TextBox x:Name="TbNewAmount"
  Text="This is my button" />
```

Then when it's closed it looks like this:

```
<TextBox [ x:Name="TbNewAmount"...]/>
```

this eliminates the need to add a comment to describe what the text box is. This would be greatly appreciated

> Edit: Updated for formatting. @ghd796, please let me know if I captured this right

**Comment by RedX2501** [comment]
I think you can use the external configuration and set

```
"FirstLineAttributes": "Name, x:Name, x:Uid",
"KeepFirstAttributeOnSameLine": true,
```

to be able to have the attribute on the first line.

**Comment by ghd796** [comment]
@RedX2501  Where Exactly would I enter these lines of code? What 'external configuration are you talking about?

**Comment by grochocki** [comment]
Yep, this should be possible today with existing options. Here is some more information on [First Line Attributes](https://github.com/Xavalon/XamlStyler/wiki/Attribute-Reordering#first-line-attributes) and [External Configurations](https://github.com/Xavalon/XamlStyler/wiki/External-Configurations).
