### ISSUE TITLE
Is there any way to keep namespace one per line while other attributes is 2 ore more per line?

### ISSUE THREAD

**Issue by JoacimWall** [Xavalon/XamlStyler#336]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by grochocki** [comment]
Can you update your issue with more details?

**Comment by JoacimWall** [comment]
hi
This is what I want. 

<img width="965" alt="image" src="https://user-images.githubusercontent.com/9278908/118444567-95b36b00-b6ed-11eb-90dd-9f53d7730f46.png">

**Comment by grochocki** [comment]
Hmm, I think I understand now -- would you consider this to be a duplicate of #329?

**Comment by JoacimWall** [comment]
> Hmm, I think I understand now -- would you consider this to be a duplicate of #329?

Yes
