### ISSUE TITLE
Visual Studio for Mac - "Indent with Tabs" checkbox is missing for settings

### ISSUE THREAD

**Issue by InquisitorJax** [Xavalon/XamlStyler#339]
Visual Studio for Mac - "Indent with Tabs" checkbox is missing for settings

**To Reproduce**
Open up VS for Mac Xaml Styler options from preferences. The first option "Indent with Tabs" - the checkbox is missing, so this option cannot be toggled on and off.

**Expected behavior**
The checkbox should be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/1822976/118779101-05129180-b88b-11eb-8f37-4d0d13bae9f3.png)

**Version Info (please complete the following information):**
 - OS: MacOS - latest Big Sur
 - Visual Studio: latest VS for Mac 8.9.10
 - XAML Styler: latest 2.0.1

**Comment by grochocki** [comment]
Closing this as won't fix since [Visual Studio for Mac is scheduled for retirement by August 31, 2024](https://learn.microsoft.com/en-us/visualstudio/mac/what-happened-to-vs-for-mac?view=vsmac-2022).
