### ISSUE TITLE
Markup extension formatting does work as expected when nested

### ISSUE THREAD

**Issue by FrecherxDachs** [Xavalon/XamlStyler#34]
Supposed you have two markup extensions, {Binding} and {LogicalAnd}.
In your Xaml Styler settings {Binding} is set to be kept on a single line.

If you format the given XAML, the result would be this:

```
<TextBox Text="Some Value"
         IsEnabled="{LogicalAnd {Binding IsWritable},
                                {Binding ElementName=CheckBox,
                                         Path=IsChecked}}" />
```

But the correct format would be:

```

<TextBox Text="Some Value"
         IsEnabled="{LogicalAnd {Binding IsWritable},
                                {Binding ElementName=CheckBox, Path=IsChecked}}" />
```

since {Binding} should be on a single line even if it is nested.

Currently the most outer markup extension defines the format for the whole attribute value.

This issue is fixed with: #33

**Comment by NicoVermeir** [comment]
thanks for the contribution!
I was checking out the PR and noticed that some unit tests are failing, could you have a look and update your PR?

thanks again!
