### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by scottkuhl** [Xavalon/XamlStyler#341]
### Installed product versions
- Visual Studio: 2022 All Versions

### Description
Make the extension available in Visual Studio 2022.

### Steps to recreate
1. Download the extension installer.
2. Run the installer.

### Current behavior
Message that it is already installed to all applicable products appears even though it is not installed in Visual Studio 2022.
It is also not listed in Online Extensions in Manage Extensions Visual Studio 2022.

### Expected behavior
Installs and works in Visual Studio 2022.

_Note: Sorry for the all the extra details.  I probably could have stopped with the title on this one._

**Comment by scottkuhl** [comment]
[Writing Visual Studio Extensions with Mads - Splitting extensions for Visual Studio 2022](https://www.youtube.com/watch?v=-PKIPTW6km0)

**Comment by virzak** [comment]
Implemented in #342 

Try the VSIXs: https://dev.azure.com/xavalon/XAML%20Styler/_build/results?buildId=401&view=artifacts

**Comment by scottkuhl** [comment]
A quick test and it installs into VS 2022 and formats the XAML like previous versions.

I subscribed to #342 so I'll know what it shows up in the Markplace.  Thanks!
