### ISSUE TITLE
Mac Version?

### ISSUE THREAD

**Issue by gordonsaxby** [Xavalon/XamlStyler#343]
It seems that the Visual Studio for Mac version of this plugin has been discontinued?!? Is a version still available to download from somewhere?

A colleague is using it on a Windows machine, so I would like to install it on my Mac too

**Comment by NicoVermeir** [comment]
hi @gordonsaxby 
the mac version is not discontinued, we do need to put some work in to work around monodevelop add-ins being discontinued.
more info can be found here: https://github.com/Xavalon/XamlStyler/issues/325

**Comment by gordonsaxby** [comment]
So, its there a Mac version available to download now, or not? If not, is there any expected date for one to be available?

**Comment by grochocki** [comment]
I've updated the link in the README to point to a direct download of Xavalon.XamlStyler_2.0.1.mpack
