### ISSUE TITLE
Different order of properties in Rider and VS 2019 plugins?

### ISSUE THREAD

**Issue by ziomek64** [Xavalon/XamlStyler#351]
**Describe the bug**
There is a different order of properties I think for both IDES. Example X:Name always at the top on VS2019 plugin but at the bottom in Rider

**To Reproduce**
Self explanatory

**Expected behavior**
Both have same formatting

**Comment by ziomek64** [comment]
Should I post some examples?

**Comment by martb1n** [comment]
Any updates on that? I have the same issue. In my team someone use Rider, someone use VS2019. We have the same settings, but formatting is different.

**Comment by NicoVermeir** [comment]
@ziomek64 @martb1n is this with an external XAML Styler config file?

**Comment by martb1n** [comment]
@NicoVermeir no. Default settings that came with installed plugin.

**Comment by NicoVermeir** [comment]
@martb1n thanks for the feedback. would it be possible to verify if the problem also exists with an external config file?

**Comment by martb1n** [comment]
@NicoVermeir if you could send me any config file, I can check

**Comment by NicoVermeir** [comment]
There is an example of the default settings on the wiki:
https://github.com/Xavalon/XamlStyler/wiki/External-Configurations

**Comment by martb1n** [comment]
@NicoVermeir as soon as I copy configuration from the link above, put it into the file and start use as Rider config - settings align between both VS 2019 and Rider IDEs. Thanks

**Comment by NicoVermeir** [comment]
great to hear! we would always advice to use an external configuration file when sharing a code base with a team.
I will close this issue for now. Thanks again for reporting back!

**Comment by ziomek64** [comment]
@NicoVermeir How is this closed? Plugins for both IDE should have same settings by default not only when you use configuration file
