### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by grochocki** [Xavalon/XamlStyler#353]
We are excited to add support for Visual Studio 2022. However, due to a limitation preventing us from publishing split extensions to the marketplace, we are holding on a release. This is something we plan to resolve before VS2022 leaves preview.

**Update (11/17):** As we work to merge this change (#360), we've released [XAML Styler for Visual Studio 2022](https://marketplace.visualstudio.com/items?itemName=TeamXavalon.XAMLStyler2022) in preview in the marketplace.

**Comment by AmitBhatnagar24** [comment]
Yes, this is desperately needed now that VS2022 is out of preview, and the side load version _does not_ seem to work with the released version.

**Comment by grochocki** [comment]
As we work to merge this change, we've released [XAML Styler for Visual Studio 2022](https://marketplace.visualstudio.com/items?itemName=TeamXavalon.XAMLStyler2022) in preview in the marketplace.

**Comment by ahmed-abdelrazek** [comment]
`Format Xaml` option disappeared from the context menu after i updated visual studio 2022 to latest version 17.0.6 (the hotkeys doesn't work too) and the extension version is the latest 3.2111.0 installed from Visual Studio Manage Extensions window
