### ISSUE TITLE
Rider  2021.3 EAP Support

### ISSUE THREAD

**Issue by vardansargsyan92** [Xavalon/XamlStyler#354]
**Is your feature request related to a problem? Please describe.**

An early access of rider has been released with **UWP app debugging** support which is nice. The bad news is that the plugin "Xaml.Styler" is not compatible with the new rider.

**Describe the solution you'd like**
It would be nice to see the plugin support for rider 2021.3

**Describe alternatives you've considered**
The alternative is to use VS2019 instead of rider

**Additional context**
_N/A_

**Comment by freza-tm** [comment]
Rider 2021.3 is now released

**Comment by roubachof** [comment]
would be cool if #340 would be fixed also, it's a real issue for more than 6 months...

**Comment by grochocki** [comment]
JetBrains previously denied our request for an open source development license, which we need to validate the changes. I just submitted another request to obtain a license so we can add support for 2021.3 and will keep this issue updated with progress.

**Comment by eliseiml** [comment]
Is it possible to build this plugin's code and use it as a 'local plugin' in my IDE?

**Comment by eliseiml** [comment]
I mean to use Styler in the Rider 2021.3

**Comment by grochocki** [comment]
> Is it possible to build this plugin's code and use it as a 'local plugin' in my IDE? I mean to use Styler in the Rider 2021.3

Yep, it should be easy enough to build and deploy locally.

Good news -- JetBrains approved our developer license request upon further review, so will work on getting an update published later this week.

**Comment by eliseiml** [comment]
Oh, that's amazing! Thanks.

**Comment by roubachof** [comment]
would be great if you could fix  #340 at the same time since it's actually pretty much unusable if you use an external config file.

**Comment by eliseiml** [comment]
Hi there) How it's going? Thousands of developers are waiting for the update))

**Comment by cesaryuan** [comment]
Any update?

**Comment by NicoVermeir** [comment]
I pushed a branch containing the changes
https://github.com/Xavalon/XamlStyler/tree/feature/rider2021

It builds and seems to install into the latest version of Rider just fine, but nothing happens. No menu items, no formatting.
Maybe @maartenba can spare a minute of his time? ;) (or anyone else with more Rider plugin experience than me)

**Comment by NicoVermeir** [comment]
@maartenba awesome, thanks!
for future reference: what did I miss to make it work?

**Comment by roubachof** [comment]
Hi guys! since you are at it, could you fix #340 ? Using a xamlstyler external file is causing the plugin to crash for now... So it means that dev teams cannot use xaml styler on rider for now (cause we must rely on the same rules to enforce the styles)

**Comment by NicoVermeir** [comment]
@roubachof there is a fix in Maarten's PR, once we fix the build pipeline and push this version out you can confirm the fix

**Comment by roubachof** [comment]
perfect ! thank you for the great job guys

**Comment by maartenba** [comment]
@NicoVermeir The missing element was in the Rider SDK version (https://github.com/Xavalon/XamlStyler/pull/364/files#diff-bc1ffab723d30f1cf2cf54a92d406d052575ef5b7b78410e59447946779a0afeR4), and this time around we also made some changes to the protocol so that had to be re-generated as well (not always going to be the case, but sometimes it is)
