### ISSUE TITLE
Cant Download XamlStyler file for VS for MAC

### ISSUE THREAD

**Issue by aleksandrsmyk** [Xavalon/XamlStyler#357]

**Comment by ionixjunior** [comment]
Hi @aleksandrsmyk! Other issues already discuss this problem https://github.com/Xavalon/XamlStyler/issues/343. Unfortunately, it doesn't have a workaround yet to solve this. But, you can do this yourself. See below:

1. Clone GitHub repo and open **src** folder using Terminal
2. Restore packages from **XamlStyler.Console** project: `nuget restore XamlStyler.Console/XamlStyler.Console.csproj`
3. Restore packages from **XamlStyler.Mac** solution: `nuget restore XamlStyler.Mac.sln`
4. Build **XamlStyler.Mac** solution: `msbuild /p:Configuration=Release XamlStyler.Mac.sln`
5. Using Terminal, go to **XamlStyler.Extension.Mac** folder and generate the package for Visual Studio: `sh create_mpack.sh`
6. A file called **Xavalon.XamlStyler_2.0.1.mpack** will be created in this folder. Install it on Visual Studio and be happy!

**Comment by kunalenterprise** [comment]
For all those guys who are still looking for the mac extension. I have attached the file below thanks to @ionixjunior 
[Xavalon.XamlStyler_2.0.1.mpack.zip](https://github.com/Xavalon/XamlStyler/files/7914911/Xavalon.XamlStyler_2.0.1.mpack.zip)

**Comment by grochocki** [comment]
I've updated the link in the README to point to a direct download of Xavalon.XamlStyler_2.0.1.mpack
