### ISSUE TITLE
Avoid linebreaks in text content. 

### ISSUE THREAD

**Issue by Montago** [Xavalon/XamlStyler#367]
I've just looked through the settings for XAML Styler again and didn't find what i was looking for. 

The Issue: 
```
<Label Grid.Row="0" Grid.Column="0" Margin="2">Empire</Label>
```

will be formatted to this:
```
<Label Grid.Row="0"
           Grid.Column="0"
           Margin="2">
        Empire
    </Label>
```

But I would like the content to be fitted between the ><:

```
<Label Grid.Row="0"
           Grid.Column="0"
           Margin="2">Empire</Label>
```

If this is already possible I just dont know how to do it :-/

**Comment by grochocki** [comment]
Please take a look at this section of the wiki on how we handle [whitespace](https://github.com/Xavalon/XamlStyler/wiki/Getting-Started#whitespace). There is this concept of "significant whitespace" in XAML that we need to maintain when formatting. When using [inline-level flow content elements](https://docs.microsoft.com/en-us/dotnet/api/system.windows.documents.inline), you will want to specify xml:space="preserve" on the parent XAML element to preserve whitespace properly.

Like this in your example:

```
<Label
    Grid.Row="0"
    Grid.Column="0"
    Margin="2"
    xml:space="preserve">Empire</Label>
```
