### ISSUE TITLE
Consolidate NuGet Packages to Align Versions

### ISSUE THREAD

**Issue by michael-hawker** [Xavalon/XamlStyler#377]
**Describe the bug**
Had pulled repro to look at fixing something and noticed there's a couple of packages `Newtonsoft.Json` and `CompareNETObjects` whose versions aren't aligned across the projects:

Not sure if want to switch to `System.Text.Json` at the same time or not, depends on what the scenarios are. Not sure if specific versions are being used due to issues that need to be addressed with upgrade or not.

**Expected behavior**
NuGet packages dependencies should use the same versions across dependenct projects

**Screenshots**
![image](https://user-images.githubusercontent.com/24302614/161309798-92e9353f-5948-4d9b-b503-5028136e2a52.png)

![image](https://user-images.githubusercontent.com/24302614/161309843-bd1966a8-5127-4e78-9f02-fc949ec34704.png)

**Comment by grochocki** [comment]
_Should_ be safe to update ```CompareNETObjects``` but there are gotchas with ```Newtonsoft.Json```. Updating can lead to unexpected behavior on older versions of Visual Studio (#242). More information here: [Using Newtonsoft.Json in a Visual Studio extension](https://devblogs.microsoft.com/visualstudio/using-newtonsoft-json-in-a-visual-studio-extension/)

**Comment by Jay-o-Way** [comment]
Is this still an issue with the latest version?

**Comment by grochocki** [comment]
CompareNETObjects had been updated since this issue was opened, but just created a PR to update packages across projects. Newtonsoft limitation still applies, though.
