### ISSUE TITLE
Visual Studio 2022 for Mac

### ISSUE THREAD

**Issue by roughiain** [Xavalon/XamlStyler#384]
Include support for Visual Studio 2022 for Mac [RC1](https://visualstudio.microsoft.com/vs/mac/preview/)

**Comment by timahrentlov** [comment]
This is the only thing missing before I can move to the new version

**Comment by nicjay** [comment]
Yes, please!

My "workaround" on 2022 right now is just opening up 2019 to re-save all my XAML when I'm ready to make a commit.

**Comment by roughiain** [comment]
Install the cli tool per wiki and run xstyler -f *.xaml. Wrap that up in gulp or grunt script to look for xaml file changes and auto formatting.

**Comment by HL-Tech** [comment]
This is highly requested

**Comment by waletoye** [comment]
any updates on this??

**Comment by tamasszadvari** [comment]
Are there any update on this? Using VS for Mac 2022 is almost mandatory on M1 chip Macbook's, so it's really important to have the XAML Styler for that IDE too.

**Comment by rudyspano** [comment]
Not optimal, but you can use both VS external tool feature and a script

<img width="971" alt="image" src="https://user-images.githubusercontent.com/21014908/184908942-42b71bd4-bcf7-42dd-a48f-7e56851c998e.png">

Script example to adapt:

```
#!/usr/bin/env bash

xaml_styler=$HOME/.nuget/packages/xamlstyler.console/3.0.0/tools/xstyler.exe
filename=$1

if [ ! -f $xamlstyler ]; then
    echo "XamlStyler not found ($xamlstyler)"
    exit 1
fi

mono $xaml_styler -f $filename

```

**Comment by NicoVermeir** [comment]
Sorry for the long silence on this everyone. I have been looking into the extension story for VS4Mac and it's all very confusing. It looks like no documentation exists, can't find an SDK and I'm reading several reports on how publishing is not possible right now either.
I have reached out to Microsoft for more information and will keep you posted.

**Comment by Saccomani** [comment]
I am using this script, working great! 


`#!/usr/bin/env bash

xaml_styler=$HOME/.nuget/packages/xamlstyler.console/3.2206.4/tools/net6.0/any/xstyler.dll
filename=$1

if [ ! -f $xamlstyler ]; then
    echo "XamlStyler not found ($xamlstyler)"
    exit 1
fi

dotnet $xaml_styler -f $filename
`

**Comment by roughiain** [comment]
not sure why the need to wrap it in a script.

*Replace {macUser} with your user folder*

External Tool settings

Command: `/Users/{macUser}/.dotnet/tools/xstyler`
Arguments: `-f ${FileDir}/${FileName} -c /Users/{macUser}/projects/settings/xstyler.json` *I'm passing a config file with custom settings*
KeyBinding: <kbd>ctrl</kbd> <kbd>shift</kbd> <kbd>f</kbd>

**Comment by NicoVermeir** [comment]
update on this: thanks to the MFractor team we now have an idea on where to start and are actively working on porting the VS4mac extension to VS 2022. Since there are quite a few breaking changes in the extension SDK this will however take a while.

Should anyone be interested in helping out, let me know and hopefully we can get a working version out soon.

**Comment by Saratsin** [comment]
> changes

I am the author of the initial version of Visual Studio for Mac extension, maybe I can help with this port. But I definitely will need help of the MFractor team, they have much greater expertise and Microsoft has drastically changed Visual Studio for Mac 2022

**Comment by Saratsin** [comment]
> update on this: thanks to the MFractor team we now have an idea on where to start and are actively working on porting the VS4mac extension to VS 2022. Since there are quite a few breaking changes in the extension SDK this will however take a while.
> 
> Should anyone be interested in helping out, let me know and hopefully we can get a working version out soon.

I am the author of the initial version of Visual Studio for Mac extension, maybe I can help with this port. But I definitely will need help of the MFractor team, they have much greater expertise and Microsoft has drastically changed Visual Studio for Mac 2022

**Comment by NicoVermeir** [comment]
@Saratsin would love your help! I'm at the point where it builds but when I run the extension I get a file not found exceptions on the Irony library. Any ideas on that one? If you want I can publish the branch already so you can take a look

**Comment by Saratsin** [comment]
@NicoVermeir yes, publish please your changes to the separate branch, I will check how it is working there

**Comment by NicoVermeir** [comment]
@Saratsin great! here it is: https://github.com/Xavalon/XamlStyler/tree/feature/vs4mac2022

**Comment by FreakyAli** [comment]
Hey guys any updates, I am getting restless 😀

**Comment by NicoVermeir** [comment]
@FreakyAli still working on it, it's not an easy upgrade :)

**Comment by FreakyAli** [comment]
@NicoVermeir Wish i could somehow show you my appreciation for doing this <3

**Comment by NicoVermeir** [comment]
quick update on this: basic functionality is working, but I'm having trouble getting the options panel in VS4mac. I'm not an experienced Mac UI developer so I could use some help here if anyone's up for it.

**Comment by bcaceiro** [comment]
Any news regarding VSMac2022 version?

**Comment by NicoVermeir** [comment]
@bcaceiro I'm still looking for help since I have limited access to a mac, and limited knowledge about vs4mac

**Comment by EmilAlipiev** [comment]
@roughiain can you please explain little bit more how this should work? do you have to download on the path /Users/{macUser}/.dotnet/tools/xstyler ? what i am supposed to have it here?

**Comment by roughiain** [comment]
Install as a global tool 

dotnet tool install --global XamlStyler.Console


More info as using it as script here https://github.com/Xavalon/XamlStyler/wiki/Script-Integration
