### ISSUE TITLE
How can I change the shortcut key?

### ISSUE THREAD

**Issue by kazuito** [Xavalon/XamlStyler#388]
I would like to change the shortcut key for this extension.
Could you please give me some tips?

thanks

**Comment by zrajnai-shapr3d** [comment]
Visual Studio
Tools / Customize ...   menu
Then "Keyboard..." button.

The command to bind to is  :  "EdotrContextMenus.CodeWindow.FormatXAML"

**Comment by kazuito** [comment]
Sorry for the late reply.
It was helpful, thank you.
