### ISSUE TITLE
VSCode Integration Workaround

### ISSUE THREAD

**Issue by jbagwell27** [Xavalon/XamlStyler#405]
I'm sure you get a lot of requests for VSCode integration. I wanted to share how I integrated the console version into VSCode using tasks. This was created on Windows, but for other OS you should just be able to change the command to include `dotnet` in the beginning.

In `tasks.json` I added the following entry:  

```json
{
      "label": "xstyler",
      "type": "shell",
      "command": "xstyler -f ${file}",
      "problemMatcher": []
}
```

Then in the `keybindings.json`, I mapped the task to a key combination

```json
{
      "key": "ctrl+shift+a", // This can be your own keybinding of choice
      "command": "workbench.action.tasks.runTask",
      "args": "xstyler"
}
```

When the task runs, it also saves the file, so I use it as an alternative key binding to save my XAML files.

**Comment by grochocki** [comment]
This is great, thank you! I've added this to our wiki :)

https://github.com/Xavalon/XamlStyler/wiki/VSCode
