### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by JaiganeshKumaran** [Xavalon/XamlStyler#411]
Visual Studio now supports Windows on ARM natively, without needing to emulate the x86 version. Please release a version of this extension ARM64.

**Comment by HavenDV** [comment]
Required steps for those who want to do PR. It seems to be simple:
https://devblogs.microsoft.com/visualstudio/now-introducing-arm64-support-for-vs-extensions/

**Comment by HavenDV** [comment]
PR is ready. This also contains a vsix file that can be installed before the release of the official version

**Comment by grochocki** [comment]
Thanks, @HavenDV! I am looking to get my hands on an ARM device for testing your PR. In the meantime, if anyone can validate the VSIX file in the PR build, please 🚀 this comment.

**Comment by Jaiganeshkumaran** [comment]
I've tested the ARM version of the VSIX from the PR, it works flawlessly.

**Comment by vhugogarcia** [comment]
Awesome to hear it works amazing on ARM. Any plans to release the new version for ARM support?

**Comment by HavenDV** [comment]
Perhaps I should somehow request a review for the PR?

**Comment by vhugogarcia** [comment]
I have one question, is this compatible with VS 2022 for mac?

**Comment by EmilAlipiev** [comment]
@vhugogarcia i am also wondering. On the description only stated VS mac 2019 and i cannot see this among the extensions on Apple silicon macbook. did you find answer for your question?

**Comment by vhugogarcia** [comment]
> @vhugogarcia i am also wondering. On the description only stated VS mac 2019 and i cannot see this among the extensions on Apple silicon macbook. did you find answer for your question?

Not really. Still waiting for a response 🙃

**Comment by grochocki** [comment]
ARM64 support is supported in v3.2311.2.0 in publishing now.
