### ISSUE TITLE
Format Selection text

### ISSUE THREAD

**Issue by shinho** [Xavalon/XamlStyler#417]
**Is your feature request related to a problem? Please describe.**
When formatting existing code in the repository, the format occurs in all of the file text. In a bad format file that leads to a lot of changes not related to what I'm changing (in a bug for instance)

**Describe the solution you'd like**
To be able to format just the selected text.

**Describe alternatives you've considered**

**Additional context**

**Comment by Jay-o-Way** [comment]
Duplicate of #67
