### ISSUE TITLE
How do I change the keyboard shortcut to launch XamlStyler?

### ISSUE THREAD

**Issue by it19862** [Xavalon/XamlStyler#421]
**Describe the bug**
How do I change the keyboard shortcut to launch XamlStyler?
I am in the XAML editor
When I press "Ctrl+S", the XAML markup is sorted.
Does XamlStyler sort the XAML markup?
XAML markup sorting is performed by XamlStyler because I pressed "Ctrl+S"?
XAML markup sorting is performed by XamlStyler because VS performs saving?

**To Reproduce**

---- 

**Expected behavior**

---

**Screenshots**
![21 03 2023_16-18-09](https://user-images.githubusercontent.com/18245828/226619251-e60a09a2-9a61-4143-aed3-a00adac0bb38.png)

![21 03 2023_16-13-50](https://user-images.githubusercontent.com/18245828/226619283-1dbfd21c-4ceb-413b-9944-ee42f0604365.png)

**External Configuration**

----

**Version Info (please complete the following information):**
 - OS: [Windows 10 ]
 - Visual Studio: [VS 2022 Community х64 (17.4.3),]
 - XAML Styler: [3.2208.1] 

**Additional context**

**Comment by grochocki** [comment]
XAML Styler can be configured to [Format on Save](https://github.com/Xavalon/XamlStyler/wiki/Miscellaneous#format-xaml-on-save), so you can disable this in extension options in VS or in the settings configuration file. You can also configure specific [attribute ](https://github.com/Xavalon/XamlStyler/wiki/Attribute-Reordering) and [element](https://github.com/Xavalon/XamlStyler/wiki/Element-Reordering) reordering settings.
