### ISSUE TITLE
How do I get a JSON configuration file?

### ISSUE THREAD

**Issue by it19862** [Xavalon/XamlStyler#422]
**Describe the bug**
How do I get a JSON configuration file?
Export the configuration file to JSON.
I am exporting as specified in **Getting-Started#importexport-settings** - (https://github.com/Xavalon/XamlStyler/wiki/Getting-Started#importexport-settings )
I get the file: **Exported-2023-03-21 .vssettings**
In the folder `c:\users\root\appdata\local\microsoft\visualstudio\17.0_d0a38a5a\settings\`

The **XamlStyler** documentation states that the configuration file must be JSON
https://github.com/Xavalon/XamlStyler/wiki/External-Configurations

File **Exported-2023-03-21 .vssettings**
`<UserSettings><ApplicationIdentity version="17.0"/><ToolsOptions/><Category name="XAML Styler_XAML Styler Settings" Category="{4b298c23-a923-31f3-b35b-0c0e4d202eba}" Package="{a224be3c-88d1-4a57-9804-181dbef68021}" RegisteredName="XAML Styler_XAML Styler Settings" PackageName="StylerPackage"><PropertyValue name="AttributeIndentation">0</PropertyValue><PropertyValue name="AttributeIndentationStyle">Spaces</PropertyValue><PropertyValue name="AttributeOrderingRuleGroups">x:Class
xmlns, xmlns:x
xmlns:*
x:Key, Key, x:Name, Name, x:Uid, Uid, Title
Grid.Row, Grid.RowSpan, Grid.Column, Grid.ColumnSpan, Canvas.Left, Canvas.Top, Canvas.Right, Canvas.Bottom
Width, Height, MinWidth, MinHeight, MaxWidth, MaxHeight
Margin, Padding, HorizontalAlignment, VerticalAlignment, HorizontalContentAlignment, VerticalContentAlignment, Panel.ZIndex
*:*, *
PageSource, PageIndex, Offset, Color, TargetName, Property, Value, StartPoint, EndPoint
mc:Ignorable, d:IsDataSource, d:LayoutOverrides, d:IsStaticText
Storyboard.*, From, To, Duration</PropertyValue><PropertyValue name="AttributesTolerance">2</PropertyValue><PropertyValue name="CommentSpaces">2</PropertyValue><PropertyValue name="ConfigPath"/><PropertyValue name="EnableAttributeReordering">True</PropertyValue><PropertyValue name="FirstLineAttributes"/><PropertyValue name="FormatMarkupExtension">True</PropertyValue><PropertyValue name="FormatOnSave">True</PropertyValue><PropertyValue name="IgnoreDesignTimeReferencePrefix">False</PropertyValue><PropertyValue name="KeepFirstAttributeOnSameLine">False</PropertyValue><PropertyValue name="MaxAttributeCharactersPerLine">0</PropertyValue><PropertyValue name="MaxAttributesPerLine">1</PropertyValue><PropertyValue name="NoNewLineElements">RadialGradientBrush, GradientStop, LinearGradientBrush, ScaleTransform, SkewTransform, RotateTransform, TranslateTransform, Trigger, Condition, Setter</PropertyValue><PropertyValue name="NoNewLineMarkupExtensions">x:Bind, Binding</PropertyValue><PropertyValue name="OrderAttributesByName">True</PropertyValue><PropertyValue name="PutAttributeOrderRuleGroupsOnSeparateLines">False</PropertyValue><PropertyValue name="PutEndingBracketOnNewLine">False</PropertyValue><PropertyValue name="RemoveDesignTimeReferences">False</PropertyValue><PropertyValue name="RemoveEndingTagOfEmptyElement">True</PropertyValue><PropertyValue name="ReorderCanvasChildren">False</PropertyValue><PropertyValue name="ReorderGridChildren">False</PropertyValue><PropertyValue name="ReorderSetters">None</PropertyValue><PropertyValue name="ReorderVSM">Last</PropertyValue><PropertyValue name="ResetToDefault">False</PropertyValue><PropertyValue name="RootElementLineBreakRule">Default</PropertyValue><PropertyValue name="SaveAndCloseOnFormat">True</PropertyValue><PropertyValue name="SearchToDriveRoot">False</PropertyValue><PropertyValue name="SpaceBeforeClosingSlash">True</PropertyValue><PropertyValue name="ThicknessAttributes">Margin, Padding, BorderThickness, ThumbnailClipMargin</PropertyValue><PropertyValue name="ThicknessStyle">Comma</PropertyValue></Category></UserSettings>`

---
**To Reproduce**
....

----
**Expected behavior**
I am exporting the XamlStyler configuration in JSON format

----
**Screenshots**
....

----
**External Configuration**
....

----
**Version Info (please complete the following information):**
 - OS: [Windows 10]
 - Visual Studio: [VS 2022 Community х64 (17.4.3),]
 - XAML Styler: [3.2208.1] 

---
**Additional context**
....

**Comment by grochocki** [comment]
That option lets you export/import your Visual Studio settings. Check out our documentation on [external configurations](https://github.com/Xavalon/XamlStyler/wiki/External-Configurations) if you would prefer to use a config file instead of VS settings to manage your XAML Styler settings for a project.

Right now, you need to set this configuration manually, but there is an open issue tracking a feature request to introduce a configuration generator to help with this process (#270).
