### ISSUE TITLE
Formatting fails if a comment contains 'xmlns:'

### ISSUE THREAD

**Issue by CorneliusRupertJackson** [Xavalon/XamlStyler#426]
**Describe the bug**
The formatting fails with an error messagebox with the following content:

>Error in StylerPackage:
>
>'<', hexadecimal value 0x3C, is an invalid attribute character.
>Line 9, position 5.

This occurs when a comment that contains the string "xmlns:" is located above an XAML element anywhere.
The XAML element needs at least one set property (as in ```x:Name="Button"``` or ```Foreground="Black"```)

**To Reproduce**
1. Create a new XAML file (ResourceDictionary in the example)
2. Add some XAML element and a comment containing 'xmlns:' that is located above the element
``` xml
<ResourceDictionary 
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <!--  Comment that contains 'xmlns:'  -->

    <Style x:Key="SomeStyle" />

</ResourceDictionary>
```
3. Select the right-click option "Format XAML"
4. The error messagebox appears:
![image](https://github.com/Xavalon/XamlStyler/assets/114663863/31466296-12ac-4206-859c-1ef99b047353)

**Version Info (please complete the following information):**
 - OS: Windows 10 Pro (21H2)
 - Visual Studio: VS2022 (17.5.5)
 - XAML Styler: Extension (3.2208.1)

**Comment by mrlacey** [comment]
This looks like a bug in the XML parsing...🤔

**Comment by mrlacey** [comment]
> This looks like a bug in the XML parsing...🤔

Nope. It's an issue with the `XmlEscapingService` not handling this correctly.

The "escaped" version of the above produces this:

```xml
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="[x]http://schemas.microsoft.com/winfx/2006/xaml">
    <!--  Comment that contains 'xmlns:'  -->

    <Style x:Key="['  -->

    <Style x:Key]SomeStyle" />
</ResourceDictionary>
```

This in turn causes `XDocument.Parse` to fail. (because the escaped XML isn't valid.)
