### ISSUE TITLE
Publish latest XamlStyler.Console to NuGet

### ISSUE THREAD

**Issue by crobibero** [Xavalon/XamlStyler#429]
**Is your feature request related to a problem? Please describe.**
The latest version available on NuGet is `3.2206.4`
The latest version in the repo is `3.2208.1`

**Describe the solution you'd like**
I would like the latest version published to NuGet so I can use the recently added .axaml support

**Describe alternatives you've considered**
N/A

**Additional context**
https://www.nuget.org/packages/XamlStyler.Console

**Comment by crobibero** [comment]
@grochocki I don't see a difference in the runs for 3.2206.4.0 and 3.2308.2.0, is it possible that the package was pushed to nuget, but just not made public?

**Comment by Jay-o-Way** [comment]
Looks like @grochocki has left the building... Who's taking this over?

**Comment by grochocki** [comment]
Sorry about that. I will look into manually publishing the latest later tonight after getting #441 in.

**Comment by grochocki** [comment]
v3.2311.2 has been published: https://www.nuget.org/packages/XamlStyler.Console

**Comment by Jay-o-Way** [comment]
Thank you!
