### ISSUE TITLE
Markup extension formatting no longer works

### ISSUE THREAD

**Issue by RandomEngy** [Xavalon/XamlStyler#432]
**Describe the bug**
Markup extension formatting is not working. When running lately it undid all of the nice formatting that an earlier run had added.

<img width="1234" alt="image" src="https://github.com/Xavalon/XamlStyler/assets/9450861/d50d90b0-c1d8-456d-a82c-4d4180d4e767">

**To Reproduce**
Format this XAML:
```xaml
<RadioButton
	VerticalAlignment="Center"
	Content="{x:Static res:EncodingRes.Bitrate}"
	IsChecked="{Binding EncodeRateType,
						Converter={StaticResource EnumBoolConverter},
						ConverterParameter={x:Static model:AudioEncodeRateType.Bitrate}}" />
```

When formatted with Markup extension formatting enabled, it all gets combined into one line:

```xaml
<RadioButton
	VerticalAlignment="Center"
	Content="{x:Static res:EncodingRes.Bitrate}"
	IsChecked="{Binding EncodeRateType, Converter={StaticResource EnumBoolConverter}, ConverterParameter={x:Static model:AudioEncodeRateType.Bitrate}}" />
```

**Expected behavior**
The IsChecked line stays formatted with multiple lines, with Converter and ConverterParameter each on its own line.

**Version Info (please complete the following information):**
 - OS: Windows 11
 - Visual Studio: 2022 17.6.4
 - XAML Styler: Extension 3.2111.0

**Comment by grochocki** [comment]
Can you confirm whether you have anything listed under the ```NoNewLineMarkupExtensions``` option? By default, this is set to ```x:Bind``` or ```Binding```, which would prevent the desired formatting as described above. If I remove those, then formatting returns the following for me when ```FormatMarkupExtension``` is set to true.

```xml
<RadioButton
	VerticalAlignment="Center"
	Content="{x:Static res:EncodingRes.Bitrate}"
	IsChecked="{Binding EncodeRateType,
						Converter={StaticResource EnumBoolConverter},
						ConverterParameter={x:Static model:AudioEncodeRateType.Bitrate}}" />
```
