### ISSUE TITLE
Add support for Rider 2023.2

### ISSUE THREAD

**Issue by ComradeNixco** [Xavalon/XamlStyler#433]
**Is your feature request related to a problem? Please describe.**
Rider has updated to 2023.2 and this version isn't suupported by XamlStyler

**Describe the solution you'd like**
Have it support Rider 2023.2.

**Describe alternatives you've considered**
Downgrade Rider while waiting for this update

**Comment by timahrentlov** [comment]
Yup. Would be nice to have support.

**Comment by ComradeNixco** [comment]
Also, question since I don't exactly know how versionning of plugins work, isn't it possible to have the extension support all minor versions of a major one like 2023.* or there's too much differences in Jetbrain's "minor" versions?

**Comment by NicoVermeir** [comment]
@ComradeNixco it used to be that you had to update the extension on every new Rider release. Apparently they have changed that and it should be possible to include more versions but I would need to look into how that works

**Comment by EmilAlipiev** [comment]
So it is only a matter of compile and publish?

**Comment by NicoVermeir** [comment]
@EmilAlipiev  It's a matter of adjusting some values in config files, compile and push

**Comment by grochocki** [comment]
Update was submitted! It should be live as soon as the submission is approved.
