### ISSUE TITLE
Position Setter each attribute on a separate line

### ISSUE THREAD

**Issue by CodingOctocat** [Xavalon/XamlStyler#435]
Current behavior:

```XAML
<Setter TargetName="ABC" Property="Background" Value="{StaticResource PrimaryBrush}" />
```

Expected behavior: like Visual Studio XAML formatting > Spacing > Position each attribute on a separate line(Position first attribute on same line as start tag)

```XMAL
<Setter TargetName="ABC"
        Property="Background"
        Value="{StaticResource PrimaryBrush}" />
```

**Comment by grochocki** [comment]
Please see [Newline Exemption Elements](https://github.com/Xavalon/XamlStyler/wiki/Attribute-Formatting#newline-exemption-elements) for configuration. By default, Setter is included in the list of elements whose attributes are not broken across lines. If you remove Setter, you should be able to achieve the desired formatting described above.

**Comment by CodingOctocat** [comment]
Problem solved.

> If you remove Setter, you should be able to achieve the desired formatting described above.
