### ISSUE TITLE
XamlStyler moves <!--#endregion--> wrongly

### ISSUE THREAD

**Issue by Baka632** [Xavalon/XamlStyler#437]
**Describe the bug**
When XAML source code contains ```<!--#endregion-->```, XamlStyle moves it wrongly

Before formatting:
```
<!--#region Visual State Manager-->
<VisualStateManager.VisualStateGroups/>
<!--#endregion-->
```

After formatting:
```
<!--#endregion-->

<!--#region Visual State Manager-->
<VisualStateManager.VisualStateGroups/>
```

**To Reproduce**
1. Format XAML source code that contains ```<!--#endregion-->```
2. See error

**Expected behavior**
```<!--#endregion-->``` should follow the previous XAML element

**Screenshots**
Before:
![image](https://github.com/Xavalon/XamlStyler/assets/48171809/fd1f968d-3edf-4550-8ca6-b439957d3945)

After:
![image](https://github.com/Xavalon/XamlStyler/assets/48171809/907bc61d-9daa-48e0-be09-b7b2615478ed)

**External Configuration**
*No*

**Version Info (please complete the following information):**
 - OS: Windows 11 22H2 (22621.2134)
 - Visual Studio: VS 2022 (17.7.1)
 - XAML Styler: Extension (3.2208.1)

**Additional context**
*No*

**Comment by grochocki** [comment]
Can you only reproduce this issue with ```VisualStateManager```? If so, can you try setting [ReorderVSM](https://github.com/Xavalon/XamlStyler/wiki/Element-Reordering#reorder-visual-state-manager) to "None" and see if you can still reproduce the issue?

**Comment by Baka632** [comment]
Yes, I can only reproduce this issue with ```VisualStateManager```

And after setting ReorderVSM to "None", the issue disappeared.

**Comment by grochocki** [comment]
Is leaving that setting as "None" feasible for your project? The challenge here is that the region could be around _any_ arbitrary block of XAML.

**Comment by Baka632** [comment]
Yes it is feasible for my project.

Usually ```VisualStateManager``` is very long so I use region to keep my code tidy and I won't add other XAML element inside.

**Comment by grochocki** [comment]
Thanks for confirming! Going to close this as _wont fix_ for now as there is a viable workaround for handling VSM.
