### ISSUE TITLE
XAML Styler firing for Project files (*.csproj) also after updating to v3.2311.2. Previously, it was working fine.

### ISSUE THREAD

**Issue by egvijayanand** [Xavalon/XamlStyler#448]
**Describe the bug**
XAML Styler firing for Project files (*.csproj) also after updating to v3.2311.2. Previously, it was working fine.

**To Reproduce**
1. While saving the project file with the XML PI node, it throws an error
2. Refer to the below screenshot for Error details:

**Expected behavior**
It should attempt to format only XAML files as the name suggests and optionally XML files with the **xml** extension.

**Screenshots**
![image](https://github.com/Xavalon/XamlStyler/assets/81947404/51610115-8678-40f1-a7a9-6e49b249b691)

**External Configuration**
NA

**Version Info (please complete the following information):**
 - OS: Windows 11 ver. 10.0.22631.2715
 - Visual Studio: VS2022 17.9 Preview 1.0
 - XAML Styler: v3.2311.2

**Additional context**
This started to occur after the recent update a few days ago.

**Comment by kmgallahan** [comment]
@grochocki Not critical, but this is fairly annoying.

**Comment by ghost1372** [comment]
i get this too

**Comment by mrlacey** [comment]
I see this as a result of a change within VS (probably in 17.8) rather than relating to something changed in this extension.

**Comment by egvijayanand** [comment]
> I see this as a result of a change within VS (probably in 17.8) rather than relating to something changed in this extension.

Even then the extension is supposed to work accordingly. Rather it shows some weird dialog.

**Comment by mrlacey** [comment]
> > I see this as a result of a change within VS (probably in 17.8) rather than relating to something changed in this extension.
> 
> Even then the extension is supposed to work accordingly. Rather it shows some weird dialog.

I commented only to say that the assertion in the issue title may be misleading. Working on a fix now.

**Comment by ghost1372** [comment]
@grochocki  can you publish a new version with this fixed issue?
This bug is very annoying

**Comment by grochocki** [comment]
> I am investigating an issue with the release build of the extension for VS2022 that is preventing it from loading properly, even though it seems to work find under debug. Will publish update as soon as I am able to resolve.

Tracking with #479.
