### ISSUE TITLE
Unexpected results with <elements> in text

### ISSUE THREAD

**Issue by Jay-o-Way** [Xavalon/XamlStyler#454]
**Describe the bug**
When having some text-related elements in a paragraph, the spaces and newlines before and after the elements are changed in a bad way.

**To Reproduce**
1. When formatting text in a \<Paragraph> that contains elements, like **Bold** or **Hyperlink**
2. Spaces and newlines are bad

**Expected behavior**

- There must remain a space on the _outside_ of these tags. However, if the element is (already) followed by a period `.` or comma `,`, then there must be no space inserted. If this does happen, an unwanted and incorrect [space] is visible in the UI .
- A **Linebreak** is preferred at the end of an actual line, and a new line is supposed to come after that.

**Screenshots**
![image](https://github.com/microsoft/WinUI-Gallery/assets/65828559/003896ff-09d0-42cc-b111-66cfec169298)

**External Configuration**

**Version Info (please complete the following information):**
 - OS: Windows 11 23H2
 - Visual Studio: 17.8.3
 - XAML Styler: 3.2311

**Additional context**
I believe Visual Studio also has a habit of messing with these spaces and/or newlines. Might wanna reach out to that team, if possible?

**Comment by grochocki** [comment]
Please take a look at this section of the wiki on how we handle [whitespace](https://github.com/Xavalon/XamlStyler/wiki/Getting-Started#whitespace). There is this concept of "significant whitespace" in XAML that we need to maintain when formatting. If you are mixing [inline-level flow content elements](https://docs.microsoft.com/en-us/dotnet/api/system.windows.documents.inline) with other text (as in your example), you will want to specify xml:space="preserve" to preserve whitespace properly.

**Comment by Jay-o-Way** [comment]
Thanks. Will try, and see if that matches my expectation.

**Comment by grochocki** [comment]
Glad that worked! The note on runs is specifically about back-to-back run elements. Anything more than that, and you should really use ```xml:space="preserve"``` to preserve intended whitespace. Updated wiki text to help clarify:

> Please note that if you are mixing [inline-level flow content elements](https://docs.microsoft.com/en-us/dotnet/api/system.windows.documents.inline) with other text, you may need to specify xml:space="preserve" **on the parent element in XAML** to preserve whitespace properly.
