### ISSUE TITLE
Suggestion: Central package versioning

### ISSUE THREAD

**Issue by hansmbakker** [Xavalon/XamlStyler#464]
While going through the source, I noticed some projects reference different versions of the same dependency. `XamlStyler.csproj` has Newtonsoft.Json 9.0.1, while `XamlStyler.Console.csproj` has Newtonsoft.Json 13.0.1.

By adding a file `Directory.packages.props` containing the needed package versions and by removing the version info from the csproj files, [you can manage the versions of nuget package dependencies centrally](https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management#enabling-central-package-management).

**Comment by grochocki** [comment]
Unfortunately, there are gotchas with ```Newtonsoft.Json```. Updating can lead to unexpected behavior on older versions of Visual Studio (#377), so this is _by design_ for now. More information here: [Using Newtonsoft.Json in a Visual Studio extension](https://devblogs.microsoft.com/visualstudio/using-newtonsoft-json-in-a-visual-studio-extension/).
