### ISSUE TITLE
Incompatible with Rider EAP 

### ISSUE THREAD

**Issue by bcaceiro** [Xavalon/XamlStyler#469]
**Describe the bug**
Cannot use this plugin on Rider EAP - this build is incompatible : requires IDE Build 233.* or earlier

**To Reproduce**

**Expected behavior**
Be compatible with rider EAP

**Comment by bagusnl** [comment]
just a heads up, Rider has now updated their stable to 2024.1, breaking Xaml Styler for stable users

**Comment by kovrom** [comment]
Hopefully pull #484 will be merged soon

**Comment by grochocki** [comment]
The change in #484 is not complete. If there are folks more familiar with Rider IDE, I could use some help in getting this PR ready.

**Comment by kovrom** [comment]
> The change in #484 is not complete. If there are folks more familiar with Rider IDE, I could use some help in getting this PR ready.

Sadly I'm not familiar with plugin development for Rider IDE. But changing <SdkVersion>2024.1.0-rc01</SdkVersion> to the latest <SdkVersion>2024.1.0</SdkVersion> seems to build and install fine locally, without complaints from gradlew.bat

**Comment by grochocki** [comment]
Ah, 2024.1.0 wasn't available when I started working on this, and couldn't get 2024.1.0-rc01 to work. @kovrom could you help verify [this build](https://dev.azure.com/xavalon/009fbb1c-6908-4943-8811-9ec612ecd322/_apis/build/builds/547/artifacts?artifactName=XamlStyler.Extension.Rider&api-version=7.1&%24format=zip) in Rider?

**Comment by kovrom** [comment]
> Ah, 2024.1.0 wasn't available when I started working on this, and couldn't get 2024.1.0-rc01 to work. @kovrom could you help verify [this build](https://dev.azure.com/xavalon/009fbb1c-6908-4943-8811-9ec612ecd322/_apis/build/builds/547/artifacts?artifactName=XamlStyler.Extension.Rider&api-version=7.1&%24format=zip) in Rider?

Seems to be working fine :+1:

**Comment by grochocki** [comment]
Submitted 3.2404.4 update to JetBrains!
