### ISSUE TITLE
TODO: Release XamlStyler 3.2401

### ISSUE THREAD

**Issue by BinToss** [Xavalon/XamlStyler#472]
# Changes

### XamlStyler.Console

- **expand console support for axaml**

### XamlStyler.Console

- handle unhandled FileNotFoundException
- deps: upgrade NuGet.CommandLine from 6.6.1 to 6.8.0

### XamlStyler.Extension.Windows.VS2022

<details><summary>deps</summary>

- deps: upgrade CompareNETObjects from 4.79.0 to 4.83.0
- deps: upgrade Microsoft.CodeAnalysis.NetAnalyzers from 7.0.3 to 8.0.0
- deps: upgrade Microsoft.VisualStudio.SDK from 17.5.33428.399 to 17.8.37.222
- deps: upgrade Microsoft.VSSDK.BuildTools from 17.5.4074 to 17.8.2365
</details>

### XamlStyler.Extension.Windows.VS2019

<details><summary>deps</summary>

- deps: upgrade CompareNETObjects from 4.79.0 to 4.83.0
- deps: upgrade Microsoft.CodeAnalysis.NetAnalyzers from 7.0.3 to 8.0.0
- deps: upgrade Microsoft.VSSDK.BuildTools from 17.5.4074 to 17.8.2365
</details>

### XamlStyler.Extension.Windows.Shared

- **improve handling of internal VS exceptions relating to .csproj files**

### XamlStyler.UnitTests

<details><summary>deps</summary>

- deps: upgrade CompareNETObjects from 4.79.0 to 4.83.0
- deps: upgrade Microsoft.NET.Test.Sdk from 17.7.0 to 17.8.0
- deps: upgrade NUnit from 3.13.3 to 4.0.1
</details>

## Miscellaneous

- update copyright year to 2024
- remove XamlStyler.Mac from main

----

Commits since 3.2308.2:
https://github.com/Xavalon/XamlStyler/compare/Release-3.2308.2...master
![image](https://github.com/Xavalon/XamlStyler/assets/7243190/218fe05c-29b4-4946-b175-764487d8ed7b)

**Comment by heartacker** [comment]
Hi，is it easy to support net7/8 not only net 6？ please

**Comment by mrlacey** [comment]
@BinToss  is this issue a request to release an update that contains a list of merged changes? Or is it something else?

@heartacker is there a specific issue with using net6 (beyond it being out of support)?

**Comment by heartacker** [comment]
nothing else but https://github.com/Xavalon/XamlStyler/issues/447

**Comment by BinToss** [comment]
> @BinToss  is this issue a request to release an update that contains a list of merged changes? Or is it something else?

Just the merged changes, good sir. Personally, the addition of [".axaml" as an acceptable XAML file extension](49ddadf16aaaf17a4aa0a168e58f4c23c7e60db6) is what motivated this request.

**Comment by grochocki** [comment]
I am investigating a blocking issue with the release build of the extension for VS2022 that is preventing it from loading properly. Unfortunately, I am not unable to deploy the extension under debug, blocking progress (#479). Will use that issue to track releasing updated version, so closing this issue.
