### ISSUE TITLE
New releases blocked on release build extension deployment bug and VS debugging

### ISSUE THREAD

**Issue by grochocki** [Xavalon/XamlStyler#479]
I am investigating a blocking issue with the release build of the extension for VS2022 that is preventing it from loading properly, even though it seems to have worked fine under debug. Unfortunately, I am not unable to deploy the extension under debug, blocking progress. This issue has been reported to the Visual Studio team: [Unable to deploy VSIX to VS2022 under debugger](https://developercommunity.visualstudio.com/t/Unable-to-deploy-VSIX-to-VS2022-under-de/10629651).

**Comment by mrlacey** [comment]
What's the blocking issue?

I can build release versions locally and install and run without issue.

---

Your deployment issue sounds like something went wrong with a VS update. Have you tried a full VS reinstall? (I know it can be frustrating and time-consuming, but it may be quicker than waiting on MS.)

**Comment by mrlacey** [comment]
Do you have a copy of the exception log in English?
And can you verify a possible version mismatch as I [commented on the other issue](https://github.com/Xavalon/XamlStyler/issues/466#issuecomment-2035410158)?

**Comment by mrlacey** [comment]
Having just checked the source, there's an inconsistency between the minimum install target and the version of the SDK that the extension tries to use. This can cause package load failures -- ask me how I know ;)

**Comment by grochocki** [comment]
> Do you have a copy of the exception log in English?

Unfortunately, not from my repro. Also, it wasn't the same version reported in that issue, but latest release builds out of our pipeline on the latest VS release at the time.

> Having just checked the source, there's an inconsistency between the minimum install target and the version of the SDK that the extension tries to use.

Is there any documentation on this?

**Comment by mrlacey** [comment]
> > Having just checked the source, there's an inconsistency between the minimum install target and the version of the SDK that the extension tries to use.
> 
> Is there any documentation on this?

Not that I'm aware of. I only learned this when someone on the VS team helped debug why one of my extensions was throwing a similar exception.

I'm putting together a PR with a fix, and lots of comments.

**Comment by grochocki** [comment]
Clean install on a spare device unblocked my issue. Published VSIX updates for 2017, 2019, 2022, and Console. Release details [here](https://github.com/Xavalon/XamlStyler/releases/tag/Release-3.2404.2).
