### ISSUE TITLE
Are External Configurations in options handled as you would expect?

### ISSUE THREAD

**Issue by grochocki** [Xavalon/XamlStyler#48]
There was an interesting conversation that was started in #46 about how we handle External Configurations in **Tools → Options → XAML Styler** that we wanted to pull out as to discuss more broadly.

Current Behavior:
- Specifying an External Configuration _overwrites_ user settings
- Originally intended to be a global override used by companies/organizations/teams as a distribution mechanism, where personal preferences influence team guidelines
- Can also be used as an alternate importing mechanism
- Makes it clear what ruleset is being applied (just open options)
- Only friendly-view of an external configuration (e.g., enums are difficult to parse to a user unfamiliar with the code by looking at a raw configuration)

Proposed Changed Behavior:
- Specifying an External Configuration is strictly a _runtime override_ of user settings
- Removing an External Configuration will revert back to user settings, preventing individual preferences from ever being lost
- Can make it clear that an external configuration is being applied by displaying a warning in options instead of showing the values that are being applied
- Lose alternate importing mechanism and friendly-view of external configuration, but potentially more consistent with tools like StyleCop

Is the current behavior confusing? Which behavior is preferred? Are there scenarios that one behavior can handle better than the other?

**Comment by JohanLarsson** [comment]
I can try to sum up my view:
```
Foo.sln
Foo.sln.xamlstyle
  Bar.csproj
  Bar.csproj.xamlstyle
```
With the following resolution precedence:
1 *.csproj.xamlstyle
2 *.sln.xamlstyle
3 Other settings file specified in plugin settings
4. Default plugin settings.

When thinking about it I can't think of a case where per project style makes sense.

**Comment by grochocki** [comment]
There has not been enough feedback to indicate that we should change from the current behavior, so we will be closing this issue for now. Please feel free to reactivate it if new conversation is warranted.
