### ISSUE TITLE
Rider EAP build

### ISSUE THREAD

**Issue by JohnTraDolta** [Xavalon/XamlStyler#493]
**Is your feature request related to a problem? Please describe.**
When using the EAP version of Rider the plugin is "Incompatible", and therefore it´s not working.  

**Describe the solution you'd like**
I dont know if it is as simple as changing a "Supported Version" variable. 

If it is then I, and others, can help find breaking changes before the stable version of rider is released.

**Describe alternatives you've considered**
I've considered using the stable version of rider but then i will be missing some of the new features 

![billede](https://github.com/Xavalon/XamlStyler/assets/42833298/9a969d38-af37-49a7-abed-23d3eb5b0862)
![billede](https://github.com/Xavalon/XamlStyler/assets/42833298/1ff45aa5-66d4-4899-ac75-7b506e0e2c1b)

**Comment by albilaga** [comment]
as [Rider 2024.2 now released](https://x.com/JetBrainsRider/status/1824013737910476897) any idea if this will be updated @grochocki ?

**Comment by ziomek64** [comment]
I also would like to know, this extension is really good for development with XAML

**Comment by grochocki** [comment]
Shifting to #500 to track
