### ISSUE TITLE
Attribute identation is broken if using tabs

### ISSUE THREAD

**Issue by igor-mikushkin** [Xavalon/XamlStyler#5]
Attributes are idented with tabs instead of spaces if using keep tabs option in version 2.1 (installed via VS' Extensions and Updates).
In previous version (2.0) attribute identation (relative to tag) was done with spaces.
This behavior is much more preferable.

**Comment by PolarbearDK** [comment]
I did that! It was a feature request done due to some add-in's complaining about mixed tabs/spaces when opening the files.

I can see that this need to be configurable. 
(I actually prefer the old "style" with tabs and then spaces)

**Comment by grochocki** [comment]
The fix for this issue has been merged into master.
