### ISSUE TITLE
New rider version

### ISSUE THREAD

**Issue by trinixe** [Xavalon/XamlStyler#500]
JetBrains released new version 2024.2, could you please update your plugin?
Thank you

**Comment by ziomek64** [comment]
@trinixe this needs to merge i believe - https://github.com/Xavalon/XamlStyler/pull/499

**Comment by NicoVermeir** [comment]
as an update: Rider 2024.2 needs the gradle intellij plugin version 2, which contains lots of breaking changes
https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-migration.html#intellij-extension

unfortunately documentation is very "spartan", so it looks like more time is needed. If anyone has the know-how, and the time, to chime in: please do!

**Comment by grochocki** [comment]
Update was submitted! It should be live as soon as the submission is approved.
