### ISSUE TITLE
TextBlock text getting ruined

### ISSUE THREAD

**Issue by xmenxwk** [Xavalon/XamlStyler#501]
Adds unnecessary space and creates new line if` <Bold> `is used inside TextBlock.

Text should show **text**.differentText but it shows **text** .differentText

**To Reproduce**
```
<TextBlock>
<Bold>text</Bold>.differentText
</TextBlock>
```

will convert to

```
<TextBlock>
<Bold>text</Bold> 
.differentText</TextBlock>
```

**Expected behavior**
```
<TextBlock>
<Bold>text</Bold>.differentText
</TextBlock>
```
do not modify text format inside TextBlock

**Version Info (please complete the following information):**
 - OS: Win10
 - Visual Studio: 2022
 - XAML Styler: 3.2404.2

**Comment by grochocki** [comment]
Please take a look at this section of the wiki on how we handle [whitespace](https://github.com/Xavalon/XamlStyler/wiki/Getting-Started#whitespace). There is this concept of "significant whitespace" in XAML that we need to maintain when formatting. If you are mixing [inline-level flow content elements](https://docs.microsoft.com/en-us/dotnet/api/system.windows.documents.inline) with other text (as in your example), you will want to specify xml:space="preserve" to preserve whitespace properly.
