### ISSUE TITLE
Is it possible to use $(SolutionDir) when setting up the external config file?

### ISSUE THREAD

**Issue by mlachancee** [Xavalon/XamlStyler#52]
Hello,

I'm trying to use XAML Styler with my team and we would like to use the same external config file that would be in our repo. We didn't clone our repos in the same directory on our computers so it is impossible for use to use an absolute path. Is it possible to use $(SolutionDir) when setting up the external config file?

Thank you very much!

**Comment by NicoVermeir** [comment]
this would probably do what you need:
https://github.com/Xavalon/XamlStyler/pull/46

we're ready to upload 2.3 to the gallery with this feature included but the VS Gallery seems to be broken at the moment

**Comment by mlachancegsoft** [comment]
Yes, it does seems to satisfy the need I have! I'll check it out as soon as the new version is up :) Thanks!

**Comment by mlachancegsoft** [comment]
Hello,

Just saw that you've updated to 2.3 on VS Gallery (yay!). I was wondering how exactly the external configuration files are now handled. Is it as simple as to add a Settings.XamlStyler config file in the Solution Directory? I created a Settings.XamlStyler file inspired by the one in your wiki.

When I removed the absolute path that pointed to my config file in the solution directory, the configs from my file doesn't seem to show in the options menu. Is this normal?

Also, it seems like the config file is fetch and used when I right click and then click on "Format XAML". But it also seems to call that file even though I specified not to format when I save in my config file. Is this normal?

Thanks again!

**Comment by NicoVermeir** [comment]
the config file overwrites the settings as long as you're working in that solution. the embedded settings do not reflect in the options menu as those are the global settings.

best way to look at it:
embedded settings file: team settings
no settings file: user defined settings from the options menu

as for the triggering on save, you'll probably need to set that in the settings file to disable it

**Comment by mlachancegsoft** [comment]
Thanks for your answer!

It is clearer now! On the other hand, do you plan to set the "Format on Save" option as a team/project settings also and not only a general setting? This settings seems to be related to the general settings (true but default) even though is it set to false in our team's config file.

The reason I ask this, is that my team and I would like to have a common config file that would be in our repo. So when a new member joins the team, that new member only has clone the repo and install XamlStyler and no more config would be needed (like StyleCop does). Now, the process would be the same, but a new member would have to change that specific option before starting to work with us. It is not the end of the world but I was just wondering.

Thanks!

**Comment by grochocki** [comment]
IMO, the save option feels to me more like a personal preference and largely unrelated from the rest of the options. For example, personally, I dislike format on save, because I am a compulsive saver and would prefer there to not be a hiccup in that flow.

On the other hand, I can also definitely understand the desire for a Format On Save option in team/project settings. I imagine your goal is to ensure folks can't forget to format files they are touching, which makes a lot of sense. Is there an alternate way that you can accomplish this? For example on my team, we use the [Git Hook](https://github.com/Xavalon/XamlStyler/wiki/Git-Hook) option to ensure all modified XAML files are formatted on check-in.

**Comment by mlachancegsoft** [comment]
Hey! You're right, the save options is more of a personnal preference! I'll check the Git Hook options with my team :) Thanks! 

On an other subjet, I was wondering how the external files would work with a project containing multiple other projects? Would I simply add it to the folder with ".sln" file? Or would I need it to add the file to every folder with a ".csproj"?

Thanks again for your help, it is greatly appreciated!

**Comment by Tadimsky** [comment]
Are there any ways to diagnose why this wouldn't be working for me?

I have a solution with 3 projects - all in different locations.
I put the Settings.XamlStyler file in the root directory of the solution (next to the .sln file) as well as in the root directory of the XAML Project file (next to the vcxproj file) but neither are working.
Putting the file path directly in the settings menu works - it seems like it's not finding the file?

Any tricks to find out why this may not be working? Can I debug it?

**Comment by grochocki** [comment]
@mlachancegsoft, great! Let me know how it works out for you. I need to update the Wiki with more details about how the per solution/project-based configurations work, but given a XAML file, it will respect the first settings file it finds up the folder hierarchy to the solution root directory. In your case, if you put the configuration file in the solution directory, all projects will respect it.

@Tadimsky, I would double-check to make sure you are in fact running the latest update. Otherwise, if you try using the console application (either via Nuget or standalone download), there is some debug output that may help.

**Comment by mlachancegsoft** [comment]
@grochocki Do you know if the GitHook will work with different Version Control app (ex. SourceTree, GitKraken, SmartGit, Command Line, ...)?

Also, I seem to have the same problem as @Tadimsky. The `Settings.XamlStyler` config file doesn't seem to be used by XamlStyler when formatting my files. It works with single project solutions I have, but not with the multiple projects solution I have. I've check and I've got 2.3 installed. I also tried, adding the file to the root of my solution, but it still didn't work. If it might help, I have two .sln in my folder hierarchy.

For example, here are all the spots I've tried adding the `Settings.XamlStyler` config file. Unfortunatly, none of them seem to be working.

```
ApplicationFolder/
    MainProject/
        MainProject/
            ...
            MainProject.csproj
        ...
        MainProject.sln
        Settings.XamlStyler

    SecondaryProject/
        SecondaryProject/
            ...
            SecondaryProject.csproj
        ...
        SecondaryProject.sln
        Settings.XamlStyler

    ProjectA/
        ...
        ProjectA.csproj
    ProjectB/
        ...
        ProjectB.csproj
    ProjectC/
        ...
        ProjectC.csproj

    Settings.XamlStyler

Settings.XamlStyler
```
Hope this helps!

(Also, is there an easy way of seeing all the `Console.WriteLine` output used in the `Log` method of the class `Program.cs` of the XamlStyler project.)

**Comment by Tadimsky** [comment]
@grochocki it looks like I'm running 2.3: 
![image](https://cloud.githubusercontent.com/assets/1149244/20322532/5a1d567a-ab2e-11e6-8485-5ddbf9c99f69.png)

Here are the logs from running with the console application:

```
C:\Users\joschm\Downloads\XamlStyler.Console-2.3.0>xstyler.exe -f E:\ONWBNext\deb\<project name>\view\controls\bottombarcontrol\bottombarcontrol.xaml
Processing: E:\ONWBNext\deb\<project name>\view\controls\bottombarcontrol\bottombarcontrol.xaml
In solution root: False
Looking in: E:\ONWBNext\deb\<project name>\view\controls\bottombarcontrol
In solution root: False
Looking in: E:\ONWBNext\deb\<project name>\view\controls
In solution root: False
Looking in: E:\ONWBNext\deb\<project name>\view
In solution root: False
Looking in: E:\ONWBNext\deb\<project name>
Configuration Found: E:\ONWBNext\deb\<project name>\Settings.XamlStyler
Processed 1 of 1 files.
```

That seemed to find the file and honor it - is that because it's looking at the xaml file itself and not the project / solution?

**Comment by Tadimsky** [comment]
Any insights here @grochocki ? I'd love to get this working for our team.
It worked from the Console but it seems like the logic is slightly different there? Is there a way to debug what's going on with the plugin? Can I attach a debugger to VS?

**Comment by mlachancee** [comment]
@Tadimsky Still no answer? My team would also love using this!
@grochocki Any idea on why the config file isn't used properly?

**Comment by grochocki** [comment]
Sorry, I was on holiday last week and just now catching up on things.

@mlachancee Regarding working with other version control systems, the [Git Hook](https://github.com/Xavalon/XamlStyler/wiki/Git-Hook) relies on Git commands, so it will not work without modification. It should not be too hard to tweak it, though. The number of examples right now is pretty small, but if you come up with a useful recipe, let us know, and we will add it to the Wiki for others to use in their projects.

Regarding showing log output, I added details in the wiki on [xstyler console command options](https://github.com/Xavalon/XamlStyler/wiki/Script-Integration#help) that should help with this.

@mlachancee/@Tadimsky As for not detecting the settings file, having two solutions is interesting, though probably a red herring. Taking a look at how we detect settings files in the up folder hierarchy, there does seem to be a difference between the [plugin](https://github.com/Xavalon/XamlStyler/pull/46/files) and the [console](https://github.com/Xavalon/XamlStyler/pull/50/files) implementations. I will dig into this a bit. You can attach a debugger, but would need to add some debug output to the plugin code.

**Comment by grochocki** [comment]
Closing discussion on this question--bug captured by #73
