### ISSUE TITLE
Error while formatting a file which has a name containing ":"

### ISSUE THREAD

**Issue by mlachancegsoft** [Xavalon/XamlStyler#53]
Hello,

I recently got this error when trying to format a XAML file I have. 

![image](https://cloud.githubusercontent.com/assets/22968383/19600401/dece34ae-9772-11e6-90a6-6d211504401f.png)

I think, this is due to the fact that I'm referencing another assembly in my file (that is in the namespace "utils"). When a property of this assembly is changed inside a setter I call the property using "utils:_ClassOfAssembly_._PropertyName_".
When commenting the setter that uses "utils:..", the formatting worked just fine! But when the setter is uncommented, I get the error message shown previously.

Thank you!

**Comment by NicoVermeir** [comment]
Hi,

this has been reported before and is fixed in our next release. the release is ready but the gallery is having some issues so we can't push it out right now, but should be okay somewhere next week (I hope)

**Comment by mlachancegsoft** [comment]
Oh perfect, thank you :) sorry about that! Can't wait to use this new version!
