### ISSUE TITLE
Proposed changes to default settings

### ISSUE THREAD

**Issue by grochocki** [Xavalon/XamlStyler#6]
We are considering changing some of the default settings for XamlStyler and wanted to solicit feedback from the community. The changes are summarized below and would only affect new users, since existing users settings will restore properly on launch.

**Position first attribute on same line as start tag**
Current Default:True
Proposed Default: False
Reasoning: Width considerations. It is common for teams/projects to have column limits. This would allow more XAML to more cleanly fit on a line before hitting that limit.

**Reorder Canvas panel children by left/top/right/bottom**
Current Default: True
Proposed Default: False
Reasoning: Ordering of children in a canvas matters. True by default will break some XAML that depends on this.

**Reorder Grid panel children by row/column**
Current Default: True
Proposed Default: False
Reasoning: Ordering of children in a grid matters. True by default will break some XAML that depends on this.

**Keep markup extensions of these types on one line**
Current Default: x:Bind
Proposed Default: x:Bind, Binding
Reasoning: Bindings should be treated the same as x:Bind.

**Thickness style**
Default: None
Proposed Default: Comma
Reasoning: This is consistent with XAML coming out of MS (samples, generic.xaml, etc.).

**Attribute Ordering Rule Group**
"x:Class*",
"xmlns, xmlns:x",
"xmlns:*",
"x:Key, Key, x:Name, Name, x:Uid, Uid, Title",
"Grid.Row, Grid.RowSpan, Grid.Column, Grid.ColumnSpan, Canvas.Left, Canvas.Top, Canvas.Right, Canvas.Bottom",
"Width, Height, MinWidth, MinHeight, MaxWidth, MaxHeight",
"Margin, Padding, HorizontalAlignment, VerticalAlignment, HorizontalContentAlignment, VerticalContentAlignment, Panel.ZIndex",
"Style, Background, Foreground, Fill, BorderBrush, BorderThickness, Stroke, StrokeThickness, Opacity",
"FontFamily, FontSize, LineHeight, FontWeight, FontStyle, FontStretch",
"*:*, *",
"PageSource, PageIndex, Offset, Color, TargetName, Property, Value, StartPoint, EndPoint",
"mc:Ignorable, d:IsDataSource, d:LayoutOverrides, d:IsStaticText"

**Comment by bartlannoeye** [comment]
I'm missing x:Bind/Binding in the ordering rules. Would like to see it after x:Key and before Grid.Row

**Comment by PolarbearDK** [comment]
x:Bind/Binding are markup extensions that occur within the value of attributes. 

Attribute ordering rule groups relates to the **name** of attributes, not value.
