### ISSUE TITLE
"MaxAttributeCharatersPerLine" Mispelled

### ISSUE THREAD

**Issue by jneidlinger** [Xavalon/XamlStyler#64]
See https://github.com/Xavalon/XamlStyler/blob/master/XamlStyler.Core/Options/IStylerOptions.cs#L30

`int MaxAttributeCharatersPerLine { get; set; }`

"Charaters" should be "Characters" 

Would of submitted a patch, but wanted to first discuss if we we need to keep the misspelled version as well for backwards compatibility.

**Comment by grochocki** [comment]
Hmm, I think it _would_ break backward compatibility, but I also think we also may be able to work around it. It would be a bit more complicated, but either that, or we never fix it.
