### ISSUE TITLE
Setting to disable when there is no config file

### ISSUE THREAD

**Issue by bartlannoeye** [Xavalon/XamlStyler#65]
Some of the projects I'm working are using XamlStyler while others are not (and introducing it is not possible due to political reasons). It would be nice to have a setting that I can disable XamlStyler by default if there is no external config file available. This way I can support both type of solutions on the same dev machine without too much trouble.

**Comment by grochocki** [comment]
Is this to prevent accidently formatting a document on save or (out of habit) right-click?

Would disabling format on save be sufficient? Perhaps aided by #4?

If not, how would you expect this to work? For example, do you imagine just a Boolean flag under Miscellaneous Settings, like "Enable for solution-based configurations only"?

**Comment by bartlannoeye** [comment]
It's to prevent accidental formatting in projects that aren't using it indeed.
The boolean flag "Enable format on save for solution-based configurations only" should be enough indeed. As I suppose some people would like to keep this.

**Comment by grochocki** [comment]
Alternatively, if you could enforce "format on save" via the configuration, and then disable "format on save" in settings, would this also work? The nice thing about this approach is that it would not add a special setting.
