### ISSUE TITLE
VS2017

### ISSUE THREAD

**Issue by tlhintoq** [Xavalon/XamlStyler#68]
I remember when going from 2013 to 2015 it was just a matter of some flag or value needing to be set saying the VSIX was 2015 friendly.  Any chance its the same case here?  I'd love to use this in the new VS2017

**Comment by NicoVermeir** [comment]
It's a bit more involved this time since they moved to vsix 3
We're working on supporting it and improving performance with the new extension loading apis

**Comment by fforjan** [comment]
Happy to be a beta tester if required ;)

**Comment by luetm** [comment]
Same here :), happy to beta test. One of my most missed extensions :)

**Comment by NicoVermeir** [comment]
let me get you guys up to date on this :)
we're currently discussing how to tackle this. VS2017 has some very nice changes on loading and handling extensions that we could really benefit from, however it would break VS2015 support.

our current thought process is to release a new package called "XAML Styler 3" and use that for VS2017 support and maintain the current package for VS2015. 

does this sound like a reasonable way to go? any other ideas?

**Comment by luetm** [comment]
@NicoVermeir 
Thanks for the info! I update to the latest VS Version as soon as it comes out, so I don't really need the VS2015 version to be maintained at all. However, I understand that some teams decide or are required to stay on 2015 or even older.

For me, the 2015 version worked well and I never felt it needed any big updates (the only thing that was a problem was the {}{0} issue in StringFormat). So my suggestion would be to keep making bugfixes to the 2015 version (or XAML Styler 2) if necessary, but focus mainly on XAML Styler 3.

If VS2017 offers a better API I'd go for it, since it will make development more efficient.

**Comment by tlhintoq** [comment]
I like the scheme you've proposed (XAML Styler 3).  Very clean... 'Line in the sand' kind of thing.

**Comment by jstevenson72** [comment]
Also love to help beta test.  I'd be willing to pay money to contribute to the availability of this extension.  My OCD and Source Control are greatly impacted by not having your wonderful tool for 2017.  Let me know how to contribute, and if you need any testing.

**Comment by NicoVermeir** [comment]
we have it working in VS2017 but are running into an issue where the right-click option is not showing up. once that's fixed we should be good to release a new version

**Comment by jstevenson72** [comment]
Sounds Great!  Would be a wonderful present!  Like I said, let me know if you have a donate button for PayPal somewhere.  LOVE this tool, it's integral to minimizing diffs within our team and source control.

**Comment by tlhintoq** [comment]
I'd be happy to run it without the right click.  Been doing it that way for Xamarin for quite a while.  Shortcut keys of cntrol-K, cntrol-2 are burned into my brain.

As I pointed out on the Xamarin Bugzilla bug:
https://bugzilla.xamarin.com/show_bug.cgi?id=41048#c1
XAML Styler is the best work-around for a bug in their Style/property inheritance.  Not having this tool is killing me.

**Comment by jstevenson72** [comment]
I agree, I just need at version whether I have to type a command to run it
or not.

**Comment by NicoVermeir** [comment]
I think we have a working release. I'd like some people to try it out before we push it to the gallery.
if you want to give it a whirl, the vsix can be found here:
https://1drv.ms/u/s!AnM0l16xWzRaxNVD8wRnalzKUCifbQ

feel free to give feedback and thanks for testing!

**Comment by luetm** [comment]
Oh yes finally :) Works good for me so far!

**Comment by NicoVermeir** [comment]
https://marketplace.visualstudio.com/items?itemName=TeamXavalon.XAMLStyler
we're live on the marketplace! (note that we dropped the "3" from the extension title but it is published as a separate extension than the VS2013-2015 one)

**Comment by jstevenson72** [comment]
The install isn't working for me.  I noticed from the log it isn't finding Visual Studio 2017.  My VS RC installed itself here: **C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE**

Here is the install log:

> 1/11/2017 10:12:18 AM - Microsoft VSIX Installer
1/11/2017 10:12:18 AM - -------------------------------------------
1/11/2017 10:12:18 AM - Initializing Install...
1/11/2017 10:12:18 AM - Extension Details...
1/11/2017 10:12:18 AM - 	Identifier         : a224be3c-88d1-4a57-9804-181dbef68021
1/11/2017 10:12:18 AM - 	Name               : XAML Styler 3
1/11/2017 10:12:18 AM - 	Author             : Xavalon
1/11/2017 10:12:18 AM - 	Version            : 3.0
1/11/2017 10:12:18 AM - 	Description        : XAML Styler is a visual studio extension, which formats XAML source code by sorting the attributes based on their importance. This tool can help you/your team maintain a better XAML coding style as well as a much better XAML readability.
1/11/2017 10:12:18 AM - 	Locale             : en-US
1/11/2017 10:12:18 AM - 	MoreInfoURL        : https://github.com/Xavalon/XamlStyler/
1/11/2017 10:12:18 AM - 	InstalledByMSI     : False
1/11/2017 10:12:18 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
1/11/2017 10:12:18 AM - 
1/11/2017 10:12:18 AM - 	SignatureState     : Unsigned
1/11/2017 10:12:18 AM - 	Supported Products : 
1/11/2017 10:12:18 AM - 		Microsoft.VisualStudio.Pro
1/11/2017 10:12:18 AM - 			Version : [15.0,16.0)
1/11/2017 10:12:18 AM - 		Microsoft.VisualStudio.Enterprise
1/11/2017 10:12:18 AM - 			Version : [15.0,16.0)
1/11/2017 10:12:18 AM - 		Microsoft.VisualStudio.Community
1/11/2017 10:12:18 AM - 			Version : [15.0,16.0)
1/11/2017 10:12:18 AM - 
1/11/2017 10:12:18 AM - 	References         : 
1/11/2017 10:12:18 AM - 		-------------------------------------------------------
1/11/2017 10:12:18 AM - 		Identifier   : Microsoft.VisualStudio.MPF.15.0
1/11/2017 10:12:18 AM - 		Name         : Visual Studio MPF 15.0
1/11/2017 10:12:18 AM - 		Version      : [15.0]
1/11/2017 10:12:18 AM - 		MoreInfoURL  : 
1/11/2017 10:12:18 AM - 		Nested       : No
1/11/2017 10:12:18 AM - 
1/11/2017 10:12:18 AM - Signature Details...
1/11/2017 10:12:18 AM - 	Extension is not signed.
1/11/2017 10:12:18 AM - 
1/11/2017 10:12:18 AM - Searching for applicable products...
1/11/2017 10:12:18 AM - Found installed product - Microsoft Visual Studio Enterprise 2015
1/11/2017 10:12:18 AM - Found installed product - Microsoft Visual Studio Professional 2015
1/11/2017 10:12:18 AM - Found installed product - Microsoft Visual Studio Community 2015
1/11/2017 10:12:18 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
1/11/2017 10:12:18 AM - Found installed product - Global Location
1/11/2017 10:12:18 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by tlhintoq** [comment]
Looks about the same as my log.  I got the same results from the one I got from the market place and from the dropbox link
```

**Comment by jstevenson72** [comment]
@tlhintoq I've found this has nothing to do with the extension or it's installer.  It was related to my installation of VS RC.  I confirmed by trying other extensions from the gallery and got the same result.

You need to find the installer, and then have it uninstall VS 2017. Then reinstall it.

Afterwards the VSIX should work, or at least it did for me.

**Comment by tlhintoq** [comment]
@jstevenson72 
Thanks but... I'm not running VS2017 on this PC.  I'm running VS2015u3 Enterprise.

**Which makes me an idiot.**  I'm running VS2017 AT HOME and forgot that the installers are a "line in the sand": One installer for pre-2017 and a different one for 2017 and later.
I'm a dork. And burned from the day.  Going home and will try it there on 2017 were it belongs.

**Comment by Janek91** [comment]
I got error during installation: "This extension is not installable on any currently installed products" 
This is error log of this installation: http://pastebin.com/eKLfe4a4

**Comment by NicoVermeir** [comment]
@Janek91 do you have VS2017 RC1 installed?

**Comment by Janek91** [comment]
I think so. It's the newest available now version.
![2017-01-13 11_27_50-about microsoft visual studio](https://cloud.githubusercontent.com/assets/7473827/21926774/77a41eda-d983-11e6-83bf-5af05889cf67.png)

**Comment by NicoVermeir** [comment]
are you installing from the gallery or from the vsix I posted in this thread?

**Comment by Janek91** [comment]
From vsix. Is it on the gallery now?

**Comment by NicoVermeir** [comment]
it is! :) can you try from there?

**Comment by Janek91** [comment]
Yes, now it went well. Thanks.

**Comment by tlhintoq** [comment]
Installed it this morning (19jan2017 at 0530hrs) from the gallery and it worked great.  Thrilled to have this tool back!  Thanks!

**Comment by xperiandri** [comment]
Does not work in Blend 2017. Not menu item at all.
Does anyone experience the same?

**Comment by NicoVermeir** [comment]
@xperiandri adding Blend support requires a special signing key from MS, that key has changed from Blend 2015 to Blend 2017 so unfortunately we'll have to see if we can get our hands on the new key.

**Comment by xperiandri** [comment]
What is the process of receiving such key? Maybe I can force this process.

**Comment by NicoVermeir** [comment]
The process is me sending an email to the right people :) mail has been sent, awaiting reply

**Comment by xperiandri** [comment]
I can chat that people. So if they will not respond for a long time you can ask me to chat and ask them
