### ISSUE TITLE
Add/Update Settings Documentation

### ISSUE THREAD

**Issue by grochocki** [Xavalon/XamlStyler#7]
There are a number of settings names and descriptions in options that are not clear. Additionally, documentation should be added to provide more information on the effects of each option, including conflicts that may arise when setting conflicting options.

**Comment by OvestLabs** [comment]
Hello @grochocki 

I started using this extension for my own dev environment and I love it. Thank you so much for taking the time to knock it out. I recently updated the extension to the latest version and found that you added support for an _External Configuration File_. This is awesome. Now I can make it a standard among the team. The only issue is... I don't know how. There are no instructions on how make this config file. Do you have a sample you can post here while you work on updating settings documentation?

Kind regards,
Laith

**Comment by grochocki** [comment]
We are looking into expanding documentation for XAML Styler. For the time being, I added a section at the [bottom of the main page ](https://github.com/Xavalon/XamlStyler) about external configurations, including the "default configuration".

**Comment by grochocki** [comment]
[Documentation](https://github.com/Xavalon/XamlStyler/wiki) has been fully updated.
