### ISSUE TITLE
Document setting IndentSize for Console Exe?

### ISSUE THREAD

**Issue by Bill77** [Xavalon/XamlStyler#77]
First of all, props on a great tool, really helping our team to standardize property ordering. :+1: 

Because we were making whole sale changes to all of our project's XAML files, I decided to run a batch file to process all the XAML files at once. Which I'll detail below for anyone else that needs to do this. :smile: 

An edge case issue I ran into was we use 4 space indentations in our XAML, so while this works fine in the VS Extension since you can read that value prior to saving. The console application defaults to 2 space indentation (no VS to read the setting from). 

So in the end I cloned the repository and discovered that there is a JSON property `IndentSize` which I can set manually, specifically to support the console app. Which I did and resolves my problem. 

Be happy to make a pull request to the Wiki if that'll be helpful.

Thanks,
Bill

**Steps to Run XAML Styler on all project files (on Win Machine)**

* Run on a command prompt: `dir /S /B *.xaml > allxaml.bat`
* Modify the batch file and insert the `xstyler.exe` call with a format like so:
`.\xstyler.exe -f "abc.xaml"`
* Execute the batch file

**Comment by grochocki** [comment]
Thanks for the batch file! I will add it to the list of recipes. With #76, we are adding a directory parameter, so you will soon be able to make this even easier with a call like:

````sh
> ./xstyler.exe -r -d "C:\Repo\Projects\SolutionDirectory"
````

> discovered that there is a JSON property IndentSize which I can set manually

Yep :) I suppose this was kind of unnecessarily secret. I will update the documentation to show this as an optional configuration option that you can add.

**Comment by Bill77** [comment]
Awesome, thanks for the quick and effective feedback! :+1:

**Comment by grochocki** [comment]
Added to the Wiki. Thanks again!

**Comment by Bill77** [comment]
Oops, looks like there was a cut&paste error on the page. :smile: 

The [Wiki Indent Size Example](https://github.com/Xavalon/XamlStyler/wiki/External-Configurations) says:
`"CommentIndent": 2` instead of `"IndentSize: 2"`

**Comment by grochocki** [comment]
Fixed, thanks!
