### ISSUE TITLE
WPF Hyperlink format wrong

### ISSUE THREAD

**Issue by h82258652** [Xavalon/XamlStyler#81]
I have a textblock like this:
```XAML
            <TextBlock>
                <Run /><Hyperlink><Run /></Hyperlink><Run /></TextBlock>
```
but after I use xaml styler format my xaml code.
```XAML
            <TextBlock>
                <Run />
                <Hyperlink><Run /></Hyperlink><Run /></TextBlock>
```
Hyperlink is placed to a new line. It will display a space which I don't need.

**Comment by NicoVermeir** [comment]
can you use the Newline exemption elements option?
![image](https://cloud.githubusercontent.com/assets/3177418/21841645/681d333a-d7e3-11e6-91b8-cea545e6873c.png)

**Comment by h82258652** [comment]
@NicoVermeir Thanks for response.
I try add Hyperlink, Run and TextBlock in the list, it still not work for me, the Hyperlink always at the newline after I use xaml styler format my code.

**Comment by h82258652** [comment]
It seems only Run element will be formatted on the same line.
https://github.com/Xavalon/XamlStyler/blob/08c146490ae3cdd3e72d0a51233e1807eb385b17/XamlStyler.Core/DocumentProcessors/ElementDocumentProcessor.cs
I think elements in TextBlock should not be formatted on the newline.

**Comment by NicoVermeir** [comment]
I'm currently looking into this (sorry that it took so long)

I don't quite understand the case, what is the first Run tag for?

At first glance this looks like an edge case that would require some specific checks and would rarely be used.
