### ISSUE TITLE
Attribute indentation behaves differently from earlier version. Value 0's is larger than 2's

### ISSUE THREAD

**Issue by HowRuud** [Xavalon/XamlStyler#86]
Attribute indentation behaves differently from earlier version. Value 0's is larger than 2's

**Comment by Fluwit** [comment]
More specifically:
- Indentation of -2 is aligned completely to the left.
- Indentation of 0 puts attributes to the right of -2.
- Indentation of 2 puts attributes between -2 and 0.
- Indentation of 10 puts attributes to the right of 0.

Not sure how to provide more details about this issue.

**Comment by grochocki** [comment]
Are you running VS2015 or VS2017?

I am seeing the following for Indentation < 0 (effective indentation is 0):
```xml
        <TextBlock
        FontSize="12"
        FontWeight="Bold"
        Foreground="Black"
        Text="Attribute Indentation" />
```

For Indentation = 0 (default; respects VS settings; effective indentation is 4, unless you change VS settings):
```xml
        <TextBlock
            FontSize="12"
            FontWeight="Bold"
            Foreground="Black"
            Text="Attribute Indentation" />
```

For Indentation = 2 (effective indentation is 2):
```xml
        <TextBlock
          FontSize="12"
          FontWeight="Bold"
          Foreground="Black"
          Text="Attribute Indentation" />
```

For Indentation = 10 (effective indentation is 10):
```xml
        <TextBlock
                  FontSize="12"
                  FontWeight="Bold"
                  Foreground="Black"
                  Text="Attribute Indentation" />
```

**Comment by HowRuud** [comment]
Hello,

We are using VS 2015.
Your explanation makes sense but from an end user's perspective it does not make sense that the value 0 is the VS default setting instead of a effective 0. In my humble opinion case 1 and 2 should be switched.

Sincerely,

Ruud

**Comment by grochocki** [comment]
Completely valid point, but there is not a great way of updating this behavior without a breaking change. I did update the [Attribute Indentation](https://github.com/Xavalon/XamlStyler/wiki/Attribute-Formatting#attribute-indentation) section of the Wiki with examples to help reduce confusion. If this continues to be a sticking point in the future, we can revisit it.
