### ISSUE TITLE
Do not format TextBlock content

### ISSUE THREAD

**Issue by RSuter** [Xavalon/XamlStyler#87]
The extension should not format the content of TextBlocks: 

Assuming I have this TextBlock: 

```
<TextBlock>
	<Run Text="Events (" /><Run Text="{Binding Events.Count, Mode=OneWay}" /><Run Text=")" />
</TextBlock>
```

The output is: "Events (0)"

After formatting with XAML Styler, the XAML looks like: 

```
<TextBlock>
	<Run Text="Events (" />
        <Run Text="{Binding Events.Count, Mode=OneWay}" />
        <Run Text=")" />
</TextBlock>
```

Which is not the same (because XAML does not ignore the added whitespaces): "Events ( 0 )"

This is why XAML Styler should not format the content of TextBlock. Can you implement this exception?

**Comment by NicoVermeir** [comment]
I tried reproducing this but the Run tag stays on the same line for me.
Can you verify that this behavior is still occuring with the latest version of XAML Styler?

**Comment by grochocki** [comment]
Closing bug due to lack of repro. @RSuter, if you continue to run into this on the latest version, feel free to reactivate with more details.

**Comment by RSuter** [comment]
Seems to work with v3. Thank you.
