### ISSUE TITLE
Can't install in VS2017 RC

### ISSUE THREAD

**Issue by Licantrop0** [Xavalon/XamlStyler#89]
installed through extension and updates.
here the log results:

1/21/2017 12:05:02 AM - Microsoft VSIX Installer
1/21/2017 12:05:02 AM - -------------------------------------------
1/21/2017 12:05:02 AM - vsixinstaller.exe version:
1/21/2017 12:05:02 AM - 15.0.26020.0 built by: D15REL
1/21/2017 12:05:02 AM - -------------------------------------------
1/21/2017 12:05:02 AM - Command line parameters:
1/21/2017 12:05:02 AM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe,/skuName:Enterprise,/skuVersion:15.0.26020.0,/appidname:Microsoft Visual Studio Enterprise 2017 RC,C:\Users\luca_\AppData\Local\Temp\VSIX5yfo2kmy.vsix
1/21/2017 12:05:02 AM - -------------------------------------------
1/21/2017 12:05:02 AM - Microsoft VSIX Installer
1/21/2017 12:05:02 AM - -------------------------------------------
1/21/2017 12:05:03 AM - Initializing Install...
1/21/2017 12:05:03 AM - Extension Details...
1/21/2017 12:05:03 AM - 	Identifier         : 0c572937-0d4a-48cc-aa3f-875ffa9805ba
1/21/2017 12:05:03 AM - 	Name               : XAML Styler
1/21/2017 12:05:03 AM - 	Author             : Xavalon
1/21/2017 12:05:03 AM - 	Version            : 3.0
1/21/2017 12:05:03 AM - 	Description        : XAML Styler is a visual studio extension, which formats XAML source code by sorting the attributes based on their importance. This tool can help you/your team maintain a better XAML coding style as well as a much better XAML readability.
1/21/2017 12:05:03 AM - 	Locale             : en-US
1/21/2017 12:05:03 AM - 	MoreInfoURL        : https://github.com/Xavalon/XamlStyler/
1/21/2017 12:05:03 AM - 	InstalledByMSI     : False
1/21/2017 12:05:03 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
1/21/2017 12:05:03 AM - 
1/21/2017 12:05:03 AM - 	SignatureState     : Unsigned
1/21/2017 12:05:03 AM - 	Supported Products : 
1/21/2017 12:05:03 AM - 		Microsoft.VisualStudio.Pro
1/21/2017 12:05:03 AM - 			Version : [15.0,16.0)
1/21/2017 12:05:03 AM - 		Microsoft.VisualStudio.Enterprise
1/21/2017 12:05:03 AM - 			Version : [15.0,16.0)
1/21/2017 12:05:03 AM - 		Microsoft.VisualStudio.Community
1/21/2017 12:05:03 AM - 			Version : [15.0,16.0)
1/21/2017 12:05:03 AM - 
1/21/2017 12:05:03 AM - 	References         : 
1/21/2017 12:05:03 AM - 		-------------------------------------------------------
1/21/2017 12:05:03 AM - 		Identifier   : Microsoft.VisualStudio.MPF.15.0
1/21/2017 12:05:03 AM - 		Name         : Visual Studio MPF 15.0
1/21/2017 12:05:03 AM - 		Version      : [15.0]
1/21/2017 12:05:03 AM - 		MoreInfoURL  : 
1/21/2017 12:05:03 AM - 		Nested       : No
1/21/2017 12:05:03 AM - 
1/21/2017 12:05:03 AM - 	Prerequisites      : 
1/21/2017 12:05:03 AM - 		-------------------------------------------------------
1/21/2017 12:05:03 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
1/21/2017 12:05:03 AM - 		Name         : Visual Studio core editor
1/21/2017 12:05:03 AM - 		Version      : [15.0.25904.2,16.0)
1/21/2017 12:05:03 AM - 
1/21/2017 12:05:03 AM - Signature Details...
1/21/2017 12:05:03 AM - 	Extension is not signed.
1/21/2017 12:05:03 AM - 
1/21/2017 12:05:04 AM - The extension with ID '0c572937-0d4a-48cc-aa3f-875ffa9805ba' is not installed to Microsoft Visual Studio Enterprise 2017 RC.
1/21/2017 12:05:18 AM - The following target products have been selected...
1/21/2017 12:05:18 AM - 	Microsoft Visual Studio Enterprise 2017 RC
1/21/2017 12:05:18 AM - 
1/21/2017 12:05:18 AM - Beginning to install extension to Microsoft Visual Studio Enterprise 2017 RC...
1/21/2017 12:05:19 AM - Install Error : System.IO.FileNotFoundException: Unable to find the specified file.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetCurrentSetupInstance()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
1/21/2017 12:05:19 AM - VSIX TaskScheduler: VSIX Auto Updatetask already exists.

**Comment by NicoVermeir** [comment]
can you install other extensions into VS2017?
if so, what targets have you selected when installing VS2017? (desktop dev, web dev, ...)

**Comment by Licantrop0** [comment]
Oh, you're right, I can't install other extension (same error...)
I have selected UWP, .Net and Xamarin...
I'll open a bug with VS.
