### ISSUE TITLE
Setting for Attributes on Single Line unless character length exceeds value

### ISSUE THREAD

**Issue by ericmschmidt** [Xavalon/XamlStyler#91]
I'm not sure if this is already a feature and I can't find it or if it's not a feature yet, but I'm looking for an option to keep all attributes on a single line, unless the total number of characters on that line exceed a certain character limit (including the indentation spaces). This would help keep the XAML definitions on a single line unless it required some side scrolling, which often makes XAML more difficult to read.

**Comment by grochocki** [comment]
Check out [Max Attribute Characters Per Line](https://github.com/Xavalon/XamlStyler/wiki/Attribute-Formatting#max-attribute-characters-per-line). You may need to tweak a few other settings as well to achieve the effect you are after.
