### ISSUE TITLE
Ability to locate external configuration automatically

### ISSUE THREAD

**Issue by marcells** [Xavalon/XamlStyler#93]
It would be nice, if the location of the external configuration could be done automatically by searching them from the current folder until the drive root (like `stylecop.json`). So it is easily possible to work in different branches and developers don't have to setup anything.

So, if possible, then:
1. Project level
2. Solution level
3. Development dircetory level
4. Until root of the hard drive

If that could not be done easily, then at least a check for `xamlstyler.json` at the solution level would be great.

**Comment by grochocki** [comment]
This feature is already available, though the documentation has not been updated (will keep this issue open to track updating documentation). Drop "Settings.XamlStyler" in any directory up through your solution directory and both the plugin and standalone will check for that.

**Comment by marcells** [comment]
Awesome! Thank you!

**Comment by grochocki** [comment]
Just updated wiki with [a few important details](https://github.com/Xavalon/XamlStyler/wiki/External-Configurations) about this feature.
