### ISSUE TITLE
Newline exemption elements bug

### ISSUE THREAD

**Issue by jizc** [Xavalon/XamlStyler#94]
With default settings, I'm seeing a lot of extra white space for line like this one:
`<Setter Property="Template" Value="{DynamicResource {ComponentResourceKey ResourceId=SubmenuItemTemplateKey,                      TypeInTargetAssembly={x:Type MenuItem}}}" />`

Here is a screenshot, since Github just removes the extra white space:
![image](https://cloud.githubusercontent.com/assets/1404846/23712363/fd1a3b34-0422-11e7-9f62-e198f7aea593.png)

My assumption is that the line first gets formatted to several lines, but then due to `Setter` being part of "Newline exemption elements", XamlStyler attempts to put it back on one line, but forgets to remove some of the white space.

**Comment by TheMcCann** [comment]
I hit this issue as well.  It looks like it only occurs when there's a markup extension nested within another markup extension.  Even with "Enable markup extension formatting" disabled, it still does it.  The only interim solution I've found is to add the nested markup extension to the "Keep markup extensions of these types on one line" list.  In your case, "ComponentResourceKey".

**Comment by jizc** [comment]
Thanks for the tip @TheMcCann!

**Comment by chvogel** [comment]
Thanks to @GreenKn1ght for pointing out that I created a duplicate issue at #99 (but has some additional information).
