### ISSUE TITLE
Make 'Format XAML on save' setting default to False

### ISSUE THREAD

**Issue by rsheptolut** [Xavalon/XamlStyler#95]
XAML Magic had it default to false.

1. Open a whole lot of files in Visual Studio, including some .xaml files, forget all about them.
2. Edit some .cs files, then press Ctrl+Shift+S to save all changes in them.
3. XAML Styler treats this as a "Save" on all open xaml files and formats them, and you get a lot of mysterious changes in your source control. You didn't intend these xaml files to change at all!
4. Revert changes in source control.
5. Repeat a couple of times to realize what's wrong.

I think it's not a useful default, it should be opt-in. Or at least try to fix this feature to format XAML only if file has some changes to save. 
XAML Styler is a great extension, it's good that it's highly configurable, but it also should have robust defaults for folks like me, who only want to see a "Make it awesome" button.

**Comment by grochocki** [comment]
I agree, which is why I changed the default for XAML Magic :) I am open to changing it for XAML Styler as well, though I would like to leave this issue open a bit for comment before taking any action . Are there any objections?

**Comment by NicoVermeir** [comment]
well, it's been the default for XAML Styler since forever, I like this default personally :)
it's only one setting, quickly switched off, so why change / break existing behavior for every other user?

**Comment by rsheptolut** [comment]
Just to elaborate my point some more:
1. This change shouldn't break anything for those who already have XAML Styler installed, it should only affect those who are installing XAML Styler.
2. When you first install XAML Styler:
a) you're a recurring user (reinstalled your OS or something like that) and you're familiar with XAML Styler behavior and settings, so yeah, no problem switching this one on, if it is defaulted to false. Or maybe you have a setting file in your repo (do you have one of those?).
b) you're a new user and you'd be surprised that this extension formats files which you did not intend to even change at all.
3. When you use XAML Styler:
a) All members of a team have XAML Styler installed and configured to the same settings, they're likely to give this some attention anyway: tweak some settings, save settings file to repo.
b) But if just one member of a team who wants to give XAML Styler a try in an existing messy project - it results in tonns of unexpected long diffs for xaml files. For example, I apply XAML Styler only for new or completely refactored xaml files, and leave the legacy ones as they are for now.

**Comment by BrunoJuchli** [comment]
If xaml styler could auto-pick-up external config files, p.Ex. saved alongside the solution with a file name xamlstyler.config, the pain of changing defaults like this would lessen a lot.
Also, when setting up a new developer machine for a team member that would make one setup step superfluous (configuring xaml styler to use the external config file). Over the past few years, we had the issue of non-matching configs several times.

**Comment by grochocki** [comment]
@BrunoJuchli, you only need to specify an external configuration in settings if the settings file is not already in the solution. See the [External Configurations](https://github.com/Xavalon/XamlStyler/wiki/External-Configurations) section in the wiki for more information.

**Comment by BrunoJuchli** [comment]
@grochocki 
sorry, I must have been very blind when I read that page yesterday! Completely missed it. Thanks

**Comment by grochocki** [comment]
While we understand some developers prefer to have this option disabled (myself included), there are likely just as many developers who prefer it enabled. Since this setting has been enabled by default for a _long_ time and it is easy to turn the setting off, we have decided that we are going to leave the current default. Thanks for the discussion on this!

**Comment by Ethanon** [comment]
This is still a bloody issue. Drives me nuts that I have NO xaml files opened and it then opens and formats every xaml file in my project.

**Comment by grochocki** [comment]
> Drives me nuts that I have NO xaml files opened and it then opens and formats every xaml file in my project.

Hmm, while this setting would make the issue you describe worse, it sounds like it might be related to #56. By default, <kbd>Ctrl</kbd><kbd>S</kbd> should only save the current document. Opening and formatting all XAML files should only work if you right click on solution items (see #260 for screenshots).
