### ISSUE TITLE
[Help] External Configuration Multi-Project Example

### ISSUE THREAD

**Issue by amkuchta** [Xavalon/XamlStyler#96]
Does anyone have an External Configuration file example that they can share that shows implementation with multiple projects?  The wiki shows the default configuration, but does not give much detail on how to modify / apply it to multiple projects (with different settings for each project).

Thanks in advance!

**Comment by grochocki** [comment]
Just updated wiki with [a few important details](https://github.com/Xavalon/XamlStyler/wiki/External-Configurations) on how to accomplish the scenario you are after.

**Comment by amkuchta** [comment]
@grochocki Thanks for the update!  I implemented a `Settings.XamlStyler` file, and it _almost_ works perfectly... The only isue is that it does not appear to be honoring `"FormatMarkupExtension" : true`.  Any thoughts on why?  (And should I open a new issue?)

**Comment by grochocki** [comment]
Could it be related to #94?
