### ISSUE TITLE
Unwanted spaces in nested markup extension

### ISSUE THREAD

**Issue by chvogel** [Xavalon/XamlStyler#99]
Affected version: VS 2015 / 2.4 (haven't checked with VS 2017 / 3.0)
Settings: all settings left to default values

Input:
`<Node Attr="{ExtensionA {ExtensionB AttrB1=ValueA, AttrB2=ValueB}}" />`

Expected result (no change):
`<Node Attr="{ExtensionA {ExtensionB AttrB1=ValueA, AttrB2=ValueB}}" />`

Actual result:
`<Node Attr="{ExtensionA {ExtensionB AttrB1=ValueA, ___________AttrB2=ValueB}}" />`
=> Additional spaces (replaced with _ here) exactely the length of '{ExtensionB' are inserted before AttrB2 (and any following attributes).

Note:
Only happens when ExtensionB is passed directly to ExtensionA without an attribute.
The following structure doesn't cause the issue:
`<Node Attr="{ExtensionA AttrA={ExtensionB AttrB1=ValueA, AttrB2=ValueB}}" />`

**Comment by GreenKn1ght** [comment]
Is it a duplicate?

**Comment by chvogel** [comment]
Yup, looks like it.
I searched for existing issues about my problem but somehow missed that one.

**Comment by grochocki** [comment]
Resolving issue, since there is already an active issue tracking it.
